#!/usr/bin/env python3
"""Render Phase-5 dual-MTS quick CSR evidence as an HTML report.

The report is intentionally derived from the raw JSON artifacts emitted by the
System Console slow-control matrix runner. The PNG screenshots are generated by
``show_phase5_histogram_matrix_gui.py`` and are treated as visual evidence of
those captured CSR transactions, not as a fresh live toolkit capture.
"""

from __future__ import annotations

import html
import json
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


SCRIPT_DIR = Path(__file__).resolve().parent
SYSTEM_DIR = SCRIPT_DIR.parent
REPORT_DIR = SYSTEM_DIR / "reports"
SCREENSHOT_DIR = REPORT_DIR / "screenshots" / "dualmts_20260429"
ASSET_DIR = REPORT_DIR / "assets" / "phase5_dualmts_20260429"
OUT_HTML = REPORT_DIR / "phase5_dualmts_quick_csr_closure_20260429.html"

JSON_FILES = [
    REPORT_DIR / "phase5_hist_matrix_dualmts_lane4_delay100k_quick_20260429.json",
    REPORT_DIR / "phase5_hist_matrix_dualmts_lane0_delay100k_quick_20260429.json",
    REPORT_DIR / "phase5_hist_matrix_dualmts_lane4_rate100k_10k_quick_20260429.json",
    REPORT_DIR / "phase5_hist_matrix_dualmts_emulator_all_delay100k_quick_20260429.json",
    REPORT_DIR / "phase5_hist_matrix_dualmts_emulator_all_rate100k_10k_quick_20260429.json",
    REPORT_DIR / "phase5_hist_matrix_dualmts_emulator_all_header1_2_4_quick_20260429.json",
]

FIRMWARE_NOTE = "top_nostp_pipe dual-MTS histogram 26.1.4 Quartus checksum 0x13DB4566 cksum 0xB4F49A95"
SOF_SHA256 = "136c2d5df538a12713b7138cf775128d633993c3411f9040f4f300d9aae0c8cc"
COMPILE_LOG = "../syn/board_projects/fe_scifi_feb_v3/quartus_compile_top_nostp_pipe_dualmts_debug_20260429.console.log"
PROGRAM_LOG = "../syn/board_projects/fe_scifi_feb_v3/program_top_nostp_pipe_dualmts_debug_20260429.log"


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def rel(path: Path) -> str:
    return path.relative_to(REPORT_DIR).as_posix()


def load_payloads() -> list[tuple[Path, dict]]:
    payloads: list[tuple[Path, dict]] = []
    for path in JSON_FILES:
        payloads.append((path, json.loads(path.read_text(encoding="utf-8"))))
    return payloads


def scope_key(scope: str) -> tuple[int, int | str]:
    if scope == "all":
        return (0, 0)
    if scope.startswith("lane"):
        try:
            return (1, int(scope[4:]))
        except ValueError:
            pass
    return (2, scope)


def scenario_records(payload: dict, scenario: str) -> list[dict]:
    return [rec for rec in payload.get("records", []) if rec.get("scenario") == scenario]


def record_map(payload: dict, scenario: str) -> dict[str, dict]:
    return {rec["scope"]: rec for rec in scenario_records(payload, scenario)}


def summary_value(rec: dict, name: str) -> int:
    return int(rec.get("summary", {}).get(name, 0))


def fmt_int(value: int) -> str:
    return f"{value:,}"


def fmt_ratio(value: float | None) -> str:
    if value is None:
        return "-"
    return f"{value:.2f}x"


def status_badge(status: str) -> str:
    cls = {
        "PASS": "pass",
        "PASS_PARTIAL": "partial",
        "FAIL": "fail",
        "BLOCKED": "blocked",
    }.get(status, "fail")
    return f'<span class="badge {cls}">{esc(status)}</span>'


def write_rate_plot(payload: dict) -> Path:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    r100 = record_map(payload, "rate_100k")
    r10 = record_map(payload, "rate_10k")
    scopes = sorted(set(r100) & set(r10), key=scope_key)
    hist_ratios = []
    mts_ratios = []
    for scope in scopes:
        h10 = summary_value(r10[scope], "hist_total_delta")
        m10 = summary_value(r10[scope], "mts_total_delta")
        hist_ratios.append(summary_value(r100[scope], "hist_total_delta") / h10 if h10 else 0.0)
        mts_ratios.append(summary_value(r100[scope], "mts_total_delta") / m10 if m10 else 0.0)

    fig, ax = plt.subplots(figsize=(10.5, 4.8), constrained_layout=True)
    x = list(range(len(scopes)))
    width = 0.36
    ax.bar([v - width / 2 for v in x], hist_ratios, width, label="hist total ratio")
    ax.bar([v + width / 2 for v in x], mts_ratios, width, label="MTS total ratio")
    ax.axhline(10.0, color="#5d6d7e", linewidth=1.3, linestyle="--", label="expected 10x")
    ax.set_title("Rate-mode 100k / 10k scaling from CSR deltas")
    ax.set_ylabel("ratio")
    ax.set_ylim(0, max(12.0, max(hist_ratios + mts_ratios) * 1.12))
    ax.set_xticks(x)
    ax.set_xticklabels(scopes, rotation=0)
    ax.grid(axis="y", color="#d5d8dc", linewidth=0.8)
    ax.legend(loc="upper right")
    out = ASSET_DIR / "phase5_dualmts_rate_scaling.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def write_header_plot(payload: dict) -> Path:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    h1 = record_map(payload, "header_1")
    h2 = record_map(payload, "header_2")
    h4 = record_map(payload, "header_4")
    scopes = sorted(set(h1) & set(h2) & set(h4), key=scope_key)
    ratio2 = []
    ratio4 = []
    for scope in scopes:
        base = summary_value(h1[scope], "hist_total_delta")
        ratio2.append(summary_value(h2[scope], "hist_total_delta") / base if base else 0.0)
        ratio4.append(summary_value(h4[scope], "hist_total_delta") / base if base else 0.0)

    fig, ax = plt.subplots(figsize=(10.5, 4.8), constrained_layout=True)
    x = list(range(len(scopes)))
    width = 0.36
    ax.bar([v - width / 2 for v in x], ratio2, width, label="2/header over 1/header")
    ax.bar([v + width / 2 for v in x], ratio4, width, label="4/header over 1/header")
    ax.axhline(2.0, color="#2874a6", linewidth=1.2, linestyle="--", label="expected 2x")
    ax.axhline(4.0, color="#922b21", linewidth=1.2, linestyle="--", label="expected 4x")
    ax.set_title("Header-mode hit scaling from CSR deltas")
    ax.set_ylabel("ratio")
    ax.set_ylim(0, max(5.0, max(ratio2 + ratio4) * 1.12))
    ax.set_xticks(x)
    ax.set_xticklabels(scopes, rotation=0)
    ax.grid(axis="y", color="#d5d8dc", linewidth=0.8)
    ax.legend(loc="upper right")
    out = ASSET_DIR / "phase5_dualmts_header_scaling.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def write_delay_plot(payload: dict) -> Path:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    records = sorted(scenario_records(payload, "delay_100k"), key=lambda rec: scope_key(rec["scope"]))
    scopes = [rec["scope"] for rec in records]
    hist = [summary_value(rec, "hist_total_delta") for rec in records]
    mts = [summary_value(rec, "mts_total_delta") for rec in records]

    fig, ax = plt.subplots(figsize=(10.5, 4.8), constrained_layout=True)
    x = list(range(len(scopes)))
    width = 0.36
    ax.bar([v - width / 2 for v in x], hist, width, label="hist total")
    ax.bar([v + width / 2 for v in x], mts, width, label="MTS total")
    ax.set_title("Delay-mode 100k CSR deltas")
    ax.set_ylabel("delta counts")
    ax.set_xticks(x)
    ax.set_xticklabels(scopes, rotation=0)
    ax.grid(axis="y", color="#d5d8dc", linewidth=0.8)
    ax.ticklabel_format(axis="y", style="plain")
    ax.legend(loc="upper right")
    out = ASSET_DIR / "phase5_dualmts_delay_counts.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def make_artifact_rows(payloads: list[tuple[Path, dict]]) -> str:
    rows = []
    for path, payload in payloads:
        records = payload.get("records", [])
        counts = Counter(rec.get("status", "UNKNOWN") for rec in records)
        scenarios = ", ".join(sorted({rec.get("scenario", "-") for rec in records}))
        result = "PASS" if counts and counts.get("PASS", 0) == len(records) else "PARTIAL"
        md_path = path.with_suffix(".md")
        rows.append(
            "<tr>"
            f"<td><a href=\"{esc(rel(md_path))}\">{esc(md_path.name)}</a><br>"
            f"<a href=\"{esc(rel(path))}\">raw JSON</a></td>"
            f"<td>{status_badge(result)}</td>"
            f"<td>{esc(scenarios)}</td>"
            f"<td>{len(records)}</td>"
            f"<td>{counts.get('PASS', 0)} / {counts.get('PASS_PARTIAL', 0)} / {counts.get('FAIL', 0)} / {counts.get('BLOCKED', 0)}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def make_rate_rows(payload: dict) -> str:
    r100 = record_map(payload, "rate_100k")
    r10 = record_map(payload, "rate_10k")
    scopes = sorted(set(r100) & set(r10), key=scope_key)
    rows = []
    for scope in scopes:
        h100 = summary_value(r100[scope], "hist_total_delta")
        h10 = summary_value(r10[scope], "hist_total_delta")
        m100 = summary_value(r100[scope], "mts_total_delta")
        m10 = summary_value(r10[scope], "mts_total_delta")
        rows.append(
            "<tr>"
            f"<td>{esc(scope)}</td>"
            f"<td>{fmt_int(h100)}</td>"
            f"<td>{fmt_int(h10)}</td>"
            f"<td>{fmt_ratio(h100 / h10 if h10 else None)}</td>"
            f"<td>{fmt_int(m100)}</td>"
            f"<td>{fmt_int(m10)}</td>"
            f"<td>{fmt_ratio(m100 / m10 if m10 else None)}</td>"
            f"<td>{status_badge(r100[scope].get('status', '-'))}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def make_header_rows(payload: dict) -> str:
    h1 = record_map(payload, "header_1")
    h2 = record_map(payload, "header_2")
    h4 = record_map(payload, "header_4")
    scopes = sorted(set(h1) & set(h2) & set(h4), key=scope_key)
    rows = []
    for scope in scopes:
        base = summary_value(h1[scope], "hist_total_delta")
        two = summary_value(h2[scope], "hist_total_delta")
        four = summary_value(h4[scope], "hist_total_delta")
        rows.append(
            "<tr>"
            f"<td>{esc(scope)}</td>"
            f"<td>{fmt_int(base)}</td>"
            f"<td>{fmt_int(two)}</td>"
            f"<td>{fmt_ratio(two / base if base else None)}</td>"
            f"<td>{fmt_int(four)}</td>"
            f"<td>{fmt_ratio(four / base if base else None)}</td>"
            f"<td>{status_badge(h1[scope].get('status', '-'))}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def make_delay_rows(payload: dict) -> str:
    rows = []
    for rec in sorted(scenario_records(payload, "delay_100k"), key=lambda item: scope_key(item["scope"])):
        rows.append(
            "<tr>"
            f"<td>{esc(rec.get('scope', '-'))}</td>"
            f"<td>{fmt_int(summary_value(rec, 'hist_total_delta'))}</td>"
            f"<td>{fmt_int(summary_value(rec, 'mts_total_delta'))}</td>"
            f"<td>{fmt_int(summary_value(rec, 'hist_drop_delta'))}</td>"
            f"<td>{fmt_int(summary_value(rec, 'frame_crc_delta'))}</td>"
            f"<td>{fmt_int(summary_value(rec, 'ring_inerr_delta'))}</td>"
            f"<td>{status_badge(rec.get('status', '-'))}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def figure_html(path: Path, caption: str) -> str:
    return (
        "<figure>"
        f"<a href=\"{esc(rel(path))}\"><img src=\"{esc(rel(path))}\" alt=\"{esc(caption)}\" loading=\"lazy\"></a>"
        f"<figcaption>{esc(caption)}</figcaption>"
        "</figure>"
    )


def screenshot_gallery(paths: Iterable[Path]) -> str:
    figures = []
    for path in sorted(paths):
        caption = path.stem.replace("phase5_hist_matrix_dualmts_", "").replace("_quick_20260429", "")
        caption = caption.replace("_", " ")
        figures.append(figure_html(path, caption))
    return "\n".join(figures)


def write_html(payloads: list[tuple[Path, dict]], plots: list[Path]) -> None:
    payload_by_name = {path.name: payload for path, payload in payloads}
    rate_payload = payload_by_name["phase5_hist_matrix_dualmts_emulator_all_rate100k_10k_quick_20260429.json"]
    header_payload = payload_by_name["phase5_hist_matrix_dualmts_emulator_all_header1_2_4_quick_20260429.json"]
    delay_payload = payload_by_name["phase5_hist_matrix_dualmts_emulator_all_delay100k_quick_20260429.json"]
    screenshots = sorted(SCREENSHOT_DIR.glob("*.png"))

    html_text = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Phase 5 dual-MTS quick CSR closure evidence</title>
  <style>
    :root {{
      color-scheme: light;
      --ink: #17202a;
      --muted: #5d6d7e;
      --line: #d5d8dc;
      --panel: #f7f9fb;
      --head: #26323f;
      --pass-bg: #dff5e6;
      --pass-fg: #146c2e;
      --partial-bg: #fff1cc;
      --partial-fg: #8a5a00;
      --fail-bg: #ffd9d9;
      --fail-fg: #9b1c1c;
    }}
    body {{
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
      color: var(--ink);
      background: #ffffff;
      line-height: 1.42;
    }}
    main {{
      width: min(1480px, calc(100vw - 48px));
      margin: 0 auto;
      padding: 28px 0 56px;
    }}
    h1, h2, h3 {{ margin: 0; }}
    h1 {{ font-size: 30px; }}
    h2 {{ margin-top: 34px; font-size: 22px; border-bottom: 1px solid var(--line); padding-bottom: 8px; }}
    h3 {{ margin-top: 20px; font-size: 17px; }}
    p {{ max-width: 1100px; }}
    code {{ background: #eef1f4; padding: 1px 5px; border-radius: 4px; overflow-wrap: anywhere; }}
    a {{ color: #1f618d; overflow-wrap: anywhere; }}
    .meta {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 10px;
      margin-top: 18px;
    }}
    .meta div {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 6px;
      padding: 10px 12px;
    }}
    .note {{
      background: #fff8e6;
      border: 1px solid #f5c967;
      border-radius: 6px;
      padding: 12px 14px;
      margin-top: 18px;
      max-width: 1120px;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      margin-top: 12px;
      font-size: 14px;
    }}
    th {{
      background: var(--head);
      color: #ffffff;
      text-align: left;
      padding: 8px 9px;
      border: 1px solid var(--head);
      white-space: nowrap;
    }}
    td {{
      padding: 7px 9px;
      border: 1px solid var(--line);
      vertical-align: top;
    }}
    tr:nth-child(even) td {{ background: #fbfcfd; }}
    .badge {{
      display: inline-block;
      min-width: 42px;
      text-align: center;
      border-radius: 999px;
      padding: 2px 8px;
      font-weight: 700;
      font-size: 12px;
    }}
    .pass {{ background: var(--pass-bg); color: var(--pass-fg); }}
    .partial {{ background: var(--partial-bg); color: var(--partial-fg); }}
    .fail {{ background: var(--fail-bg); color: var(--fail-fg); }}
    .blocked {{ background: #e8e8e8; color: #4d4d4d; }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(440px, 1fr));
      gap: 18px;
      margin-top: 16px;
    }}
    .screens {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(520px, 1fr));
      gap: 18px;
      margin-top: 16px;
    }}
    figure {{
      margin: 0;
      border: 1px solid var(--line);
      border-radius: 6px;
      background: var(--panel);
      overflow: hidden;
    }}
    figure img {{
      display: block;
      width: 100%;
      height: auto;
      background: #ffffff;
    }}
    figcaption {{
      padding: 8px 10px;
      color: var(--muted);
      font-size: 13px;
      border-top: 1px solid var(--line);
    }}
    .nowrap {{ white-space: nowrap; }}
  </style>
</head>
<body>
<main>
  <h1>Phase 5 dual-MTS quick CSR closure evidence</h1>
  <p>Generated {esc(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))}. This page consolidates the Phase 5 quick CSR evidence captured after the dual-MTS histogram debug firmware was programmed.</p>
  <div class="meta">
    <div><strong>Evidence level</strong><br>quick CSR over SWB System Console slow-control path</div>
    <div><strong>Firmware</strong><br><code>{esc(FIRMWARE_NOTE)}</code></div>
    <div><strong>SOF SHA-256</strong><br><code>{esc(SOF_SHA256)}</code></div>
    <div><strong>Timing gate</strong><br>Quartus compile PASS, slow 85 C setup WNS <code>+0.318 ns</code>, TNS <code>0.000</code></div>
    <div><strong>Compile log</strong><br><a href="{esc(COMPILE_LOG)}">{esc(Path(COMPILE_LOG).name)}</a></div>
    <div><strong>Program log</strong><br><a href="{esc(PROGRAM_LOG)}">{esc(Path(PROGRAM_LOG).name)}</a></div>
  </div>
  <div class="note">
    These screenshots are generated from captured CSR JSON with the System-Console-style matrix viewer under Xvfb. They are not a fresh live Intel System Console toolkit screen capture. The raw JSON and Markdown evidence are linked below and remain authoritative for this quick gate.
  </div>

  <h2>Evidence Index</h2>
  <table>
    <thead><tr><th>Artifact</th><th>Result</th><th>Scenario</th><th>Rows</th><th>PASS / PARTIAL / FAIL / BLOCKED</th></tr></thead>
    <tbody>
{make_artifact_rows(payloads)}
    </tbody>
  </table>

  <h2>Sanity Plots</h2>
  <div class="grid">
    {figure_html(plots[0], "Rate-mode 100k/10k histogram and MTS scaling. Expected ratio is 10x.")}
    {figure_html(plots[1], "Delay-mode 100k histogram and MTS deltas across all and individual emulator lanes.")}
    {figure_html(plots[2], "Header-mode scaling for 2/header and 4/header relative to 1/header.")}
  </div>

  <h2>Rate Matrix</h2>
  <p>All rows use emulator source, separate 100 ms sampling windows, and zero histogram drops, CRC deltas, MTS discards, and ring input errors in the source artifact.</p>
  <table>
    <thead><tr><th>Scope</th><th>Hist 100k</th><th>Hist 10k</th><th>Hist ratio</th><th>MTS 100k</th><th>MTS 10k</th><th>MTS ratio</th><th>Status</th></tr></thead>
    <tbody>
{make_rate_rows(rate_payload)}
    </tbody>
  </table>

  <h2>Delay Matrix</h2>
  <table>
    <thead><tr><th>Scope</th><th>Hist total</th><th>MTS total</th><th>Hist drop</th><th>Frame CRC</th><th>Ring InErr</th><th>Status</th></tr></thead>
    <tbody>
{make_delay_rows(delay_payload)}
    </tbody>
  </table>

  <h2>Header Matrix</h2>
  <table>
    <thead><tr><th>Scope</th><th>1/header hist</th><th>2/header hist</th><th>2/header ratio</th><th>4/header hist</th><th>4/header ratio</th><th>Status</th></tr></thead>
    <tbody>
{make_header_rows(header_payload)}
    </tbody>
  </table>

  <h2>System-Console-Style Screenshots</h2>
  <div class="screens">
{screenshot_gallery(screenshots)}
  </div>

  <h2>Open Closure Items</h2>
  <table>
    <thead><tr><th>Item</th><th>Status</th><th>Reason</th></tr></thead>
    <tbody>
      <tr><td>Live System Console screenshot</td><td>{status_badge("PASS_PARTIAL")}</td><td>This report uses a generated System-Console-style CSR screenshot from raw JSON. A final live toolkit screenshot still belongs in the final closure packet.</td></tr>
      <tr><td>Authentic generated-system <code>tb_int</code> match</td><td>{status_badge("PASS_PARTIAL")}</td><td>Quick board CSR evidence passes; matching simulation evidence for the exact scenario tuple and firmware checksum remains required.</td></tr>
      <tr><td>Real MuTRiG and mixed source matrix</td><td>{status_badge("PASS_PARTIAL")}</td><td>The current full matrix is emulator-source evidence. Real and mixed source closure remain open per <code>TEST_PLAN_PHASE5.md</code>.</td></tr>
      <tr><td>Histogram bin SRAM dump</td><td>{status_badge("PASS_PARTIAL")}</td><td>The quick path excludes <code>hist_bin</code> because this firmware/SC aperture currently returns RSP3.</td></tr>
    </tbody>
  </table>
</main>
</body>
</html>
"""
    OUT_HTML.write_text(html_text, encoding="utf-8")


def main() -> int:
    payloads = load_payloads()
    payload_by_name = {path.name: payload for path, payload in payloads}
    rate_plot = write_rate_plot(payload_by_name["phase5_hist_matrix_dualmts_emulator_all_rate100k_10k_quick_20260429.json"])
    delay_plot = write_delay_plot(payload_by_name["phase5_hist_matrix_dualmts_emulator_all_delay100k_quick_20260429.json"])
    header_plot = write_header_plot(payload_by_name["phase5_hist_matrix_dualmts_emulator_all_header1_2_4_quick_20260429.json"])
    write_html(payloads, [rate_plot, delay_plot, header_plot])
    print(OUT_HTML)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
