import B001_uid_read_test_sv_unit::*;
import B002_uid_write_ignored_test_sv_unit::*;
import B003_meta_versioning_test_sv_unit::*;
import B004_default_mode_real_test_sv_unit::*;
import B005_set_mode_emu_test_sv_unit::*;
import B006_set_mode_mix_rr_test_sv_unit::*;
import B007_real_only_drain_test_sv_unit::*;
import B008_emu_only_drain_test_sv_unit::*;
import B009_mix_rr_merged_packet_alternation_test_sv_unit::*;
import B010_mix_rr_single_beat_absorbed_test_sv_unit::*;
import B011_mix_rr_single_beat_both_idle_test_sv_unit::*;
import B012_switch_at_idle_test_sv_unit::*;
import B013_switch_during_packet_defers_test_sv_unit::*;
import B014_switch_back_to_back_test_sv_unit::*;
import B015_switch_mix_rr_to_real_drains_outstanding_emu_test_sv_unit::*;
import B016_real_fifo_fill_drain_test_sv_unit::*;
import B017_emu_fifo_fill_drain_test_sv_unit::*;
import B018_idle_does_not_consume_test_sv_unit::*;
import B019_ingress_real_hit_counter_test_sv_unit::*;
import B020_ingress_emu_hit_counter_test_sv_unit::*;
import B021_drop_real_counter_test_sv_unit::*;
import B022_drop_emu_counter_test_sv_unit::*;
import B023_egress_real_counter_test_sv_unit::*;
import B024_egress_emu_counter_test_sv_unit::*;
import B025_low_high_pair_atomicity_test_sv_unit::*;
import B026_w1p_clear_counters_test_sv_unit::*;
import B027_csr_back_to_back_writes_test_sv_unit::*;
import B028_channel_convention_test_sv_unit::*;
import B029_watchdog_threshold_default_test_sv_unit::*;
import B030_run_control_run_prep_resets_state_test_sv_unit::*;
import B031_run_control_reset_clears_counters_test_sv_unit::*;
import B032_frame_counters_native_eop_test_sv_unit::*;
import B033_mode_preserved_through_run_test_sv_unit::*;

module B999_basic_factory_anchor;
  initial begin
    void'(B001_uid_read_test::type_id::get());
    void'(B002_uid_write_ignored_test::type_id::get());
    void'(B003_meta_versioning_test::type_id::get());
    void'(B004_default_mode_real_test::type_id::get());
    void'(B005_set_mode_emu_test::type_id::get());
    void'(B006_set_mode_mix_rr_test::type_id::get());
    void'(B007_real_only_drain_test::type_id::get());
    void'(B008_emu_only_drain_test::type_id::get());
    void'(B009_mix_rr_merged_packet_alternation_test::type_id::get());
    void'(B010_mix_rr_single_beat_absorbed_test::type_id::get());
    void'(B011_mix_rr_single_beat_both_idle_test::type_id::get());
    void'(B012_switch_at_idle_test::type_id::get());
    void'(B013_switch_during_packet_defers_test::type_id::get());
    void'(B014_switch_back_to_back_test::type_id::get());
    void'(B015_switch_mix_rr_to_real_drains_outstanding_emu_test::type_id::get());
    void'(B016_real_fifo_fill_drain_test::type_id::get());
    void'(B017_emu_fifo_fill_drain_test::type_id::get());
    void'(B018_idle_does_not_consume_test::type_id::get());
    void'(B019_ingress_real_hit_counter_test::type_id::get());
    void'(B020_ingress_emu_hit_counter_test::type_id::get());
    void'(B021_drop_real_counter_test::type_id::get());
    void'(B022_drop_emu_counter_test::type_id::get());
    void'(B023_egress_real_counter_test::type_id::get());
    void'(B024_egress_emu_counter_test::type_id::get());
    void'(B025_low_high_pair_atomicity_test::type_id::get());
    void'(B026_w1p_clear_counters_test::type_id::get());
    void'(B027_csr_back_to_back_writes_test::type_id::get());
    void'(B028_channel_convention_test::type_id::get());
    void'(B029_watchdog_threshold_default_test::type_id::get());
    void'(B030_run_control_run_prep_resets_state_test::type_id::get());
    void'(B031_run_control_reset_clears_counters_test::type_id::get());
    void'(B032_frame_counters_native_eop_test::type_id::get());
    void'(B033_mode_preserved_through_run_test::type_id::get());
  end
endmodule

bind tb_top B999_basic_factory_anchor basic_factory_anchor();
