# qsys scripting (.tcl) file for scifi_datapath_system
package require -exact qsys 16.0

create_system {scifi_datapath_system}
set_module_property VERSION 1.0.0.0511

set_project_property DEVICE_FAMILY {Arria V}
set_project_property DEVICE {5AGXBA7D4F31C5}
set_project_property HIDE_FROM_IP_CATALOG {false}

# Instances and instance parameters
# (disabled instances are intentionally culled)
add_instance counter_sclr_bridge altera_reset_bridge 18.1
set_instance_parameter_value counter_sclr_bridge {ACTIVE_LOW_RESET} {0}
set_instance_parameter_value counter_sclr_bridge {NUM_RESET_OUTPUTS} {4}
set_instance_parameter_value counter_sclr_bridge {SYNCHRONOUS_EDGES} {deassert}
set_instance_parameter_value counter_sclr_bridge {USE_RESET_REQUEST} {0}

add_instance dbg_conduit2rst conduit2rst 1.0
set_instance_parameter_value dbg_conduit2rst {DEBUG} {1}

add_instance issp_dprst altera_in_system_sources_probes 18.1
set_instance_parameter_value issp_dprst {create_source_clock} {1}
set_instance_parameter_value issp_dprst {create_source_clock_enable} {0}
set_instance_parameter_value issp_dprst {gui_use_auto_index} {0}
set_instance_parameter_value issp_dprst {instance_id} {dprs}
set_instance_parameter_value issp_dprst {probe_width} {0}
set_instance_parameter_value issp_dprst {sld_instance_index} {2}
set_instance_parameter_value issp_dprst {source_initial_value} {0}
set_instance_parameter_value issp_dprst {source_width} {1}

add_instance master_datapath altera_jtag_avalon_master 18.1
set_instance_parameter_value master_datapath {FAST_VER} {0}
set_instance_parameter_value master_datapath {FIFO_DEPTHS} {2}
set_instance_parameter_value master_datapath {PLI_PORT} {50000}
set_instance_parameter_value master_datapath {USE_PLI} {0}

add_instance mm_clock_crossing_bridge altera_avalon_mm_clock_crossing_bridge 18.1
set_instance_parameter_value mm_clock_crossing_bridge {ADDRESS_UNITS} {WORDS}
set_instance_parameter_value mm_clock_crossing_bridge {ADDRESS_WIDTH} {12}
set_instance_parameter_value mm_clock_crossing_bridge {COMMAND_FIFO_DEPTH} {8}
set_instance_parameter_value mm_clock_crossing_bridge {DATA_WIDTH} {32}
set_instance_parameter_value mm_clock_crossing_bridge {MASTER_SYNC_DEPTH} {2}
set_instance_parameter_value mm_clock_crossing_bridge {MAX_BURST_SIZE} {256}
set_instance_parameter_value mm_clock_crossing_bridge {RESPONSE_FIFO_DEPTH} {512}
set_instance_parameter_value mm_clock_crossing_bridge {SLAVE_SYNC_DEPTH} {2}
set_instance_parameter_value mm_clock_crossing_bridge {SYMBOL_WIDTH} {8}
set_instance_parameter_value mm_clock_crossing_bridge {USE_AUTO_ADDRESS_WIDTH} {0}

add_instance monitor_clock_125 clock_source 18.1
set_instance_parameter_value monitor_clock_125 {clockFrequency} {125000000.0}
set_instance_parameter_value monitor_clock_125 {clockFrequencyKnown} {1}
set_instance_parameter_value monitor_clock_125 {resetSynchronousEdges} {NONE}

add_instance mts_preprocessor_nano_0 mts_preprocessor_nano 1.8
set_instance_parameter_value mts_preprocessor_nano_0 {DEBUG} {1}

add_instance mutrig_datapath_subsystem_0 mutrig_datapath_system 1.0
set_instance_parameter_value mutrig_datapath_subsystem_0 {issp_instance_index} {10}

add_instance mutrig_datapath_subsystem_1 mutrig_datapath_system 1.0
set_instance_parameter_value mutrig_datapath_subsystem_1 {issp_instance_index} {11}

add_instance mutrig_datapath_subsystem_2 mutrig_datapath_system 1.0
set_instance_parameter_value mutrig_datapath_subsystem_2 {issp_instance_index} {12}

add_instance mutrig_datapath_subsystem_3 mutrig_datapath_system 1.0
set_instance_parameter_value mutrig_datapath_subsystem_3 {issp_instance_index} {13}

add_instance receiver_clock_125 altera_clock_bridge 18.1
set_instance_parameter_value receiver_clock_125 {EXPLICIT_CLOCK_RATE} {125000000.0}
set_instance_parameter_value receiver_clock_125 {NUM_CLOCK_OUTPUTS} {1}

add_instance receiver_subsystem scifi_lvds_receiver_system 1.0

add_instance reset_bridge_export altera_reset_bridge 18.1
set_instance_parameter_value reset_bridge_export {ACTIVE_LOW_RESET} {0}
set_instance_parameter_value reset_bridge_export {NUM_RESET_OUTPUTS} {1}
set_instance_parameter_value reset_bridge_export {SYNCHRONOUS_EDGES} {none}
set_instance_parameter_value reset_bridge_export {USE_RESET_REQUEST} {0}

# exported interfaces
add_interface areset_iopll_in_reset reset sink
set_interface_property areset_iopll_in_reset EXPORT_OF receiver_subsystem.areset_iopll_in_reset
add_interface avmm_clk clock sink
set_interface_property avmm_clk EXPORT_OF mm_clock_crossing_bridge.s0_clk
add_interface avmm_port avalon slave
set_interface_property avmm_port EXPORT_OF mm_clock_crossing_bridge.s0
add_interface avmm_rst reset sink
set_interface_property avmm_rst EXPORT_OF mm_clock_crossing_bridge.s0_reset
add_interface counter_sclr reset sink
set_interface_property counter_sclr EXPORT_OF reset_bridge_export.in_reset
add_interface m_reset_link_firefly_data avalon_streaming source
set_interface_property m_reset_link_firefly_data EXPORT_OF receiver_subsystem.s_reset_link_firefly_data
add_interface monitor_clock_125_in clock sink
set_interface_property monitor_clock_125_in EXPORT_OF monitor_clock_125.clk_in
add_interface monitor_reset_in_reset reset sink
set_interface_property monitor_reset_in_reset EXPORT_OF monitor_clock_125.clk_in_reset
add_interface mts_preprocessor_nano_0_debug_conduit conduit end
set_interface_property mts_preprocessor_nano_0_debug_conduit EXPORT_OF mts_preprocessor_nano_0.debug_conduit
add_interface r_reset_link_firefly_data avalon_streaming source
set_interface_property r_reset_link_firefly_data EXPORT_OF receiver_subsystem.r_reset_link_firefly_data
add_interface receiver_clock_125_out_clk clock source
set_interface_property receiver_clock_125_out_clk EXPORT_OF receiver_clock_125.out_clk
add_interface reset_req_to_mutrig_reset reset sink
set_interface_property reset_req_to_mutrig_reset EXPORT_OF mts_preprocessor_nano_0.reset_request_interface
add_interface scifi_lvds_rx_0_rx_inclock_pll clock sink
set_interface_property scifi_lvds_rx_0_rx_inclock_pll EXPORT_OF receiver_subsystem.scifi_lvds_rx_0_rx_inclock_pll
add_interface scifi_lvds_rx_0_rx_serial_data conduit end
set_interface_property scifi_lvds_rx_0_rx_serial_data EXPORT_OF receiver_subsystem.scifi_lvds_rx_0_rx_serial_data

# connections and connection parameters
add_connection counter_sclr_bridge.out_reset mutrig_datapath_subsystem_0.sclr_counter_req

add_connection counter_sclr_bridge.out_reset_1 mutrig_datapath_subsystem_1.sclr_counter_req

add_connection counter_sclr_bridge.out_reset_2 mutrig_datapath_subsystem_2.sclr_counter_req

add_connection counter_sclr_bridge.out_reset_3 mutrig_datapath_subsystem_3.sclr_counter_req

add_connection dbg_conduit2rst.reset_source counter_sclr_bridge.in_reset

add_connection dbg_conduit2rst.reset_source mm_clock_crossing_bridge.m0_reset

add_connection dbg_conduit2rst.reset_source mts_preprocessor_nano_0.reset_interface

add_connection dbg_conduit2rst.reset_source mutrig_datapath_subsystem_0.reset

add_connection dbg_conduit2rst.reset_source mutrig_datapath_subsystem_1.reset

add_connection dbg_conduit2rst.reset_source mutrig_datapath_subsystem_2.reset

add_connection dbg_conduit2rst.reset_source mutrig_datapath_subsystem_3.reset

add_connection dbg_conduit2rst.reset_source receiver_subsystem.system_reset_in_reset

add_connection issp_dprst.sources dbg_conduit2rst.reset_in
set_connection_parameter_value issp_dprst.sources/dbg_conduit2rst.reset_in endPort {}
set_connection_parameter_value issp_dprst.sources/dbg_conduit2rst.reset_in endPortLSB {0}
set_connection_parameter_value issp_dprst.sources/dbg_conduit2rst.reset_in startPort {}
set_connection_parameter_value issp_dprst.sources/dbg_conduit2rst.reset_in startPortLSB {0}
set_connection_parameter_value issp_dprst.sources/dbg_conduit2rst.reset_in width {0}

add_connection master_datapath.master mts_preprocessor_nano_0.avmm_debug
set_connection_parameter_value master_datapath.master/mts_preprocessor_nano_0.avmm_debug arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mts_preprocessor_nano_0.avmm_debug baseAddress {0x00010000}
set_connection_parameter_value master_datapath.master/mts_preprocessor_nano_0.avmm_debug defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_0.avmm_errcnt
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.avmm_errcnt arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.avmm_errcnt baseAddress {0x0230}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.avmm_errcnt defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_counter_value
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_counter_value arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_counter_value baseAddress {0x0000}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_counter_value defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_rst_interval
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_rst_interval arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_rst_interval baseAddress {0x0220}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_rst_interval defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_0.mutrig_frame_assembly_csr
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mutrig_frame_assembly_csr arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mutrig_frame_assembly_csr baseAddress {0x0200}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_0.mutrig_frame_assembly_csr defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_1.avmm_errcnt
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.avmm_errcnt arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.avmm_errcnt baseAddress {0x0234}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.avmm_errcnt defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_counter_value
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_counter_value arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_counter_value baseAddress {0x0080}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_counter_value defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_rst_interval
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_rst_interval arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_rst_interval baseAddress {0x0224}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_rst_interval defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_1.mutrig_frame_assembly_csr
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mutrig_frame_assembly_csr arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mutrig_frame_assembly_csr baseAddress {0x0208}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_1.mutrig_frame_assembly_csr defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_2.avmm_errcnt
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.avmm_errcnt arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.avmm_errcnt baseAddress {0x0238}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.avmm_errcnt defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_counter_value
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_counter_value arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_counter_value baseAddress {0x0100}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_counter_value defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_rst_interval
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_rst_interval arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_rst_interval baseAddress {0x0228}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_rst_interval defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_2.mutrig_frame_assembly_csr
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mutrig_frame_assembly_csr arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mutrig_frame_assembly_csr baseAddress {0x0210}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_2.mutrig_frame_assembly_csr defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_3.avmm_errcnt
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.avmm_errcnt arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.avmm_errcnt baseAddress {0x023c}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.avmm_errcnt defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_counter_value
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_counter_value arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_counter_value baseAddress {0x0180}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_counter_value defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_rst_interval
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_rst_interval arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_rst_interval baseAddress {0x022c}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_rst_interval defaultConnection {0}

add_connection master_datapath.master mutrig_datapath_subsystem_3.mutrig_frame_assembly_csr
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mutrig_frame_assembly_csr arbitrationPriority {1}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mutrig_frame_assembly_csr baseAddress {0x0218}
set_connection_parameter_value master_datapath.master/mutrig_datapath_subsystem_3.mutrig_frame_assembly_csr defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_0.avmm_errcnt
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.avmm_errcnt arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.avmm_errcnt baseAddress {0x0230}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.avmm_errcnt defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_counter_value
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_counter_value arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_counter_value baseAddress {0x0000}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_counter_value defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_rst_interval
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_rst_interval arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_rst_interval baseAddress {0x0220}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mch_count_subsystem_avmm_rst_interval defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_0.mutrig_frame_assembly_csr
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mutrig_frame_assembly_csr arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mutrig_frame_assembly_csr baseAddress {0x0200}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_0.mutrig_frame_assembly_csr defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_1.avmm_errcnt
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.avmm_errcnt arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.avmm_errcnt baseAddress {0x0234}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.avmm_errcnt defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_counter_value
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_counter_value arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_counter_value baseAddress {0x0080}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_counter_value defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_rst_interval
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_rst_interval arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_rst_interval baseAddress {0x0224}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mch_count_subsystem_avmm_rst_interval defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_1.mutrig_frame_assembly_csr
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mutrig_frame_assembly_csr arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mutrig_frame_assembly_csr baseAddress {0x0208}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_1.mutrig_frame_assembly_csr defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_2.avmm_errcnt
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.avmm_errcnt arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.avmm_errcnt baseAddress {0x0238}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.avmm_errcnt defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_counter_value
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_counter_value arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_counter_value baseAddress {0x0100}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_counter_value defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_rst_interval
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_rst_interval arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_rst_interval baseAddress {0x0228}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mch_count_subsystem_avmm_rst_interval defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_2.mutrig_frame_assembly_csr
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mutrig_frame_assembly_csr arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mutrig_frame_assembly_csr baseAddress {0x0210}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_2.mutrig_frame_assembly_csr defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_3.avmm_errcnt
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.avmm_errcnt arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.avmm_errcnt baseAddress {0x023c}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.avmm_errcnt defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_counter_value
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_counter_value arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_counter_value baseAddress {0x0180}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_counter_value defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_rst_interval
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_rst_interval arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_rst_interval baseAddress {0x022c}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mch_count_subsystem_avmm_rst_interval defaultConnection {0}

add_connection mm_clock_crossing_bridge.m0 mutrig_datapath_subsystem_3.mutrig_frame_assembly_csr
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mutrig_frame_assembly_csr arbitrationPriority {1}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mutrig_frame_assembly_csr baseAddress {0x0218}
set_connection_parameter_value mm_clock_crossing_bridge.m0/mutrig_datapath_subsystem_3.mutrig_frame_assembly_csr defaultConnection {0}

add_connection monitor_clock_125.clk master_datapath.clk

add_connection monitor_clock_125.clk mutrig_datapath_subsystem_0.debug_clock_in_clk

add_connection monitor_clock_125.clk mutrig_datapath_subsystem_1.debug_clock_in_clk

add_connection monitor_clock_125.clk mutrig_datapath_subsystem_2.debug_clock_in_clk

add_connection monitor_clock_125.clk mutrig_datapath_subsystem_3.debug_clock_in_clk

add_connection monitor_clock_125.clk receiver_subsystem.system_clock_125_in

add_connection monitor_clock_125.clk_reset master_datapath.clk_reset

add_connection monitor_clock_125.clk_reset receiver_subsystem.system_reset_in_reset

add_connection mutrig_datapath_subsystem_0.hit_type0_out mts_preprocessor_nano_0.link_a_hit_type0_avst

add_connection mutrig_datapath_subsystem_0.mutrig_frame_assembly_headerinfo mts_preprocessor_nano_0.headerinfo_avst

add_connection receiver_subsystem.mutrig0_8b1k_data mutrig_datapath_subsystem_0.avst_in

add_connection receiver_subsystem.mutrig1_8b1k_data mutrig_datapath_subsystem_1.avst_in

add_connection receiver_subsystem.mutrig2_8b1k_data mutrig_datapath_subsystem_2.avst_in

add_connection receiver_subsystem.mutrig3_8b1k_data mutrig_datapath_subsystem_3.avst_in

add_connection receiver_subsystem.rx_clock_125_out counter_sclr_bridge.clk

add_connection receiver_subsystem.rx_clock_125_out dbg_conduit2rst.dummy_clock

add_connection receiver_subsystem.rx_clock_125_out issp_dprst.source_clk

add_connection receiver_subsystem.rx_clock_125_out mm_clock_crossing_bridge.m0_clk

add_connection receiver_subsystem.rx_clock_125_out mts_preprocessor_nano_0.clock_interface

add_connection receiver_subsystem.rx_clock_125_out mutrig_datapath_subsystem_0.clk

add_connection receiver_subsystem.rx_clock_125_out mutrig_datapath_subsystem_1.clk

add_connection receiver_subsystem.rx_clock_125_out mutrig_datapath_subsystem_2.clk

add_connection receiver_subsystem.rx_clock_125_out mutrig_datapath_subsystem_3.clk

add_connection receiver_subsystem.rx_clock_125_out receiver_clock_125.in_clk

add_connection reset_bridge_export.out_reset counter_sclr_bridge.in_reset

# interconnect requirements
set_interconnect_requirement {$system} {qsys_mm.clockCrossingAdapter} {HANDSHAKE}
set_interconnect_requirement {$system} {qsys_mm.enableEccProtection} {FALSE}
set_interconnect_requirement {$system} {qsys_mm.insertDefaultSlave} {FALSE}
set_interconnect_requirement {$system} {qsys_mm.maxAdditionalLatency} {1}

save_system {scifi_datapath_system.qsys}
