+define+UVM_NO_DPI
+define+TB_INT_SIM
+incdir+uvm/common
+incdir+uvm/common/runctl_phy_agent
+incdir+uvm/common/sc_phy_agent
+incdir+uvm/common/rdma_rqe_ingress_monitor
+incdir+uvm/common/rdma_cqe_egress_monitor
+incdir+uvm/common/opq_lane_fill_monitor
+incdir+uvm/common/pcie_dma_egress_monitor
+incdir+uvm/common/host_memory_model
+incdir+uvm/swb_rdma_pretest
+incdir+uvm/swb_rdma_pretest/sequences
+incdir+uvm/swb_rdma_pretest/tests
uvm/common/runctl_phy_if.sv
uvm/common/sc_avmm_if.sv
uvm/common/run_window_db.sv
uvm/swb_rdma_pretest/rdma_rqe_ingress_if.sv
uvm/swb_rdma_pretest/rdma_cqe_egress_if.sv
uvm/swb_rdma_pretest/opq_lane_if.sv
uvm/swb_rdma_pretest/pcie_dma_egress_if.sv
uvm/common/swb_stage_record.sv
uvm/common/host_memory_model/host_memory_pkg.sv
uvm/common/host_memory_model/host_axi_responder.sv
uvm/common/host_memory_model/host_memory_model.sv
uvm/common/host_memory_model/host_polling_core.sv
uvm/common/runctl_phy_agent/runctl_phy_agent.sv
uvm/common/sc_phy_agent/sc_phy_agent.sv
uvm/common/rdma_rqe_ingress_monitor/rdma_rqe_ingress_monitor.sv
uvm/common/rdma_cqe_egress_monitor/rdma_cqe_egress_monitor.sv
uvm/common/opq_lane_fill_monitor/opq_lane_fill_monitor.sv
uvm/common/pcie_dma_egress_monitor/pcie_dma_egress_monitor.sv
uvm/swb_rdma_pretest/tb_int_swb_case_model.sv
uvm/swb_rdma_pretest/tb_int_swb_scoreboard.sv
uvm/swb_rdma_pretest/tb_int_dual_env.sv
uvm/swb_rdma_pretest/sequences/swb_case_sequences.sv
uvm/swb_rdma_pretest/sequences/B001.sv
uvm/swb_rdma_pretest/sequences/B002.sv
uvm/swb_rdma_pretest/sequences/B003.sv
uvm/swb_rdma_pretest/sequences/B004.sv
uvm/swb_rdma_pretest/sequences/B005.sv
uvm/swb_rdma_pretest/sequences/B006.sv
uvm/swb_rdma_pretest/sequences/B007.sv
uvm/swb_rdma_pretest/sequences/B008.sv
uvm/swb_rdma_pretest/sequences/B033.sv
uvm/swb_rdma_pretest/sequences/B034.sv
uvm/swb_rdma_pretest/sequences/B040.sv
uvm/swb_rdma_pretest/sequences/B043.sv
uvm/swb_rdma_pretest/sequences/B065.sv
uvm/swb_rdma_pretest/sequences/B066.sv
uvm/swb_rdma_pretest/sequences/B067.sv
uvm/swb_rdma_pretest/sequences/B068.sv
uvm/swb_rdma_pretest/sequences/B069.sv
uvm/swb_rdma_pretest/sequences/E001.sv
uvm/swb_rdma_pretest/sequences/E002.sv
uvm/swb_rdma_pretest/sequences/E003.sv
uvm/swb_rdma_pretest/sequences/E033.sv
uvm/swb_rdma_pretest/sequences/E043.sv
uvm/swb_rdma_pretest/sequences/E065.sv
uvm/swb_rdma_pretest/sequences/E066.sv
uvm/swb_rdma_pretest/sequences/E067.sv
uvm/swb_rdma_pretest/sequences/E068.sv
uvm/swb_rdma_pretest/sequences/X001.sv
uvm/swb_rdma_pretest/sequences/X002.sv
uvm/swb_rdma_pretest/sequences/X003.sv
uvm/swb_rdma_pretest/sequences/X004.sv
uvm/swb_rdma_pretest/sequences/X005.sv
uvm/swb_rdma_pretest/sequences/X033.sv
uvm/swb_rdma_pretest/sequences/X065.sv
uvm/swb_rdma_pretest/sequences/X069.sv
uvm/swb_rdma_pretest/sequences/P001.sv
uvm/swb_rdma_pretest/sequences/P002.sv
uvm/swb_rdma_pretest/sequences/P003.sv
uvm/swb_rdma_pretest/sequences/P065.sv
uvm/swb_rdma_pretest/sequences/P066.sv
uvm/swb_rdma_pretest/sequences/P068.sv
uvm/swb_rdma_pretest/sequences/run_sequence_directed.sv
uvm/swb_rdma_pretest/tb_int_base_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b001_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b002_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b003_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b004_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b005_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b006_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b007_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b008_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b033_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b034_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b040_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b043_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b065_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b066_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b067_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b068_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b069_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e001_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e002_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e003_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e033_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e043_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e065_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e066_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e067_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e068_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x001_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x002_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x003_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x004_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x005_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x033_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x065_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x069_test.sv
uvm/swb_rdma_pretest/tests/tb_int_p001_test.sv
uvm/swb_rdma_pretest/tests/tb_int_p002_test.sv
uvm/swb_rdma_pretest/tests/tb_int_p003_test.sv
uvm/swb_rdma_pretest/tests/tb_int_p065_test.sv
uvm/swb_rdma_pretest/tests/tb_int_p066_test.sv
uvm/swb_rdma_pretest/tests/tb_int_p068_test.sv
uvm/swb_rdma_pretest/tests/tb_int_run_sequence_directed_test.sv
uvm/swb_rdma_pretest/tests/tb_int_selected_tests_pkg.sv
uvm/swb_rdma_pretest/tb_int_smoke_test.sv
uvm/swb_rdma_pretest/tb_int_top.sv
