+define+UVM_NO_DPI
+define+TB_INT_SIM
+incdir+uvm/common
+incdir+uvm/common/runctl_phy_agent
+incdir+uvm/common/sc_phy_agent
+incdir+uvm/common/rdma_sqe_ingress_monitor
+incdir+uvm/common/rdma_cqe_egress_monitor
+incdir+uvm/common/opq_lane_fill_monitor
+incdir+uvm/common/pcie_dma_egress_monitor
+incdir+uvm/swb_rdma_pretest
+incdir+uvm/swb_rdma_pretest/sequences
+incdir+uvm/swb_rdma_pretest/tests
uvm/common/runctl_phy_if.sv
uvm/common/sc_avmm_if.sv
uvm/common/run_window_db.sv
uvm/swb_rdma_pretest/rdma_sqe_ingress_if.sv
uvm/swb_rdma_pretest/rdma_cqe_egress_if.sv
uvm/swb_rdma_pretest/opq_lane_if.sv
uvm/swb_rdma_pretest/pcie_dma_egress_if.sv
uvm/common/swb_stage_record.sv
uvm/common/runctl_phy_agent/runctl_phy_agent.sv
uvm/common/sc_phy_agent/sc_phy_agent.sv
uvm/common/rdma_sqe_ingress_monitor/rdma_sqe_ingress_monitor.sv
uvm/common/rdma_cqe_egress_monitor/rdma_cqe_egress_monitor.sv
uvm/common/opq_lane_fill_monitor/opq_lane_fill_monitor.sv
uvm/common/pcie_dma_egress_monitor/pcie_dma_egress_monitor.sv
uvm/swb_rdma_pretest/tb_int_swb_case_model.sv
uvm/swb_rdma_pretest/tb_int_swb_scoreboard.sv
uvm/swb_rdma_pretest/tb_int_dual_env.sv
uvm/swb_rdma_pretest/sequences/swb_case_sequences.sv
uvm/swb_rdma_pretest/sequences/B001.sv
uvm/swb_rdma_pretest/sequences/B006.sv
uvm/swb_rdma_pretest/sequences/B008.sv
uvm/swb_rdma_pretest/sequences/B033.sv
uvm/swb_rdma_pretest/sequences/B034.sv
uvm/swb_rdma_pretest/sequences/B040.sv
uvm/swb_rdma_pretest/sequences/B043.sv
uvm/swb_rdma_pretest/sequences/B065.sv
uvm/swb_rdma_pretest/sequences/B066.sv
uvm/swb_rdma_pretest/sequences/B067.sv
uvm/swb_rdma_pretest/sequences/B068.sv
uvm/swb_rdma_pretest/sequences/B069.sv
uvm/swb_rdma_pretest/sequences/E001.sv
uvm/swb_rdma_pretest/sequences/E033.sv
uvm/swb_rdma_pretest/sequences/E043.sv
uvm/swb_rdma_pretest/sequences/E065.sv
uvm/swb_rdma_pretest/sequences/X001.sv
uvm/swb_rdma_pretest/sequences/X033.sv
uvm/swb_rdma_pretest/sequences/X065.sv
uvm/swb_rdma_pretest/sequences/X069.sv
uvm/swb_rdma_pretest/sequences/P065.sv
uvm/swb_rdma_pretest/sequences/P068.sv
uvm/swb_rdma_pretest/tb_int_base_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b001_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b006_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b008_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b033_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b034_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b040_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b043_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b065_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b066_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b067_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b068_test.sv
uvm/swb_rdma_pretest/tests/tb_int_b069_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e001_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e033_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e043_test.sv
uvm/swb_rdma_pretest/tests/tb_int_e065_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x001_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x033_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x065_test.sv
uvm/swb_rdma_pretest/tests/tb_int_x069_test.sv
uvm/swb_rdma_pretest/tests/tb_int_p065_test.sv
uvm/swb_rdma_pretest/tests/tb_int_p068_test.sv
uvm/swb_rdma_pretest/tests/tb_int_selected_tests_pkg.sv
uvm/swb_rdma_pretest/tb_int_smoke_test.sv
uvm/swb_rdma_pretest/tb_int_top.sv
