+define+UVM_NO_DPI
+define+TB_INT_SIM
+incdir+uvm/common
+incdir+uvm/common/mutrig_phy_agent
+incdir+uvm/common/runctl_phy_agent
+incdir+uvm/common/sc_phy_agent
+incdir+uvm/common/l2_fifo_commit_monitor
+incdir+uvm/common/lvds_decoded_monitor
+incdir+uvm/common/rbcam_egress_monitor
+incdir+uvm/common/feb_egress_monitor
+incdir+uvm/common/mu3e_frame_format
+incdir+uvm/common/feb_frame_monitor
+incdir+uvm/common/histogram_csr_monitor
+incdir+uvm/common/debug_l2_sidecar_monitor
+incdir+uvm/common/debug_pre_rbcam_sidecar_monitor
+incdir+uvm/common/debug_post_rbcam_sidecar_monitor
+incdir+uvm/common/debug_feb_egress_sidecar_monitor
+incdir+uvm/common/debug_fill_monitor
+incdir+uvm/v3_pretest-260511
+incdir+uvm/v3_pretest-260511/sequences
+incdir+uvm/v3_pretest-260511/tests
uvm/common/hit_key_pkg.sv
uvm/common/run_window_db.sv
uvm/common/hit_record.sv
uvm/common/latency_reporter.sv
uvm/common/hit_tap_if.sv
uvm/common/tb_int_counter_if.sv
uvm/common/lvds_phy_if.sv
uvm/common/runctl_phy_if.sv
uvm/common/sc_avmm_if.sv
uvm/common/mu3e_frame_if.sv
uvm/v3_pretest-260511/mutrig_l2_commit_if.sv
uvm/v3_pretest-260511/mutrig_frame_deassembly_decoded_if.sv
uvm/common/debug_fill_monitor/debug_fill_if.sv
../../../../run-control_mgmt/rtl/runctl_mgmt_host.sv
uvm/common/mutrig_phy_agent/mutrig_phy_agent.sv
uvm/common/runctl_phy_agent/runctl_phy_agent.sv
uvm/common/sc_phy_agent/sc_phy_agent.sv
uvm/common/l2_fifo_commit_monitor/l2_fifo_commit_monitor.sv
uvm/common/lvds_decoded_monitor/lvds_decoded_monitor.sv
uvm/common/rbcam_egress_monitor/rbcam_egress_monitor.sv
uvm/common/feb_egress_monitor/feb_egress_monitor.sv
uvm/common/mu3e_frame_format/mu3e_frame_format_pkg.sv
uvm/common/feb_frame_monitor/feb_frame_monitor.sv
uvm/common/histogram_csr_monitor/histogram_csr_monitor.sv
uvm/common/debug_l2_sidecar_monitor/debug_l2_sidecar_monitor.sv
uvm/common/debug_pre_rbcam_sidecar_monitor/debug_pre_rbcam_sidecar_monitor.sv
uvm/common/debug_post_rbcam_sidecar_monitor/debug_post_rbcam_sidecar_monitor.sv
uvm/common/debug_feb_egress_sidecar_monitor/debug_feb_egress_sidecar_monitor.sv
uvm/common/debug_fill_monitor/debug_fill_monitor.sv
uvm/common/per_bucket_ledger_scoreboard.sv
uvm/v3_pretest-260511/tb_int_v3_scoreboard.sv
uvm/v3_pretest-260511/tb_int_dual_env.sv
uvm/v3_pretest-260511/sequences/tb_int_basic_sequences.sv
uvm/v3_pretest-260511/sequences/run_emulator_directed.sv
uvm/v3_pretest-260511/tb_int_base_test.sv
uvm/v3_pretest-260511/tests/tb_int_b065_test.sv
uvm/v3_pretest-260511/tests/tb_int_b066_test.sv
uvm/v3_pretest-260511/tests/tb_int_b067_test.sv
uvm/v3_pretest-260511/tests/tb_int_b068_test.sv
uvm/v3_pretest-260511/tests/tb_int_b069_test.sv
uvm/v3_pretest-260511/tests/tb_int_run_emulator_directed_test.sv
uvm/v3_pretest-260511/tests/tb_int_run_emul_blocked_test.sv
uvm/v3_pretest-260511/tests/tb_int_run_emul_fixed_test.sv
uvm/v3_pretest-260511/tb_int_smoke_test.sv
uvm/v3_pretest-260511/tb_int_assertions.sv
uvm/v3_pretest-260511/tb_int_top.sv
