#

source "device.tcl"

add_instance emif_0 altera_emif

set_instance_parameter_value emif_0 {BOARD_DDR3_AC_TO_CK_SKEW_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_DDR3_BRD_SKEW_WITHIN_DQS_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_DDR3_DQS_TO_CK_SKEW_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_DDR3_IS_SKEW_WITHIN_AC_DESKEWED} {1}
set_instance_parameter_value emif_0 {BOARD_DDR3_IS_SKEW_WITHIN_DQS_DESKEWED} {0}
set_instance_parameter_value emif_0 {BOARD_DDR3_MAX_CK_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_DDR3_MAX_DQS_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_DDR3_PKG_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_DDR3_PKG_BRD_SKEW_WITHIN_DQS_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_DDR3_SKEW_BETWEEN_DIMMS_NS} {0.05}
set_instance_parameter_value emif_0 {BOARD_DDR3_SKEW_BETWEEN_DQS_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_AC_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_AC_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_CK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_RCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_RCLK_SLEW_RATE} {5.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_RDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_RDATA_SLEW_RATE} {2.5}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_WCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_WCLK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_WDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USER_WDATA_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_DDR3_USE_DEFAULT_ISI_VALUES} {1}
set_instance_parameter_value emif_0 {BOARD_DDR3_USE_DEFAULT_SLEW_RATES} {1}
set_instance_parameter_value emif_0 {BOARD_DDR4_AC_TO_CK_SKEW_NS} {9.85294e-05}
set_instance_parameter_value emif_0 {BOARD_DDR4_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_DDR4_BRD_SKEW_WITHIN_DQS_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_DDR4_DQS_TO_CK_SKEW_NS} {-0.633751172}
set_instance_parameter_value emif_0 {BOARD_DDR4_IS_SKEW_WITHIN_AC_DESKEWED} {1}
set_instance_parameter_value emif_0 {BOARD_DDR4_IS_SKEW_WITHIN_DQS_DESKEWED} {1}
set_instance_parameter_value emif_0 {BOARD_DDR4_MAX_CK_DELAY_NS} {0.63384586}
set_instance_parameter_value emif_0 {BOARD_DDR4_MAX_DQS_DELAY_NS} {0.604109232}
set_instance_parameter_value emif_0 {BOARD_DDR4_PKG_BRD_SKEW_WITHIN_AC_NS} {0.002408548}
set_instance_parameter_value emif_0 {BOARD_DDR4_PKG_BRD_SKEW_WITHIN_DQS_NS} {0.00090747}
set_instance_parameter_value emif_0 {BOARD_DDR4_SKEW_BETWEEN_DIMMS_NS} {0.05}
set_instance_parameter_value emif_0 {BOARD_DDR4_SKEW_BETWEEN_DQS_NS} {0.148791384}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_AC_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_AC_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_CK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_RCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_RCLK_SLEW_RATE} {8.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_RDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_RDATA_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_WCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_WCLK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_WDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USER_WDATA_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_DDR4_USE_DEFAULT_ISI_VALUES} {1}
set_instance_parameter_value emif_0 {BOARD_DDR4_USE_DEFAULT_SLEW_RATES} {1}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_AC_TO_CK_SKEW_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_BRD_SKEW_WITHIN_DQS_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_DQS_TO_CK_SKEW_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_IS_SKEW_WITHIN_AC_DESKEWED} {1}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_IS_SKEW_WITHIN_DQS_DESKEWED} {0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_MAX_CK_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_MAX_DQS_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_PKG_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_PKG_BRD_SKEW_WITHIN_DQS_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_SKEW_BETWEEN_DIMMS_NS} {0.05}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_SKEW_BETWEEN_DQS_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_AC_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_AC_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_CK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_RCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_RCLK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_RDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_RDATA_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_WCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_WCLK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_WDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USER_WDATA_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USE_DEFAULT_ISI_VALUES} {1}
set_instance_parameter_value emif_0 {BOARD_LPDDR3_USE_DEFAULT_SLEW_RATES} {1}
set_instance_parameter_value emif_0 {BOARD_QDR2_AC_TO_K_SKEW_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR2_BRD_SKEW_WITHIN_D_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR2_BRD_SKEW_WITHIN_Q_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR2_IS_SKEW_WITHIN_AC_DESKEWED} {1}
set_instance_parameter_value emif_0 {BOARD_QDR2_IS_SKEW_WITHIN_D_DESKEWED} {0}
set_instance_parameter_value emif_0 {BOARD_QDR2_IS_SKEW_WITHIN_Q_DESKEWED} {0}
set_instance_parameter_value emif_0 {BOARD_QDR2_MAX_K_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_QDR2_PKG_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR2_PKG_BRD_SKEW_WITHIN_D_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR2_PKG_BRD_SKEW_WITHIN_Q_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_AC_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_AC_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_K_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_RCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_RCLK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_RDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_RDATA_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_WCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_WDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USER_WDATA_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_QDR2_USE_DEFAULT_ISI_VALUES} {1}
set_instance_parameter_value emif_0 {BOARD_QDR2_USE_DEFAULT_SLEW_RATES} {1}
set_instance_parameter_value emif_0 {BOARD_QDR4_AC_TO_CK_SKEW_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR4_BRD_SKEW_WITHIN_QK_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR4_DK_TO_CK_SKEW_NS} {-0.02}
set_instance_parameter_value emif_0 {BOARD_QDR4_IS_SKEW_WITHIN_AC_DESKEWED} {1}
set_instance_parameter_value emif_0 {BOARD_QDR4_IS_SKEW_WITHIN_QK_DESKEWED} {1}
set_instance_parameter_value emif_0 {BOARD_QDR4_MAX_CK_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_QDR4_MAX_DK_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_QDR4_PKG_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR4_PKG_BRD_SKEW_WITHIN_QK_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR4_SKEW_BETWEEN_DIMMS_NS} {0.05}
set_instance_parameter_value emif_0 {BOARD_QDR4_SKEW_BETWEEN_DK_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_AC_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_AC_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_CK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_RCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_RCLK_SLEW_RATE} {5.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_RDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_RDATA_SLEW_RATE} {2.5}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_WCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_WCLK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_WDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USER_WDATA_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_QDR4_USE_DEFAULT_ISI_VALUES} {1}
set_instance_parameter_value emif_0 {BOARD_QDR4_USE_DEFAULT_SLEW_RATES} {1}
set_instance_parameter_value emif_0 {BOARD_RLD3_AC_TO_CK_SKEW_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_RLD3_BRD_SKEW_WITHIN_QK_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_RLD3_DK_TO_CK_SKEW_NS} {-0.02}
set_instance_parameter_value emif_0 {BOARD_RLD3_IS_SKEW_WITHIN_AC_DESKEWED} {1}
set_instance_parameter_value emif_0 {BOARD_RLD3_IS_SKEW_WITHIN_QK_DESKEWED} {0}
set_instance_parameter_value emif_0 {BOARD_RLD3_MAX_CK_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_RLD3_MAX_DK_DELAY_NS} {0.6}
set_instance_parameter_value emif_0 {BOARD_RLD3_PKG_BRD_SKEW_WITHIN_AC_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_RLD3_PKG_BRD_SKEW_WITHIN_QK_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_RLD3_SKEW_BETWEEN_DIMMS_NS} {0.05}
set_instance_parameter_value emif_0 {BOARD_RLD3_SKEW_BETWEEN_DK_NS} {0.02}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_AC_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_AC_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_CK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_RCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_RCLK_SLEW_RATE} {7.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_RDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_RDATA_SLEW_RATE} {3.5}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_WCLK_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_WCLK_SLEW_RATE} {4.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_WDATA_ISI_NS} {0.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USER_WDATA_SLEW_RATE} {2.0}
set_instance_parameter_value emif_0 {BOARD_RLD3_USE_DEFAULT_ISI_VALUES} {1}
set_instance_parameter_value emif_0 {BOARD_RLD3_USE_DEFAULT_SLEW_RATES} {1}
set_instance_parameter_value emif_0 {CTRL_DDR3_ADDR_ORDER_ENUM} {DDR3_CTRL_ADDR_ORDER_CS_R_B_C}
set_instance_parameter_value emif_0 {CTRL_DDR3_AUTO_POWER_DOWN_CYCS} {32}
set_instance_parameter_value emif_0 {CTRL_DDR3_AUTO_POWER_DOWN_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_AUTO_PRECHARGE_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_AVL_PROTOCOL_ENUM} {CTRL_AVL_PROTOCOL_MM}
set_instance_parameter_value emif_0 {CTRL_DDR3_ECC_AUTO_CORRECTION_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_ECC_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_MMR_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_RD_TO_RD_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_RD_TO_WR_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_RD_TO_WR_SAME_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_REORDER_EN} {1}
set_instance_parameter_value emif_0 {CTRL_DDR3_SELF_REFRESH_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_STARVE_LIMIT} {10}
set_instance_parameter_value emif_0 {CTRL_DDR3_USER_PRIORITY_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_USER_REFRESH_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_WR_TO_RD_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_WR_TO_RD_SAME_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR3_WR_TO_WR_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_ADDR_ORDER_ENUM} {DDR4_CTRL_ADDR_ORDER_CS_R_B_C_BG}
set_instance_parameter_value emif_0 {CTRL_DDR4_AUTO_POWER_DOWN_CYCS} {32}
set_instance_parameter_value emif_0 {CTRL_DDR4_AUTO_POWER_DOWN_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_AUTO_PRECHARGE_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_AVL_PROTOCOL_ENUM} {CTRL_AVL_PROTOCOL_MM}
set_instance_parameter_value emif_0 {CTRL_DDR4_ECC_AUTO_CORRECTION_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_ECC_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_MMR_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_RD_TO_RD_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_RD_TO_WR_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_RD_TO_WR_SAME_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_REORDER_EN} {1}
set_instance_parameter_value emif_0 {CTRL_DDR4_SELF_REFRESH_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_STARVE_LIMIT} {10}
set_instance_parameter_value emif_0 {CTRL_DDR4_USER_PRIORITY_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_USER_REFRESH_EN} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_WR_TO_RD_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_WR_TO_RD_SAME_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_DDR4_WR_TO_WR_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_ADDR_ORDER_ENUM} {LPDDR3_CTRL_ADDR_ORDER_CS_R_B_C}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_AUTO_POWER_DOWN_CYCS} {32}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_AUTO_POWER_DOWN_EN} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_AUTO_PRECHARGE_EN} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_AVL_PROTOCOL_ENUM} {CTRL_AVL_PROTOCOL_MM}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_MMR_EN} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_RD_TO_RD_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_RD_TO_WR_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_RD_TO_WR_SAME_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_REORDER_EN} {1}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_SELF_REFRESH_EN} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_STARVE_LIMIT} {10}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_USER_PRIORITY_EN} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_USER_REFRESH_EN} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_WR_TO_RD_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_WR_TO_RD_SAME_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_LPDDR3_WR_TO_WR_DIFF_CHIP_DELTA_CYCS} {0}
set_instance_parameter_value emif_0 {CTRL_QDR2_AVL_ENABLE_POWER_OF_TWO_BUS} {0}
set_instance_parameter_value emif_0 {CTRL_QDR2_AVL_MAX_BURST_COUNT} {4}
set_instance_parameter_value emif_0 {CTRL_QDR2_AVL_PROTOCOL_ENUM} {CTRL_AVL_PROTOCOL_MM}
set_instance_parameter_value emif_0 {CTRL_QDR4_ADD_RAW_TURNAROUND_DELAY_CYC} {0}
set_instance_parameter_value emif_0 {CTRL_QDR4_ADD_WAR_TURNAROUND_DELAY_CYC} {0}
set_instance_parameter_value emif_0 {CTRL_QDR4_AVL_ENABLE_POWER_OF_TWO_BUS} {0}
set_instance_parameter_value emif_0 {CTRL_QDR4_AVL_MAX_BURST_COUNT} {4}
set_instance_parameter_value emif_0 {CTRL_QDR4_AVL_PROTOCOL_ENUM} {CTRL_AVL_PROTOCOL_MM}
set_instance_parameter_value emif_0 {CTRL_RLD2_AVL_PROTOCOL_ENUM} {CTRL_AVL_PROTOCOL_MM}
set_instance_parameter_value emif_0 {CTRL_RLD3_ADDR_ORDER_ENUM} {RLD3_CTRL_ADDR_ORDER_CS_R_B_C}
set_instance_parameter_value emif_0 {CTRL_RLD3_AVL_PROTOCOL_ENUM} {CTRL_AVL_PROTOCOL_MM}
set_instance_parameter_value emif_0 {DIAG_BOARD_DELAY_CONFIG_STR} {}
set_instance_parameter_value emif_0 {DIAG_DDR3_ABSTRACT_PHY} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_BYPASS_DEFAULT_PATTERN} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_BYPASS_REPEAT_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_DDR3_BYPASS_STRESS_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_DDR3_BYPASS_USER_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_DDR3_CAL_ADDR0} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_CAL_ADDR1} {8}
set_instance_parameter_value emif_0 {DIAG_DDR3_CAL_ENABLE_NON_DES} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_CAL_FULL_CAL_ON_RESET} {1}
set_instance_parameter_value emif_0 {DIAG_DDR3_CA_LEVEL_EN} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_EFFICIENCY_MONITOR} {EFFMON_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_DDR3_EXPORT_SEQ_AVALON_MASTER} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_EXPORT_SEQ_AVALON_SLAVE} {CAL_DEBUG_EXPORT_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_DDR3_EX_DESIGN_ISSP_EN} {1}
set_instance_parameter_value emif_0 {DIAG_DDR3_EX_DESIGN_NUM_OF_SLAVES} {1}
set_instance_parameter_value emif_0 {DIAG_DDR3_EX_DESIGN_SEPARATE_RZQS} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_INTERFACE_ID} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_SEPARATE_READ_WRITE_ITFS} {0}
set_instance_parameter_value emif_0 {DIAG_DDR3_SIM_CAL_MODE_ENUM} {SIM_CAL_MODE_SKIP}
set_instance_parameter_value emif_0 {DIAG_DDR3_TG_BE_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_DDR3_TG_DATA_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_DDR3_USE_TG_AVL_2} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_ABSTRACT_PHY} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_BYPASS_DEFAULT_PATTERN} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_BYPASS_REPEAT_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_DDR4_BYPASS_STRESS_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_DDR4_BYPASS_USER_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_DDR4_CAL_ADDR0} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_CAL_ADDR1} {8}
set_instance_parameter_value emif_0 {DIAG_DDR4_CAL_ENABLE_NON_DES} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_CAL_FULL_CAL_ON_RESET} {1}
set_instance_parameter_value emif_0 {DIAG_DDR4_EFFICIENCY_MONITOR} {EFFMON_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_DDR4_EXPORT_SEQ_AVALON_MASTER} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_EXPORT_SEQ_AVALON_SLAVE} {CAL_DEBUG_EXPORT_MODE_JTAG}
set_instance_parameter_value emif_0 {DIAG_DDR4_EX_DESIGN_ISSP_EN} {1}
set_instance_parameter_value emif_0 {DIAG_DDR4_EX_DESIGN_NUM_OF_SLAVES} {1}
set_instance_parameter_value emif_0 {DIAG_DDR4_EX_DESIGN_SEPARATE_RZQS} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_INTERFACE_ID} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_SEPARATE_READ_WRITE_ITFS} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_SIM_CAL_MODE_ENUM} {SIM_CAL_MODE_SKIP}
set_instance_parameter_value emif_0 {DIAG_DDR4_SKIP_CA_DESKEW} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_SKIP_CA_LEVEL} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_SKIP_VREF_CAL} {0}
set_instance_parameter_value emif_0 {DIAG_DDR4_TG_BE_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_DDR4_TG_DATA_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_DDR4_USE_TG_AVL_2} {0}
set_instance_parameter_value emif_0 {DIAG_ECLIPSE_DEBUG} {0}
set_instance_parameter_value emif_0 {DIAG_ENABLE_HPS_EMIF_DEBUG} {0}
set_instance_parameter_value emif_0 {DIAG_ENABLE_JTAG_UART} {0}
set_instance_parameter_value emif_0 {DIAG_ENABLE_JTAG_UART_HEX} {0}
set_instance_parameter_value emif_0 {DIAG_EXPORT_VJI} {0}
set_instance_parameter_value emif_0 {DIAG_EXPOSE_DFT_SIGNALS} {0}
set_instance_parameter_value emif_0 {DIAG_EXTRA_CONFIGS} {}
set_instance_parameter_value emif_0 {DIAG_EXT_DOCS} {0}
set_instance_parameter_value emif_0 {DIAG_EX_DESIGN_ADD_TEST_EMIFS} {}
set_instance_parameter_value emif_0 {DIAG_EX_DESIGN_SEPARATE_RESETS} {0}
set_instance_parameter_value emif_0 {DIAG_FAST_SIM_OVERRIDE} {FAST_SIM_OVERRIDE_DEFAULT}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_ABSTRACT_PHY} {0}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_BYPASS_DEFAULT_PATTERN} {0}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_BYPASS_REPEAT_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_BYPASS_STRESS_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_BYPASS_USER_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_EFFICIENCY_MONITOR} {EFFMON_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_EXPORT_SEQ_AVALON_MASTER} {0}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_EXPORT_SEQ_AVALON_SLAVE} {CAL_DEBUG_EXPORT_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_EX_DESIGN_ISSP_EN} {1}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_EX_DESIGN_NUM_OF_SLAVES} {1}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_EX_DESIGN_SEPARATE_RZQS} {0}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_INTERFACE_ID} {0}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_SEPARATE_READ_WRITE_ITFS} {0}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_SIM_CAL_MODE_ENUM} {SIM_CAL_MODE_SKIP}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_SKIP_CA_DESKEW} {0}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_SKIP_CA_LEVEL} {0}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_TG_BE_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_TG_DATA_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_LPDDR3_USE_TG_AVL_2} {0}
set_instance_parameter_value emif_0 {DIAG_QDR2_ABSTRACT_PHY} {0}
set_instance_parameter_value emif_0 {DIAG_QDR2_BYPASS_DEFAULT_PATTERN} {0}
set_instance_parameter_value emif_0 {DIAG_QDR2_BYPASS_REPEAT_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_QDR2_BYPASS_STRESS_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_QDR2_BYPASS_USER_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_QDR2_EFFICIENCY_MONITOR} {EFFMON_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_QDR2_EXPORT_SEQ_AVALON_MASTER} {0}
set_instance_parameter_value emif_0 {DIAG_QDR2_EXPORT_SEQ_AVALON_SLAVE} {CAL_DEBUG_EXPORT_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_QDR2_EX_DESIGN_ISSP_EN} {1}
set_instance_parameter_value emif_0 {DIAG_QDR2_EX_DESIGN_NUM_OF_SLAVES} {1}
set_instance_parameter_value emif_0 {DIAG_QDR2_EX_DESIGN_SEPARATE_RZQS} {0}
set_instance_parameter_value emif_0 {DIAG_QDR2_INTERFACE_ID} {0}
set_instance_parameter_value emif_0 {DIAG_QDR2_SEPARATE_READ_WRITE_ITFS} {0}
set_instance_parameter_value emif_0 {DIAG_QDR2_SIM_CAL_MODE_ENUM} {SIM_CAL_MODE_SKIP}
set_instance_parameter_value emif_0 {DIAG_QDR2_TG_BE_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_QDR2_TG_DATA_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_QDR2_USE_TG_AVL_2} {0}
set_instance_parameter_value emif_0 {DIAG_QDR4_ABSTRACT_PHY} {0}
set_instance_parameter_value emif_0 {DIAG_QDR4_BYPASS_DEFAULT_PATTERN} {0}
set_instance_parameter_value emif_0 {DIAG_QDR4_BYPASS_REPEAT_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_QDR4_BYPASS_STRESS_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_QDR4_BYPASS_USER_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_QDR4_EFFICIENCY_MONITOR} {EFFMON_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_QDR4_EXPORT_SEQ_AVALON_MASTER} {0}
set_instance_parameter_value emif_0 {DIAG_QDR4_EXPORT_SEQ_AVALON_SLAVE} {CAL_DEBUG_EXPORT_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_QDR4_EX_DESIGN_ISSP_EN} {1}
set_instance_parameter_value emif_0 {DIAG_QDR4_EX_DESIGN_NUM_OF_SLAVES} {1}
set_instance_parameter_value emif_0 {DIAG_QDR4_EX_DESIGN_SEPARATE_RZQS} {0}
set_instance_parameter_value emif_0 {DIAG_QDR4_INTERFACE_ID} {0}
set_instance_parameter_value emif_0 {DIAG_QDR4_SEPARATE_READ_WRITE_ITFS} {0}
set_instance_parameter_value emif_0 {DIAG_QDR4_SIM_CAL_MODE_ENUM} {SIM_CAL_MODE_SKIP}
set_instance_parameter_value emif_0 {DIAG_QDR4_SKIP_VREF_CAL} {0}
set_instance_parameter_value emif_0 {DIAG_QDR4_TG_BE_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_QDR4_TG_DATA_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_QDR4_USE_TG_AVL_2} {0}
set_instance_parameter_value emif_0 {DIAG_RLD2_ABSTRACT_PHY} {0}
set_instance_parameter_value emif_0 {DIAG_RLD2_BYPASS_DEFAULT_PATTERN} {0}
set_instance_parameter_value emif_0 {DIAG_RLD2_BYPASS_REPEAT_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_RLD2_BYPASS_STRESS_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_RLD2_BYPASS_USER_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_RLD2_EFFICIENCY_MONITOR} {EFFMON_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_RLD2_EXPORT_SEQ_AVALON_MASTER} {0}
set_instance_parameter_value emif_0 {DIAG_RLD2_EXPORT_SEQ_AVALON_SLAVE} {CAL_DEBUG_EXPORT_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_RLD2_EX_DESIGN_ISSP_EN} {1}
set_instance_parameter_value emif_0 {DIAG_RLD2_EX_DESIGN_NUM_OF_SLAVES} {1}
set_instance_parameter_value emif_0 {DIAG_RLD2_EX_DESIGN_SEPARATE_RZQS} {0}
set_instance_parameter_value emif_0 {DIAG_RLD2_INTERFACE_ID} {0}
set_instance_parameter_value emif_0 {DIAG_RLD2_SEPARATE_READ_WRITE_ITFS} {0}
set_instance_parameter_value emif_0 {DIAG_RLD2_SIM_CAL_MODE_ENUM} {SIM_CAL_MODE_SKIP}
set_instance_parameter_value emif_0 {DIAG_RLD2_TG_BE_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_RLD2_TG_DATA_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_RLD2_USE_TG_AVL_2} {0}
set_instance_parameter_value emif_0 {DIAG_RLD3_ABSTRACT_PHY} {0}
set_instance_parameter_value emif_0 {DIAG_RLD3_BYPASS_DEFAULT_PATTERN} {0}
set_instance_parameter_value emif_0 {DIAG_RLD3_BYPASS_REPEAT_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_RLD3_BYPASS_STRESS_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_RLD3_BYPASS_USER_STAGE} {1}
set_instance_parameter_value emif_0 {DIAG_RLD3_EFFICIENCY_MONITOR} {EFFMON_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_RLD3_EXPORT_SEQ_AVALON_MASTER} {0}
set_instance_parameter_value emif_0 {DIAG_RLD3_EXPORT_SEQ_AVALON_SLAVE} {CAL_DEBUG_EXPORT_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_RLD3_EX_DESIGN_ISSP_EN} {1}
set_instance_parameter_value emif_0 {DIAG_RLD3_EX_DESIGN_NUM_OF_SLAVES} {1}
set_instance_parameter_value emif_0 {DIAG_RLD3_EX_DESIGN_SEPARATE_RZQS} {0}
set_instance_parameter_value emif_0 {DIAG_RLD3_INTERFACE_ID} {0}
set_instance_parameter_value emif_0 {DIAG_RLD3_SEPARATE_READ_WRITE_ITFS} {0}
set_instance_parameter_value emif_0 {DIAG_RLD3_SIM_CAL_MODE_ENUM} {SIM_CAL_MODE_SKIP}
set_instance_parameter_value emif_0 {DIAG_RLD3_TG_BE_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_RLD3_TG_DATA_PATTERN_LENGTH} {8}
set_instance_parameter_value emif_0 {DIAG_RLD3_USE_TG_AVL_2} {0}
set_instance_parameter_value emif_0 {DIAG_RS232_UART_BAUDRATE} {57600}
set_instance_parameter_value emif_0 {DIAG_SIM_REGTEST_MODE} {0}
set_instance_parameter_value emif_0 {DIAG_SOFT_NIOS_CLOCK_FREQUENCY} {100}
set_instance_parameter_value emif_0 {DIAG_SOFT_NIOS_MODE} {SOFT_NIOS_MODE_DISABLED}
set_instance_parameter_value emif_0 {DIAG_SYNTH_FOR_SIM} {0}
set_instance_parameter_value emif_0 {DIAG_TG_AVL_2_EXPORT_CFG_INTERFACE} {0}
set_instance_parameter_value emif_0 {DIAG_TG_AVL_2_NUM_CFG_INTERFACES} {0}
set_instance_parameter_value emif_0 {DIAG_TIMING_REGTEST_MODE} {0}
set_instance_parameter_value emif_0 {DIAG_USE_BOARD_DELAY_MODEL} {0}
set_instance_parameter_value emif_0 {DIAG_USE_RS232_UART} {0}
set_instance_parameter_value emif_0 {DIAG_VERBOSE_IOAUX} {0}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR3_GEN_SIM} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR3_GEN_SYNTH} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR3_HDL_FORMAT} {HDL_FORMAT_VERILOG}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR3_PREV_PRESET} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR3_SEL_DESIGN} {AVAIL_EX_DESIGNS_GEN_DESIGN}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR3_TARGET_DEV_KIT} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR4_GEN_SIM} {0}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR4_GEN_SYNTH} {0}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR4_HDL_FORMAT} {HDL_FORMAT_VERILOG}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR4_PREV_PRESET} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR4_SEL_DESIGN} {AVAIL_EX_DESIGNS_GEN_DESIGN}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_DDR4_TARGET_DEV_KIT} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_LPDDR3_GEN_SIM} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_LPDDR3_GEN_SYNTH} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_LPDDR3_HDL_FORMAT} {HDL_FORMAT_VERILOG}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_LPDDR3_PREV_PRESET} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_LPDDR3_SEL_DESIGN} {AVAIL_EX_DESIGNS_GEN_DESIGN}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_LPDDR3_TARGET_DEV_KIT} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR2_GEN_SIM} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR2_GEN_SYNTH} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR2_HDL_FORMAT} {HDL_FORMAT_VERILOG}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR2_PREV_PRESET} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR2_SEL_DESIGN} {AVAIL_EX_DESIGNS_GEN_DESIGN}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR2_TARGET_DEV_KIT} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR4_GEN_SIM} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR4_GEN_SYNTH} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR4_HDL_FORMAT} {HDL_FORMAT_VERILOG}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR4_PREV_PRESET} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR4_SEL_DESIGN} {AVAIL_EX_DESIGNS_GEN_DESIGN}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_QDR4_TARGET_DEV_KIT} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD2_GEN_SIM} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD2_GEN_SYNTH} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD2_HDL_FORMAT} {HDL_FORMAT_VERILOG}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD2_PREV_PRESET} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD2_SEL_DESIGN} {AVAIL_EX_DESIGNS_GEN_DESIGN}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD2_TARGET_DEV_KIT} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD3_GEN_SIM} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD3_GEN_SYNTH} {1}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD3_HDL_FORMAT} {HDL_FORMAT_VERILOG}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD3_PREV_PRESET} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD3_SEL_DESIGN} {AVAIL_EX_DESIGNS_GEN_DESIGN}
set_instance_parameter_value emif_0 {EX_DESIGN_GUI_RLD3_TARGET_DEV_KIT} {TARGET_DEV_KIT_NONE}
set_instance_parameter_value emif_0 {INTERNAL_TESTING_MODE} {0}
set_instance_parameter_value emif_0 {IS_ED_SLAVE} {0}
set_instance_parameter_value emif_0 {MEM_DDR3_ALERT_N_DQS_GROUP} {0}
set_instance_parameter_value emif_0 {MEM_DDR3_ALERT_N_PLACEMENT_ENUM} {DDR3_ALERT_N_PLACEMENT_AC_LANES}
set_instance_parameter_value emif_0 {MEM_DDR3_ASR_ENUM} {DDR3_ASR_MANUAL}
set_instance_parameter_value emif_0 {MEM_DDR3_ATCL_ENUM} {DDR3_ATCL_DISABLED}
set_instance_parameter_value emif_0 {MEM_DDR3_BANK_ADDR_WIDTH} {3}
set_instance_parameter_value emif_0 {MEM_DDR3_BL_ENUM} {DDR3_BL_BL8}
set_instance_parameter_value emif_0 {MEM_DDR3_BT_ENUM} {DDR3_BT_SEQUENTIAL}
set_instance_parameter_value emif_0 {MEM_DDR3_CKE_PER_DIMM} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_CK_WIDTH} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_COL_ADDR_WIDTH} {10}
set_instance_parameter_value emif_0 {MEM_DDR3_DISCRETE_CS_WIDTH} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_DISCRETE_MIRROR_ADDRESSING_EN} {0}
set_instance_parameter_value emif_0 {MEM_DDR3_DLL_EN} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_DM_EN} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_DQ_PER_DQS} {8}
set_instance_parameter_value emif_0 {MEM_DDR3_DQ_WIDTH} {72}
set_instance_parameter_value emif_0 {MEM_DDR3_DRV_STR_ENUM} {DDR3_DRV_STR_RZQ_7}
set_instance_parameter_value emif_0 {MEM_DDR3_FORMAT_ENUM} {MEM_FORMAT_UDIMM}
set_instance_parameter_value emif_0 {MEM_DDR3_HIDE_ADV_MR_SETTINGS} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_LRDIMM_EXTENDED_CONFIG} {000000000000000000}
set_instance_parameter_value emif_0 {MEM_DDR3_MIRROR_ADDRESSING_EN} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_NUM_OF_DIMMS} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_PD_ENUM} {DDR3_PD_OFF}
set_instance_parameter_value emif_0 {MEM_DDR3_RANKS_PER_DIMM} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_RDIMM_CONFIG} {0000000000000000}
set_instance_parameter_value emif_0 {MEM_DDR3_ROW_ADDR_WIDTH} {15}
set_instance_parameter_value emif_0 {MEM_DDR3_RTT_NOM_ENUM} {DDR3_RTT_NOM_ODT_DISABLED}
set_instance_parameter_value emif_0 {MEM_DDR3_RTT_WR_ENUM} {DDR3_RTT_WR_RZQ_4}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT0_1X1} {off}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT0_2X2} {off off}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT0_4X2} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT0_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT1_2X2} {off off}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT1_4X2} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT1_4X4} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT2_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODT3_4X4} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODTN_1X1} {Rank\ 0}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODTN_2X2} {Rank\ 0 Rank\ 1}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODTN_4X2} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_DDR3_R_ODTN_4X4} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_DDR3_SPEEDBIN_ENUM} {DDR3_SPEEDBIN_2133}
set_instance_parameter_value emif_0 {MEM_DDR3_SRT_ENUM} {DDR3_SRT_NORMAL}
set_instance_parameter_value emif_0 {MEM_DDR3_TCL} {14}
set_instance_parameter_value emif_0 {MEM_DDR3_TDH_DC_MV} {100}
set_instance_parameter_value emif_0 {MEM_DDR3_TDH_PS} {55}
set_instance_parameter_value emif_0 {MEM_DDR3_TDQSCK_PS} {180}
set_instance_parameter_value emif_0 {MEM_DDR3_TDQSQ_PS} {75}
set_instance_parameter_value emif_0 {MEM_DDR3_TDQSS_CYC} {0.27}
set_instance_parameter_value emif_0 {MEM_DDR3_TDSH_CYC} {0.18}
set_instance_parameter_value emif_0 {MEM_DDR3_TDSS_CYC} {0.18}
set_instance_parameter_value emif_0 {MEM_DDR3_TDS_AC_MV} {135}
set_instance_parameter_value emif_0 {MEM_DDR3_TDS_PS} {53}
set_instance_parameter_value emif_0 {MEM_DDR3_TFAW_NS} {25.0}
set_instance_parameter_value emif_0 {MEM_DDR3_TIH_DC_MV} {100}
set_instance_parameter_value emif_0 {MEM_DDR3_TIH_PS} {95}
set_instance_parameter_value emif_0 {MEM_DDR3_TINIT_US} {500}
set_instance_parameter_value emif_0 {MEM_DDR3_TIS_AC_MV} {135}
set_instance_parameter_value emif_0 {MEM_DDR3_TIS_PS} {60}
set_instance_parameter_value emif_0 {MEM_DDR3_TMRD_CK_CYC} {4}
set_instance_parameter_value emif_0 {MEM_DDR3_TQH_CYC} {0.38}
set_instance_parameter_value emif_0 {MEM_DDR3_TQSH_CYC} {0.4}
set_instance_parameter_value emif_0 {MEM_DDR3_TRAS_NS} {33.0}
set_instance_parameter_value emif_0 {MEM_DDR3_TRCD_NS} {13.09}
set_instance_parameter_value emif_0 {MEM_DDR3_TREFI_US} {7.8}
set_instance_parameter_value emif_0 {MEM_DDR3_TRFC_NS} {160.0}
set_instance_parameter_value emif_0 {MEM_DDR3_TRP_NS} {13.09}
set_instance_parameter_value emif_0 {MEM_DDR3_TRRD_CYC} {6}
set_instance_parameter_value emif_0 {MEM_DDR3_TRTP_CYC} {8}
set_instance_parameter_value emif_0 {MEM_DDR3_TWLH_PS} {125.0}
set_instance_parameter_value emif_0 {MEM_DDR3_TWLS_PS} {125.0}
set_instance_parameter_value emif_0 {MEM_DDR3_TWR_NS} {15.0}
set_instance_parameter_value emif_0 {MEM_DDR3_TWTR_CYC} {8}
set_instance_parameter_value emif_0 {MEM_DDR3_USE_DEFAULT_ODT} {1}
set_instance_parameter_value emif_0 {MEM_DDR3_WTCL} {10}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT0_1X1} {on}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT0_2X2} {on off}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT0_4X2} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT0_4X4} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT1_2X2} {off on}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT1_4X2} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT1_4X4} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT2_4X4} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODT3_4X4} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODTN_1X1} {Rank\ 0}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODTN_2X2} {Rank\ 0 Rank\ 1}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODTN_4X2} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_DDR3_W_ODTN_4X4} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_DDR4_AC_PARITY_LATENCY} {DDR4_AC_PARITY_LATENCY_DISABLE}
set_instance_parameter_value emif_0 {MEM_DDR4_AC_PERSISTENT_ERROR} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_ALERT_N_AC_LANE} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_ALERT_N_AC_PIN} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_ALERT_N_DQS_GROUP} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_ALERT_N_PLACEMENT_ENUM} {DDR4_ALERT_N_PLACEMENT_AUTO}
set_instance_parameter_value emif_0 {MEM_DDR4_ALERT_PAR_EN} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_ASR_ENUM} {DDR4_ASR_MANUAL_NORMAL}
set_instance_parameter_value emif_0 {MEM_DDR4_ATCL_ENUM} {DDR4_ATCL_DISABLED}
set_instance_parameter_value emif_0 {MEM_DDR4_BANK_ADDR_WIDTH} {2}
set_instance_parameter_value emif_0 {MEM_DDR4_BANK_GROUP_WIDTH} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_BL_ENUM} {DDR4_BL_BL8}
set_instance_parameter_value emif_0 {MEM_DDR4_BT_ENUM} {DDR4_BT_SEQUENTIAL}
set_instance_parameter_value emif_0 {MEM_DDR4_CAL_MODE} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_CHIP_ID_WIDTH} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_CKE_PER_DIMM} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_CK_WIDTH} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_COL_ADDR_WIDTH} {10}
set_instance_parameter_value emif_0 {MEM_DDR4_DB_DQ_DRV_ENUM} {DDR4_DB_DRV_STR_RZQ_7}
set_instance_parameter_value emif_0 {MEM_DDR4_DB_RTT_NOM_ENUM} {DDR4_DB_RTT_NOM_ODT_DISABLED}
set_instance_parameter_value emif_0 {MEM_DDR4_DB_RTT_PARK_ENUM} {DDR4_DB_RTT_PARK_ODT_DISABLED}
set_instance_parameter_value emif_0 {MEM_DDR4_DB_RTT_WR_ENUM} {DDR4_DB_RTT_WR_RZQ_3}
set_instance_parameter_value emif_0 {MEM_DDR4_DEFAULT_VREFOUT} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_DISCRETE_CS_WIDTH} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_DISCRETE_MIRROR_ADDRESSING_EN} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_DLL_EN} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_DM_EN} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_DQ_PER_DQS} {8}
set_instance_parameter_value emif_0 {MEM_DDR4_DQ_WIDTH} {64}
set_instance_parameter_value emif_0 {MEM_DDR4_DRV_STR_ENUM} {DDR4_DRV_STR_RZQ_7}
set_instance_parameter_value emif_0 {MEM_DDR4_FINE_GRANULARITY_REFRESH} {DDR4_FINE_REFRESH_FIXED_1X}
set_instance_parameter_value emif_0 {MEM_DDR4_FORMAT_ENUM} {MEM_FORMAT_SODIMM}
set_instance_parameter_value emif_0 {MEM_DDR4_GEARDOWN} {DDR4_GEARDOWN_HR}
set_instance_parameter_value emif_0 {MEM_DDR4_HIDE_ADV_MR_SETTINGS} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_INTERNAL_VREFDQ_MONITOR} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_LRDIMM_ODT_LESS_BS} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_LRDIMM_ODT_LESS_BS_PARK_OHM} {240}
set_instance_parameter_value emif_0 {MEM_DDR4_LRDIMM_VREFDQ_VALUE} {}
set_instance_parameter_value emif_0 {MEM_DDR4_MAX_POWERDOWN} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_MIRROR_ADDRESSING_EN} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_MPR_READ_FORMAT} {DDR4_MPR_READ_FORMAT_SERIAL}
set_instance_parameter_value emif_0 {MEM_DDR4_NUM_OF_DIMMS} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_ODT_IN_POWERDOWN} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_PER_DRAM_ADDR} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_RANKS_PER_DIMM} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_RCD_CA_IBT_ENUM} {DDR4_RCD_CA_IBT_100}
set_instance_parameter_value emif_0 {MEM_DDR4_RCD_CKE_IBT_ENUM} {DDR4_RCD_CKE_IBT_100}
set_instance_parameter_value emif_0 {MEM_DDR4_RCD_CS_IBT_ENUM} {DDR4_RCD_CS_IBT_100}
set_instance_parameter_value emif_0 {MEM_DDR4_RCD_ODT_IBT_ENUM} {DDR4_RCD_ODT_IBT_100}
set_instance_parameter_value emif_0 {MEM_DDR4_READ_DBI} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_READ_PREAMBLE} {2}
set_instance_parameter_value emif_0 {MEM_DDR4_READ_PREAMBLE_TRAINING} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_ROW_ADDR_WIDTH} {16}
set_instance_parameter_value emif_0 {MEM_DDR4_RTT_NOM_ENUM} {DDR4_RTT_NOM_RZQ_5}
set_instance_parameter_value emif_0 {MEM_DDR4_RTT_PARK} {DDR4_RTT_PARK_ODT_DISABLED}
set_instance_parameter_value emif_0 {MEM_DDR4_RTT_WR_ENUM} {DDR4_RTT_WR_ODT_DISABLED}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT0_1X1} {off}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT0_2X2} {off off}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT0_4X2} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT0_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT1_2X2} {off off}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT1_4X2} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT1_4X4} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT2_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODT3_4X4} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODTN_1X1} {Rank\ 0}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODTN_2X2} {Rank\ 0 Rank\ 1}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODTN_4X2} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_DDR4_R_ODTN_4X4} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_DDR4_SELF_RFSH_ABORT} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_133_RCD_DB_VENDOR_LSB} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_134_RCD_DB_VENDOR_MSB} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_135_RCD_REV} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_137_RCD_CA_DRV} {101}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_138_RCD_CK_DRV} {5}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_139_DB_REV} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_140_DRAM_VREFDQ_R0} {29}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_141_DRAM_VREFDQ_R1} {29}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_142_DRAM_VREFDQ_R2} {29}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_143_DRAM_VREFDQ_R3} {29}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_144_DB_VREFDQ} {37}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_145_DB_MDQ_DRV} {21}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_148_DRAM_DRV} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_149_DRAM_RTT_WR_NOM} {20}
set_instance_parameter_value emif_0 {MEM_DDR4_SPD_152_DRAM_RTT_PARK} {39}
set_instance_parameter_value emif_0 {MEM_DDR4_SPEEDBIN_ENUM} {DDR4_SPEEDBIN_2400}
set_instance_parameter_value emif_0 {MEM_DDR4_TCCD_L_CYC} {6}
set_instance_parameter_value emif_0 {MEM_DDR4_TCCD_S_CYC} {4}
set_instance_parameter_value emif_0 {MEM_DDR4_TCL} {18}
set_instance_parameter_value emif_0 {MEM_DDR4_TDIVW_DJ_CYC} {0.1}
set_instance_parameter_value emif_0 {MEM_DDR4_TDIVW_TOTAL_UI} {0.2}
set_instance_parameter_value emif_0 {MEM_DDR4_TDQSCK_PS} {175}
set_instance_parameter_value emif_0 {MEM_DDR4_TDQSQ_PS} {66}
set_instance_parameter_value emif_0 {MEM_DDR4_TDQSQ_UI} {0.17}
set_instance_parameter_value emif_0 {MEM_DDR4_TDQSS_CYC} {0.27}
set_instance_parameter_value emif_0 {MEM_DDR4_TDSH_CYC} {0.18}
set_instance_parameter_value emif_0 {MEM_DDR4_TDSS_CYC} {0.18}
set_instance_parameter_value emif_0 {MEM_DDR4_TDVWP_UI} {0.72}
set_instance_parameter_value emif_0 {MEM_DDR4_TEMP_CONTROLLED_RFSH_ENA} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_TEMP_CONTROLLED_RFSH_RANGE} {DDR4_TEMP_CONTROLLED_RFSH_NORMAL}
set_instance_parameter_value emif_0 {MEM_DDR4_TEMP_SENSOR_READOUT} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_TFAW_NS} {30.0}
set_instance_parameter_value emif_0 {MEM_DDR4_TIH_DC_MV} {75}
set_instance_parameter_value emif_0 {MEM_DDR4_TIH_PS} {87}
set_instance_parameter_value emif_0 {MEM_DDR4_TINIT_US} {500}
set_instance_parameter_value emif_0 {MEM_DDR4_TIS_AC_MV} {100}
set_instance_parameter_value emif_0 {MEM_DDR4_TIS_PS} {62}
set_instance_parameter_value emif_0 {MEM_DDR4_TMRD_CK_CYC} {8}
set_instance_parameter_value emif_0 {MEM_DDR4_TQH_CYC} {0.38}
set_instance_parameter_value emif_0 {MEM_DDR4_TQH_UI} {0.74}
set_instance_parameter_value emif_0 {MEM_DDR4_TQSH_CYC} {0.4}
set_instance_parameter_value emif_0 {MEM_DDR4_TRAS_NS} {32.0}
set_instance_parameter_value emif_0 {MEM_DDR4_TRCD_NS} {13.32}
set_instance_parameter_value emif_0 {MEM_DDR4_TREFI_US} {7.8}
set_instance_parameter_value emif_0 {MEM_DDR4_TRFC_NS} {350.0}
set_instance_parameter_value emif_0 {MEM_DDR4_TRP_NS} {13.32}
set_instance_parameter_value emif_0 {MEM_DDR4_TRRD_L_CYC} {8}
set_instance_parameter_value emif_0 {MEM_DDR4_TRRD_S_CYC} {7}
set_instance_parameter_value emif_0 {MEM_DDR4_TWLH_PS} {108.0}
set_instance_parameter_value emif_0 {MEM_DDR4_TWLS_PS} {108.0}
set_instance_parameter_value emif_0 {MEM_DDR4_TWR_NS} {15.0}
set_instance_parameter_value emif_0 {MEM_DDR4_TWTR_L_CYC} {9}
set_instance_parameter_value emif_0 {MEM_DDR4_TWTR_S_CYC} {3}
set_instance_parameter_value emif_0 {MEM_DDR4_USER_VREFDQ_TRAINING_RANGE} {DDR4_VREFDQ_TRAINING_RANGE_1}
set_instance_parameter_value emif_0 {MEM_DDR4_USER_VREFDQ_TRAINING_VALUE} {56.0}
set_instance_parameter_value emif_0 {MEM_DDR4_USE_DEFAULT_ODT} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_VDIVW_TOTAL} {130}
set_instance_parameter_value emif_0 {MEM_DDR4_WRITE_CRC} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_WRITE_DBI} {0}
set_instance_parameter_value emif_0 {MEM_DDR4_WRITE_PREAMBLE} {1}
set_instance_parameter_value emif_0 {MEM_DDR4_WTCL} {16}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT0_1X1} {on}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT0_2X2} {on off}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT0_4X2} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT0_4X4} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT1_2X2} {off on}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT1_4X2} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT1_4X4} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT2_4X4} {off off on on}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODT3_4X4} {on on off off}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODTN_1X1} {Rank\ 0}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODTN_2X2} {Rank\ 0 Rank\ 1}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODTN_4X2} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_DDR4_W_ODTN_4X4} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_LPDDR3_BANK_ADDR_WIDTH} {3}
set_instance_parameter_value emif_0 {MEM_LPDDR3_BL} {LPDDR3_BL_BL8}
set_instance_parameter_value emif_0 {MEM_LPDDR3_CK_WIDTH} {1}
set_instance_parameter_value emif_0 {MEM_LPDDR3_COL_ADDR_WIDTH} {10}
set_instance_parameter_value emif_0 {MEM_LPDDR3_DATA_LATENCY} {LPDDR3_DL_RL12_WL6}
set_instance_parameter_value emif_0 {MEM_LPDDR3_DISCRETE_CS_WIDTH} {1}
set_instance_parameter_value emif_0 {MEM_LPDDR3_DM_EN} {1}
set_instance_parameter_value emif_0 {MEM_LPDDR3_DQODT} {LPDDR3_DQODT_DISABLE}
set_instance_parameter_value emif_0 {MEM_LPDDR3_DQ_WIDTH} {32}
set_instance_parameter_value emif_0 {MEM_LPDDR3_DRV_STR} {LPDDR3_DRV_STR_40D_40U}
set_instance_parameter_value emif_0 {MEM_LPDDR3_PDODT} {LPDDR3_PDODT_DISABLED}
set_instance_parameter_value emif_0 {MEM_LPDDR3_ROW_ADDR_WIDTH} {15}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODT0_1X1} {off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODT0_2X2} {off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODT0_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODT1_2X2} {off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODT1_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODT2_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODT3_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODTN_1X1} {Rank\ 0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODTN_2X2} {Rank\ 0 Rank\ 1}
set_instance_parameter_value emif_0 {MEM_LPDDR3_R_ODTN_4X4} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_LPDDR3_SPEEDBIN_ENUM} {LPDDR3_SPEEDBIN_1600}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDH_DC_MV} {100}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDH_PS} {100}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDQSCKDL} {614}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDQSQ_PS} {135}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDQSS_CYC} {1.25}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDSH_CYC} {0.2}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDSS_CYC} {0.2}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDS_AC_MV} {150}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TDS_PS} {75}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TFAW_NS} {50.0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TIH_DC_MV} {100}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TIH_PS} {100}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TINIT_US} {500}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TIS_AC_MV} {150}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TIS_PS} {75}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TMRR_CK_CYC} {4}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TMRW_CK_CYC} {10}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TQH_CYC} {0.38}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TQSH_CYC} {0.38}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TRAS_NS} {42.5}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TRCD_NS} {18.0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TREFI_US} {3.9}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TRFC_NS} {210.0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TRP_NS} {18.0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TRRD_CYC} {8}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TRTP_CYC} {6}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TWLH_PS} {175.0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TWLS_PS} {175.0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TWR_NS} {15.0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_TWTR_CYC} {6}
set_instance_parameter_value emif_0 {MEM_LPDDR3_USE_DEFAULT_ODT} {1}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODT0_1X1} {on}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODT0_2X2} {on on}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODT0_4X4} {on on on on}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODT1_2X2} {off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODT1_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODT2_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODT3_4X4} {off off off off}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODTN_1X1} {Rank\ 0}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODTN_2X2} {Rank\ 0 Rank\ 1}
set_instance_parameter_value emif_0 {MEM_LPDDR3_W_ODTN_4X4} {Rank\ 0 Rank\ 1 Rank\ 2 Rank\ 3}
set_instance_parameter_value emif_0 {MEM_QDR2_ADDR_WIDTH} {19}
set_instance_parameter_value emif_0 {MEM_QDR2_BL} {4}
set_instance_parameter_value emif_0 {MEM_QDR2_BWS_EN} {1}
set_instance_parameter_value emif_0 {MEM_QDR2_DATA_PER_DEVICE} {36}
set_instance_parameter_value emif_0 {MEM_QDR2_INTERNAL_JITTER_NS} {0.08}
set_instance_parameter_value emif_0 {MEM_QDR2_SPEEDBIN_ENUM} {QDR2_SPEEDBIN_633}
set_instance_parameter_value emif_0 {MEM_QDR2_TCCQO_NS} {0.45}
set_instance_parameter_value emif_0 {MEM_QDR2_TCQDOH_NS} {-0.09}
set_instance_parameter_value emif_0 {MEM_QDR2_TCQD_NS} {0.09}
set_instance_parameter_value emif_0 {MEM_QDR2_TCQH_NS} {0.71}
set_instance_parameter_value emif_0 {MEM_QDR2_THA_NS} {0.18}
set_instance_parameter_value emif_0 {MEM_QDR2_THD_NS} {0.18}
set_instance_parameter_value emif_0 {MEM_QDR2_TRL_CYC} {2.5}
set_instance_parameter_value emif_0 {MEM_QDR2_TSA_NS} {0.23}
set_instance_parameter_value emif_0 {MEM_QDR2_TSD_NS} {0.23}
set_instance_parameter_value emif_0 {MEM_QDR2_WIDTH_EXPANDED} {0}
set_instance_parameter_value emif_0 {MEM_QDR4_AC_ODT_MODE_ENUM} {QDR4_ODT_25_PCT}
set_instance_parameter_value emif_0 {MEM_QDR4_ADDR_INV_ENA} {0}
set_instance_parameter_value emif_0 {MEM_QDR4_ADDR_WIDTH} {21}
set_instance_parameter_value emif_0 {MEM_QDR4_CK_ODT_MODE_ENUM} {QDR4_ODT_25_PCT}
set_instance_parameter_value emif_0 {MEM_QDR4_DATA_INV_ENA} {1}
set_instance_parameter_value emif_0 {MEM_QDR4_DATA_ODT_MODE_ENUM} {QDR4_ODT_25_PCT}
set_instance_parameter_value emif_0 {MEM_QDR4_DQ_PER_PORT_PER_DEVICE} {36}
set_instance_parameter_value emif_0 {MEM_QDR4_PD_OUTPUT_DRIVE_MODE_ENUM} {QDR4_OUTPUT_DRIVE_25_PCT}
set_instance_parameter_value emif_0 {MEM_QDR4_PU_OUTPUT_DRIVE_MODE_ENUM} {QDR4_OUTPUT_DRIVE_25_PCT}
set_instance_parameter_value emif_0 {MEM_QDR4_SPEEDBIN_ENUM} {QDR4_SPEEDBIN_2133}
set_instance_parameter_value emif_0 {MEM_QDR4_TASH_PS} {170}
set_instance_parameter_value emif_0 {MEM_QDR4_TCKDK_MAX_PS} {150}
set_instance_parameter_value emif_0 {MEM_QDR4_TCKDK_MIN_PS} {-150}
set_instance_parameter_value emif_0 {MEM_QDR4_TCKQK_MAX_PS} {225}
set_instance_parameter_value emif_0 {MEM_QDR4_TCSH_PS} {170}
set_instance_parameter_value emif_0 {MEM_QDR4_TISH_PS} {150}
set_instance_parameter_value emif_0 {MEM_QDR4_TQH_CYC} {0.4}
set_instance_parameter_value emif_0 {MEM_QDR4_TQKQ_MAX_PS} {75}
set_instance_parameter_value emif_0 {MEM_QDR4_WIDTH_EXPANDED} {0}
set_instance_parameter_value emif_0 {MEM_RLD2_ADDR_WIDTH} {21}
set_instance_parameter_value emif_0 {MEM_RLD2_BANK_ADDR_WIDTH} {3}
set_instance_parameter_value emif_0 {MEM_RLD2_BL} {4}
set_instance_parameter_value emif_0 {MEM_RLD2_CONFIG_ENUM} {RLD2_CONFIG_TRC_8_TRL_8_TWL_9}
set_instance_parameter_value emif_0 {MEM_RLD2_DM_EN} {1}
set_instance_parameter_value emif_0 {MEM_RLD2_DQ_PER_DEVICE} {9}
set_instance_parameter_value emif_0 {MEM_RLD2_DRIVE_IMPEDENCE_ENUM} {RLD2_DRIVE_IMPEDENCE_INTERNAL_50}
set_instance_parameter_value emif_0 {MEM_RLD2_ODT_MODE_ENUM} {RLD2_ODT_ON}
set_instance_parameter_value emif_0 {MEM_RLD2_REFRESH_INTERVAL_US} {0.24}
set_instance_parameter_value emif_0 {MEM_RLD2_SPEEDBIN_ENUM} {RLD2_SPEEDBIN_18}
set_instance_parameter_value emif_0 {MEM_RLD2_TAH_NS} {0.3}
set_instance_parameter_value emif_0 {MEM_RLD2_TAS_NS} {0.3}
set_instance_parameter_value emif_0 {MEM_RLD2_TCKDK_MAX_NS} {0.3}
set_instance_parameter_value emif_0 {MEM_RLD2_TCKDK_MIN_NS} {-0.3}
set_instance_parameter_value emif_0 {MEM_RLD2_TCKH_CYC} {0.45}
set_instance_parameter_value emif_0 {MEM_RLD2_TCKQK_MAX_NS} {0.2}
set_instance_parameter_value emif_0 {MEM_RLD2_TDH_NS} {0.17}
set_instance_parameter_value emif_0 {MEM_RLD2_TDS_NS} {0.17}
set_instance_parameter_value emif_0 {MEM_RLD2_TQKH_HCYC} {0.9}
set_instance_parameter_value emif_0 {MEM_RLD2_TQKQ_MAX_NS} {0.12}
set_instance_parameter_value emif_0 {MEM_RLD2_TQKQ_MIN_NS} {-0.12}
set_instance_parameter_value emif_0 {MEM_RLD2_WIDTH_EXPANDED} {0}
set_instance_parameter_value emif_0 {MEM_RLD3_ADDR_WIDTH} {20}
set_instance_parameter_value emif_0 {MEM_RLD3_AREF_PROTOCOL_ENUM} {RLD3_AREF_BAC}
set_instance_parameter_value emif_0 {MEM_RLD3_BANK_ADDR_WIDTH} {4}
set_instance_parameter_value emif_0 {MEM_RLD3_BL} {2}
set_instance_parameter_value emif_0 {MEM_RLD3_DATA_LATENCY_MODE_ENUM} {RLD3_DL_RL16_WL17}
set_instance_parameter_value emif_0 {MEM_RLD3_DEPTH_EXPANDED} {0}
set_instance_parameter_value emif_0 {MEM_RLD3_DM_EN} {1}
set_instance_parameter_value emif_0 {MEM_RLD3_DQ_PER_DEVICE} {36}
set_instance_parameter_value emif_0 {MEM_RLD3_ODT_MODE_ENUM} {RLD3_ODT_40}
set_instance_parameter_value emif_0 {MEM_RLD3_OUTPUT_DRIVE_MODE_ENUM} {RLD3_OUTPUT_DRIVE_40}
set_instance_parameter_value emif_0 {MEM_RLD3_SPEEDBIN_ENUM} {RLD3_SPEEDBIN_093E}
set_instance_parameter_value emif_0 {MEM_RLD3_TCKDK_MAX_CYC} {0.27}
set_instance_parameter_value emif_0 {MEM_RLD3_TCKDK_MIN_CYC} {-0.27}
set_instance_parameter_value emif_0 {MEM_RLD3_TCKQK_MAX_PS} {135}
set_instance_parameter_value emif_0 {MEM_RLD3_TDH_DC_MV} {100}
set_instance_parameter_value emif_0 {MEM_RLD3_TDH_PS} {5}
set_instance_parameter_value emif_0 {MEM_RLD3_TDS_AC_MV} {150}
set_instance_parameter_value emif_0 {MEM_RLD3_TDS_PS} {-30}
set_instance_parameter_value emif_0 {MEM_RLD3_TIH_DC_MV} {100}
set_instance_parameter_value emif_0 {MEM_RLD3_TIH_PS} {65}
set_instance_parameter_value emif_0 {MEM_RLD3_TIS_AC_MV} {150}
set_instance_parameter_value emif_0 {MEM_RLD3_TIS_PS} {85}
set_instance_parameter_value emif_0 {MEM_RLD3_TQH_CYC} {0.38}
set_instance_parameter_value emif_0 {MEM_RLD3_TQKQ_MAX_PS} {75}
set_instance_parameter_value emif_0 {MEM_RLD3_T_RC_MODE_ENUM} {RLD3_TRC_9}
set_instance_parameter_value emif_0 {MEM_RLD3_WIDTH_EXPANDED} {0}
set_instance_parameter_value emif_0 {MEM_RLD3_WRITE_PROTOCOL_ENUM} {RLD3_WRITE_1BANK}
set_instance_parameter_value emif_0 {PHY_DDR3_CAL_ADDR0} {0}
set_instance_parameter_value emif_0 {PHY_DDR3_CAL_ADDR1} {8}
set_instance_parameter_value emif_0 {PHY_DDR3_CAL_ENABLE_NON_DES} {0}
set_instance_parameter_value emif_0 {PHY_DDR3_CONFIG_ENUM} {CONFIG_PHY_AND_HARD_CTRL}
set_instance_parameter_value emif_0 {PHY_DDR3_CORE_CLKS_SHARING_ENUM} {CORE_CLKS_SHARING_DISABLED}
set_instance_parameter_value emif_0 {PHY_DDR3_DEFAULT_IO} {1}
set_instance_parameter_value emif_0 {PHY_DDR3_DEFAULT_REF_CLK_FREQ} {1}
set_instance_parameter_value emif_0 {PHY_DDR3_HPS_ENABLE_EARLY_RELEASE} {0}
set_instance_parameter_value emif_0 {PHY_DDR3_IO_VOLTAGE} {1.5}
set_instance_parameter_value emif_0 {PHY_DDR3_MEM_CLK_FREQ_MHZ} {1066.667}
set_instance_parameter_value emif_0 {PHY_DDR3_RATE_ENUM} {RATE_QUARTER}
set_instance_parameter_value emif_0 {PHY_DDR3_REF_CLK_JITTER_PS} {10.0}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_AC_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_AC_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_AC_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_AUTO_STARTING_VREFIN_EN} {1}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_CK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_CK_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_CK_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_DATA_IN_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_DATA_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_DATA_OUT_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_PERIODIC_OCT_RECAL_ENUM} {PERIODIC_OCT_RECAL_AUTO}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_PING_PONG_EN} {0}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_PLL_REF_CLK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_REF_CLK_FREQ_MHZ} {-1.0}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_RZQ_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_DDR3_USER_STARTING_VREFIN} {70.0}
set_instance_parameter_value emif_0 {PHY_DDR4_CONFIG_ENUM} {CONFIG_PHY_AND_HARD_CTRL}
set_instance_parameter_value emif_0 {PHY_DDR4_CORE_CLKS_SHARING_ENUM} {CORE_CLKS_SHARING_DISABLED}
set_instance_parameter_value emif_0 {PHY_DDR4_DEFAULT_IO} {0}
set_instance_parameter_value emif_0 {PHY_DDR4_DEFAULT_REF_CLK_FREQ} {1}
set_instance_parameter_value emif_0 {PHY_DDR4_HPS_ENABLE_EARLY_RELEASE} {0}
set_instance_parameter_value emif_0 {PHY_DDR4_IO_VOLTAGE} {1.2}
set_instance_parameter_value emif_0 {PHY_DDR4_MEM_CLK_FREQ_MHZ} {1200.0}
set_instance_parameter_value emif_0 {PHY_DDR4_RATE_ENUM} {RATE_QUARTER}
set_instance_parameter_value emif_0 {PHY_DDR4_REF_CLK_JITTER_PS} {10.0}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_AC_IO_STD_ENUM} {IO_STD_SSTL_12}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_AC_MODE_ENUM} {OUT_OCT_40_CAL}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_AC_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_AUTO_STARTING_VREFIN_EN} {1}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_CK_IO_STD_ENUM} {IO_STD_SSTL_12}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_CK_MODE_ENUM} {OUT_OCT_40_CAL}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_CK_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_DATA_IN_MODE_ENUM} {IN_OCT_48_CAL}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_DATA_IO_STD_ENUM} {IO_STD_POD_12}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_DATA_OUT_MODE_ENUM} {OUT_OCT_34_CAL}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_PERIODIC_OCT_RECAL_ENUM} {PERIODIC_OCT_RECAL_AUTO}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_PING_PONG_EN} {0}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_PLL_REF_CLK_IO_STD_ENUM} {IO_STD_LVDS_NO_OCT}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_REF_CLK_FREQ_MHZ} {-1.0}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_RZQ_IO_STD_ENUM} {IO_STD_CMOS_12}
set_instance_parameter_value emif_0 {PHY_DDR4_USER_STARTING_VREFIN} {70.0}
set_instance_parameter_value emif_0 {PHY_LPDDR3_CONFIG_ENUM} {CONFIG_PHY_AND_HARD_CTRL}
set_instance_parameter_value emif_0 {PHY_LPDDR3_CORE_CLKS_SHARING_ENUM} {CORE_CLKS_SHARING_DISABLED}
set_instance_parameter_value emif_0 {PHY_LPDDR3_DEFAULT_IO} {1}
set_instance_parameter_value emif_0 {PHY_LPDDR3_DEFAULT_REF_CLK_FREQ} {1}
set_instance_parameter_value emif_0 {PHY_LPDDR3_HPS_ENABLE_EARLY_RELEASE} {0}
set_instance_parameter_value emif_0 {PHY_LPDDR3_IO_VOLTAGE} {1.2}
set_instance_parameter_value emif_0 {PHY_LPDDR3_MEM_CLK_FREQ_MHZ} {800.0}
set_instance_parameter_value emif_0 {PHY_LPDDR3_RATE_ENUM} {RATE_QUARTER}
set_instance_parameter_value emif_0 {PHY_LPDDR3_REF_CLK_JITTER_PS} {10.0}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_AC_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_AC_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_AC_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_AUTO_STARTING_VREFIN_EN} {1}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_CK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_CK_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_CK_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_DATA_IN_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_DATA_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_DATA_OUT_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_PERIODIC_OCT_RECAL_ENUM} {PERIODIC_OCT_RECAL_AUTO}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_PING_PONG_EN} {0}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_PLL_REF_CLK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_REF_CLK_FREQ_MHZ} {-1.0}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_RZQ_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_LPDDR3_USER_STARTING_VREFIN} {70.0}
set_instance_parameter_value emif_0 {PHY_QDR2_CONFIG_ENUM} {CONFIG_PHY_AND_SOFT_CTRL}
set_instance_parameter_value emif_0 {PHY_QDR2_CORE_CLKS_SHARING_ENUM} {CORE_CLKS_SHARING_DISABLED}
set_instance_parameter_value emif_0 {PHY_QDR2_DEFAULT_IO} {1}
set_instance_parameter_value emif_0 {PHY_QDR2_DEFAULT_REF_CLK_FREQ} {1}
set_instance_parameter_value emif_0 {PHY_QDR2_HPS_ENABLE_EARLY_RELEASE} {0}
set_instance_parameter_value emif_0 {PHY_QDR2_IO_VOLTAGE} {1.5}
set_instance_parameter_value emif_0 {PHY_QDR2_MEM_CLK_FREQ_MHZ} {633.333}
set_instance_parameter_value emif_0 {PHY_QDR2_RATE_ENUM} {RATE_HALF}
set_instance_parameter_value emif_0 {PHY_QDR2_REF_CLK_JITTER_PS} {10.0}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_AC_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_AC_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_AC_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_AUTO_STARTING_VREFIN_EN} {1}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_CK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_CK_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_CK_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_DATA_IN_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_DATA_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_DATA_OUT_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_PERIODIC_OCT_RECAL_ENUM} {PERIODIC_OCT_RECAL_AUTO}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_PING_PONG_EN} {0}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_PLL_REF_CLK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_REF_CLK_FREQ_MHZ} {-1.0}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_RZQ_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR2_USER_STARTING_VREFIN} {70.0}
set_instance_parameter_value emif_0 {PHY_QDR4_CONFIG_ENUM} {CONFIG_PHY_AND_SOFT_CTRL}
set_instance_parameter_value emif_0 {PHY_QDR4_CORE_CLKS_SHARING_ENUM} {CORE_CLKS_SHARING_DISABLED}
set_instance_parameter_value emif_0 {PHY_QDR4_DEFAULT_IO} {1}
set_instance_parameter_value emif_0 {PHY_QDR4_DEFAULT_REF_CLK_FREQ} {1}
set_instance_parameter_value emif_0 {PHY_QDR4_HPS_ENABLE_EARLY_RELEASE} {0}
set_instance_parameter_value emif_0 {PHY_QDR4_IO_VOLTAGE} {1.2}
set_instance_parameter_value emif_0 {PHY_QDR4_MEM_CLK_FREQ_MHZ} {1066.667}
set_instance_parameter_value emif_0 {PHY_QDR4_RATE_ENUM} {RATE_QUARTER}
set_instance_parameter_value emif_0 {PHY_QDR4_REF_CLK_JITTER_PS} {10.0}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_AC_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_AC_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_AC_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_AUTO_STARTING_VREFIN_EN} {1}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_CK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_CK_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_CK_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_DATA_IN_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_DATA_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_DATA_OUT_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_PERIODIC_OCT_RECAL_ENUM} {PERIODIC_OCT_RECAL_AUTO}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_PING_PONG_EN} {0}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_PLL_REF_CLK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_REF_CLK_FREQ_MHZ} {-1.0}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_RZQ_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_QDR4_USER_STARTING_VREFIN} {70.0}
set_instance_parameter_value emif_0 {PHY_RLD2_CONFIG_ENUM} {CONFIG_PHY_AND_SOFT_CTRL}
set_instance_parameter_value emif_0 {PHY_RLD2_CORE_CLKS_SHARING_ENUM} {CORE_CLKS_SHARING_DISABLED}
set_instance_parameter_value emif_0 {PHY_RLD2_DEFAULT_IO} {1}
set_instance_parameter_value emif_0 {PHY_RLD2_DEFAULT_REF_CLK_FREQ} {1}
set_instance_parameter_value emif_0 {PHY_RLD2_HPS_ENABLE_EARLY_RELEASE} {0}
set_instance_parameter_value emif_0 {PHY_RLD2_IO_VOLTAGE} {1.8}
set_instance_parameter_value emif_0 {PHY_RLD2_MEM_CLK_FREQ_MHZ} {533.333}
set_instance_parameter_value emif_0 {PHY_RLD2_RATE_ENUM} {RATE_HALF}
set_instance_parameter_value emif_0 {PHY_RLD2_REF_CLK_JITTER_PS} {10.0}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_AC_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_AC_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_AC_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_AUTO_STARTING_VREFIN_EN} {1}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_CK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_CK_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_CK_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_DATA_IN_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_DATA_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_DATA_OUT_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_PERIODIC_OCT_RECAL_ENUM} {PERIODIC_OCT_RECAL_AUTO}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_PING_PONG_EN} {0}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_PLL_REF_CLK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_REF_CLK_FREQ_MHZ} {-1.0}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_RZQ_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD2_USER_STARTING_VREFIN} {70.0}
set_instance_parameter_value emif_0 {PHY_RLD3_CONFIG_ENUM} {CONFIG_PHY_ONLY}
set_instance_parameter_value emif_0 {PHY_RLD3_CORE_CLKS_SHARING_ENUM} {CORE_CLKS_SHARING_DISABLED}
set_instance_parameter_value emif_0 {PHY_RLD3_DEFAULT_IO} {1}
set_instance_parameter_value emif_0 {PHY_RLD3_DEFAULT_REF_CLK_FREQ} {1}
set_instance_parameter_value emif_0 {PHY_RLD3_HPS_ENABLE_EARLY_RELEASE} {0}
set_instance_parameter_value emif_0 {PHY_RLD3_IO_VOLTAGE} {1.2}
set_instance_parameter_value emif_0 {PHY_RLD3_MEM_CLK_FREQ_MHZ} {1066.667}
set_instance_parameter_value emif_0 {PHY_RLD3_RATE_ENUM} {RATE_QUARTER}
set_instance_parameter_value emif_0 {PHY_RLD3_REF_CLK_JITTER_PS} {10.0}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_AC_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_AC_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_AC_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_AUTO_STARTING_VREFIN_EN} {1}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_CK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_CK_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_CK_SLEW_RATE_ENUM} {SLEW_RATE_FAST}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_DATA_IN_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_DATA_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_DATA_OUT_MODE_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_PERIODIC_OCT_RECAL_ENUM} {PERIODIC_OCT_RECAL_AUTO}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_PING_PONG_EN} {0}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_PLL_REF_CLK_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_REF_CLK_FREQ_MHZ} {-1.0}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_RZQ_IO_STD_ENUM} {unset}
set_instance_parameter_value emif_0 {PHY_RLD3_USER_STARTING_VREFIN} {70.0}
set_instance_parameter_value emif_0 {PLL_ADD_EXTRA_CLKS} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_DUTY_CYCLE_GUI_5} {50.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_DUTY_CYCLE_GUI_6} {50.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_DUTY_CYCLE_GUI_7} {50.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_DUTY_CYCLE_GUI_8} {50.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_FREQ_MHZ_GUI_5} {100.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_FREQ_MHZ_GUI_6} {100.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_FREQ_MHZ_GUI_7} {100.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_FREQ_MHZ_GUI_8} {100.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_PHASE_DEG_GUI_5} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_PHASE_DEG_GUI_6} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_PHASE_DEG_GUI_7} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_PHASE_DEG_GUI_8} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_PHASE_PS_GUI_5} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_PHASE_PS_GUI_6} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_PHASE_PS_GUI_7} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_ACTUAL_PHASE_PS_GUI_8} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_DUTY_CYCLE_GUI_5} {50.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_DUTY_CYCLE_GUI_6} {50.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_DUTY_CYCLE_GUI_7} {50.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_DUTY_CYCLE_GUI_8} {50.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_FREQ_MHZ_GUI_5} {100.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_FREQ_MHZ_GUI_6} {100.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_FREQ_MHZ_GUI_7} {100.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_FREQ_MHZ_GUI_8} {100.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_PHASE_GUI_5} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_PHASE_GUI_6} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_PHASE_GUI_7} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_DESIRED_PHASE_GUI_8} {0.0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_0} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_1} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_2} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_3} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_4} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_5} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_6} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_7} {0}
set_instance_parameter_value emif_0 {PLL_EXTRA_CLK_PHASE_SHIFT_UNIT_GUI_8} {0}
set_instance_parameter_value emif_0 {PLL_USER_NUM_OF_EXTRA_CLKS} {0}
set_instance_parameter_value emif_0 {PROTOCOL_ENUM} {PROTOCOL_DDR4}
set_instance_parameter_value emif_0 {SHORT_QSYS_INTERFACE_NAMES} {0}

set_instance_property emif_0 AUTO_EXPORT {true}
