// scifi_datapath_system_v3_arb_hit_type0_supercore_0_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module scifi_datapath_system_v3_arb_hit_type0_supercore_0_mm_interconnect_1 (
		input  wire        clk_bridge_out_clk_clk,                       //                     clk_bridge_out_clk.clk
		input  wire        csr_pipe_1_reset_reset_bridge_in_reset_reset, // csr_pipe_1_reset_reset_bridge_in_reset.reset
		input  wire [4:0]  csr_pipe_1_m0_address,                        //                          csr_pipe_1_m0.address
		output wire        csr_pipe_1_m0_waitrequest,                    //                                       .waitrequest
		input  wire [0:0]  csr_pipe_1_m0_burstcount,                     //                                       .burstcount
		input  wire [3:0]  csr_pipe_1_m0_byteenable,                     //                                       .byteenable
		input  wire        csr_pipe_1_m0_read,                           //                                       .read
		output wire [31:0] csr_pipe_1_m0_readdata,                       //                                       .readdata
		output wire        csr_pipe_1_m0_readdatavalid,                  //                                       .readdatavalid
		input  wire        csr_pipe_1_m0_write,                          //                                       .write
		input  wire [31:0] csr_pipe_1_m0_writedata,                      //                                       .writedata
		input  wire        csr_pipe_1_m0_debugaccess,                    //                                       .debugaccess
		output wire [4:0]  lane_1_csr_address,                           //                             lane_1_csr.address
		output wire        lane_1_csr_write,                             //                                       .write
		output wire        lane_1_csr_read,                              //                                       .read
		input  wire [31:0] lane_1_csr_readdata,                          //                                       .readdata
		output wire [31:0] lane_1_csr_writedata,                         //                                       .writedata
		input  wire        lane_1_csr_waitrequest                        //                                       .waitrequest
	);

	wire         csr_pipe_1_m0_translator_avalon_universal_master_0_waitrequest;   // lane_1_csr_translator:uav_waitrequest -> csr_pipe_1_m0_translator:uav_waitrequest
	wire  [31:0] csr_pipe_1_m0_translator_avalon_universal_master_0_readdata;      // lane_1_csr_translator:uav_readdata -> csr_pipe_1_m0_translator:uav_readdata
	wire         csr_pipe_1_m0_translator_avalon_universal_master_0_debugaccess;   // csr_pipe_1_m0_translator:uav_debugaccess -> lane_1_csr_translator:uav_debugaccess
	wire   [6:0] csr_pipe_1_m0_translator_avalon_universal_master_0_address;       // csr_pipe_1_m0_translator:uav_address -> lane_1_csr_translator:uav_address
	wire         csr_pipe_1_m0_translator_avalon_universal_master_0_read;          // csr_pipe_1_m0_translator:uav_read -> lane_1_csr_translator:uav_read
	wire   [3:0] csr_pipe_1_m0_translator_avalon_universal_master_0_byteenable;    // csr_pipe_1_m0_translator:uav_byteenable -> lane_1_csr_translator:uav_byteenable
	wire         csr_pipe_1_m0_translator_avalon_universal_master_0_readdatavalid; // lane_1_csr_translator:uav_readdatavalid -> csr_pipe_1_m0_translator:uav_readdatavalid
	wire         csr_pipe_1_m0_translator_avalon_universal_master_0_lock;          // csr_pipe_1_m0_translator:uav_lock -> lane_1_csr_translator:uav_lock
	wire         csr_pipe_1_m0_translator_avalon_universal_master_0_write;         // csr_pipe_1_m0_translator:uav_write -> lane_1_csr_translator:uav_write
	wire  [31:0] csr_pipe_1_m0_translator_avalon_universal_master_0_writedata;     // csr_pipe_1_m0_translator:uav_writedata -> lane_1_csr_translator:uav_writedata
	wire   [2:0] csr_pipe_1_m0_translator_avalon_universal_master_0_burstcount;    // csr_pipe_1_m0_translator:uav_burstcount -> lane_1_csr_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (5),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (7),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) csr_pipe_1_m0_translator (
		.clk                    (clk_bridge_out_clk_clk),                                           //                       clk.clk
		.reset                  (csr_pipe_1_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (csr_pipe_1_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (csr_pipe_1_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (csr_pipe_1_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (csr_pipe_1_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (csr_pipe_1_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (csr_pipe_1_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (csr_pipe_1_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (csr_pipe_1_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (csr_pipe_1_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (csr_pipe_1_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (csr_pipe_1_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (csr_pipe_1_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (csr_pipe_1_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (csr_pipe_1_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (csr_pipe_1_m0_byteenable),                                         //                          .byteenable
		.av_read                (csr_pipe_1_m0_read),                                               //                          .read
		.av_readdata            (csr_pipe_1_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (csr_pipe_1_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (csr_pipe_1_m0_write),                                              //                          .write
		.av_writedata           (csr_pipe_1_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (csr_pipe_1_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                             //               (terminated)
		.av_begintransfer       (1'b0),                                                             //               (terminated)
		.av_chipselect          (1'b0),                                                             //               (terminated)
		.av_lock                (1'b0),                                                             //               (terminated)
		.uav_clken              (),                                                                 //               (terminated)
		.av_clken               (1'b1),                                                             //               (terminated)
		.uav_response           (2'b00),                                                            //               (terminated)
		.av_response            (),                                                                 //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                             //               (terminated)
		.av_writeresponsevalid  ()                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (5),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (7),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) lane_1_csr_translator (
		.clk                    (clk_bridge_out_clk_clk),                                           //                      clk.clk
		.reset                  (csr_pipe_1_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (csr_pipe_1_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (csr_pipe_1_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (csr_pipe_1_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (csr_pipe_1_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (csr_pipe_1_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (csr_pipe_1_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (csr_pipe_1_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (csr_pipe_1_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (csr_pipe_1_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (csr_pipe_1_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (csr_pipe_1_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (lane_1_csr_address),                                               //      avalon_anti_slave_0.address
		.av_write               (lane_1_csr_write),                                                 //                         .write
		.av_read                (lane_1_csr_read),                                                  //                         .read
		.av_readdata            (lane_1_csr_readdata),                                              //                         .readdata
		.av_writedata           (lane_1_csr_writedata),                                             //                         .writedata
		.av_waitrequest         (lane_1_csr_waitrequest),                                           //                         .waitrequest
		.av_begintransfer       (),                                                                 //              (terminated)
		.av_beginbursttransfer  (),                                                                 //              (terminated)
		.av_burstcount          (),                                                                 //              (terminated)
		.av_byteenable          (),                                                                 //              (terminated)
		.av_readdatavalid       (1'b0),                                                             //              (terminated)
		.av_writebyteenable     (),                                                                 //              (terminated)
		.av_lock                (),                                                                 //              (terminated)
		.av_chipselect          (),                                                                 //              (terminated)
		.av_clken               (),                                                                 //              (terminated)
		.uav_clken              (1'b0),                                                             //              (terminated)
		.av_debugaccess         (),                                                                 //              (terminated)
		.av_outputenable        (),                                                                 //              (terminated)
		.uav_response           (),                                                                 //              (terminated)
		.av_response            (2'b00),                                                            //              (terminated)
		.uav_writeresponsevalid (),                                                                 //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                              //              (terminated)
	);

endmodule
