// error_int_b002_top.sv
// Integration-TB top for B002 repro:
//   arb_hit_type0_supercore_0 lane run_state propagation through Qsys adapter glue.
//
// This module is the simulator top for the error_b002 bucket.
// It is compiled separately from tb_int_top — do not merge.
//
// DUT: arb_hit_type0_supercore (generated by Qsys 18.1, 8-lane, full tree)
// Stimulus: UVM test via runctl_b002_if virtual interface
//
// Reset polarity note:
//   The supercore rst_reset port is ACTIVE-HIGH (matches arb_hit_type0 internally:
//   "if (rst)" in arb_hit_type0_runctl.sv).
//   Drive rst=1 for first 10 cycles, then rst=0.
//
// Author: Mu3e IP team
// Version : 26.2.0
// Date    : 20260504
// Change  : New — B002 integration repro top.

`timescale 1ns / 1ps

// ---------------------------------------------------------------------------
// Virtual interface: run_ctrl drive + per-lane run_state observation.
// run_state[N] is wired as an input from the DUT hierarchy so the test can
// read it without DPI (avoids UVM_HDL_READ which requires DPI).
// ---------------------------------------------------------------------------
interface runctl_b002_if (
    input logic        clk,
    input logic        rst,
    input logic [2:0]  run_state_0,
    input logic [2:0]  run_state_1,
    input logic [2:0]  run_state_2,
    input logic [2:0]  run_state_3,
    input logic [2:0]  run_state_4,
    input logic [2:0]  run_state_5,
    input logic [2:0]  run_state_6,
    input logic [2:0]  run_state_7
);
    logic        run_ctrl_valid;
    logic [8:0]  run_ctrl_data;

    task clear();
        run_ctrl_valid = 1'b0;
        run_ctrl_data  = 9'h000;
    endtask
endinterface

// ---------------------------------------------------------------------------
// Top module
// ---------------------------------------------------------------------------
module error_int_b002_top;
    timeunit 1ns;
    timeprecision 1ps;

    import uvm_pkg::*;
    `include "uvm_macros.svh"
    import error_int_b002_seq_pkg::*;
    import error_int_b002_test_pkg::*;

    // -----------------------------------------------------------------------
    // Clock and reset
    // -----------------------------------------------------------------------
    logic clk;
    logic rst;

    initial clk = 1'b0;
    always #4 clk = ~clk;   // 125 MHz (8 ns period)

    initial begin
        rst = 1'b1;
        repeat (10) @(posedge clk);
        rst = 1'b0;
    end

    // -----------------------------------------------------------------------
    // Virtual interface — wires run_state from DUT lanes as interface inputs
    // so the test can read them without DPI.
    // These wires are driven by the DUT instances below; they must be declared
    // before the interface instantiation that references them.
    // -----------------------------------------------------------------------
    // lane_run_state wires are driven by hierarchical references into u_dut
    // after the DUT is elaborated.  Declare them here; assign after DUT block.
    wire [2:0] lane_run_state [0:7];

    runctl_b002_if runctl_vif(
        .clk         (clk),
        .rst         (rst),
        .run_state_0 (lane_run_state[0]),
        .run_state_1 (lane_run_state[1]),
        .run_state_2 (lane_run_state[2]),
        .run_state_3 (lane_run_state[3]),
        .run_state_4 (lane_run_state[4]),
        .run_state_5 (lane_run_state[5]),
        .run_state_6 (lane_run_state[6]),
        .run_state_7 (lane_run_state[7])
    );

    // Initialize drive signals
    initial begin
        runctl_vif.run_ctrl_valid = 1'b0;
        runctl_vif.run_ctrl_data  = 9'h000;
    end

    // -----------------------------------------------------------------------
    // Tie-off wires for DUT data ports (not exercised in this repro)
    // -----------------------------------------------------------------------

    // EMU inputs (8 lanes x 7 signals)
    wire [44:0] emu_data_tieoff  = 45'h0;
    wire        emu_valid_tieoff = 1'b0;
    wire [2:0]  emu_err_tieoff   = 3'h0;
    wire [3:0]  emu_chan_tieoff  = 4'h0;
    wire        emu_sop_tieoff  = 1'b0;
    wire        emu_eop_tieoff  = 1'b0;
    wire        emu_eor_tieoff  = 1'b0;

    // REAL inputs (8 lanes x 7 signals)
    wire [44:0] real_data_tieoff  = 45'h0;
    wire        real_valid_tieoff = 1'b0;
    wire [2:0]  real_err_tieoff   = 3'h0;
    wire [3:0]  real_chan_tieoff  = 4'h0;
    wire        real_sop_tieoff  = 1'b0;
    wire        real_eop_tieoff  = 1'b0;
    wire        real_eor_tieoff  = 1'b0;

    // CSR (tie write=0, read=0; readdata/waitrequest are outputs — leave floating)
    wire [4:0]  csr_addr_tieoff  = 5'h0;
    wire        csr_wr_tieoff    = 1'b0;
    wire        csr_rd_tieoff    = 1'b0;
    wire [31:0] csr_wdata_tieoff = 32'h0;

    // -----------------------------------------------------------------------
    // DUT instantiation — arb_hit_type0_supercore
    // Port names exactly as generated in arb_hit_type0_supercore.v
    // -----------------------------------------------------------------------
    arb_hit_type0_supercore u_dut (
        // Clock / Reset
        .clk_clk                     (clk),
        .rst_reset                   (rst),

        // Run control — driven by UVM via virtual interface
        .run_ctrl_valid              (runctl_vif.run_ctrl_valid),
        .run_ctrl_data               (runctl_vif.run_ctrl_data),

        // CSR (all lanes tied off — not under test)
        .csr_0_address               (csr_addr_tieoff),
        .csr_0_write                 (csr_wr_tieoff),
        .csr_0_read                  (csr_rd_tieoff),
        .csr_0_writedata             (csr_wdata_tieoff),
        .csr_0_readdata              (),
        .csr_0_waitrequest           (),

        .csr_1_address               (csr_addr_tieoff),
        .csr_1_write                 (csr_wr_tieoff),
        .csr_1_read                  (csr_rd_tieoff),
        .csr_1_writedata             (csr_wdata_tieoff),
        .csr_1_readdata              (),
        .csr_1_waitrequest           (),

        .csr_2_address               (csr_addr_tieoff),
        .csr_2_write                 (csr_wr_tieoff),
        .csr_2_read                  (csr_rd_tieoff),
        .csr_2_writedata             (csr_wdata_tieoff),
        .csr_2_readdata              (),
        .csr_2_waitrequest           (),

        .csr_3_address               (csr_addr_tieoff),
        .csr_3_write                 (csr_wr_tieoff),
        .csr_3_read                  (csr_rd_tieoff),
        .csr_3_writedata             (csr_wdata_tieoff),
        .csr_3_readdata              (),
        .csr_3_waitrequest           (),

        .csr_4_address               (csr_addr_tieoff),
        .csr_4_write                 (csr_wr_tieoff),
        .csr_4_read                  (csr_rd_tieoff),
        .csr_4_writedata             (csr_wdata_tieoff),
        .csr_4_readdata              (),
        .csr_4_waitrequest           (),

        .csr_5_address               (csr_addr_tieoff),
        .csr_5_write                 (csr_wr_tieoff),
        .csr_5_read                  (csr_rd_tieoff),
        .csr_5_writedata             (csr_wdata_tieoff),
        .csr_5_readdata              (),
        .csr_5_waitrequest           (),

        .csr_6_address               (csr_addr_tieoff),
        .csr_6_write                 (csr_wr_tieoff),
        .csr_6_read                  (csr_rd_tieoff),
        .csr_6_writedata             (csr_wdata_tieoff),
        .csr_6_readdata              (),
        .csr_6_waitrequest           (),

        .csr_7_address               (csr_addr_tieoff),
        .csr_7_write                 (csr_wr_tieoff),
        .csr_7_read                  (csr_rd_tieoff),
        .csr_7_writedata             (csr_wdata_tieoff),
        .csr_7_readdata              (),
        .csr_7_waitrequest           (),

        // EMU inputs (all tied off)
        .emu_in_0_data               (emu_data_tieoff),
        .emu_in_0_valid              (emu_valid_tieoff),
        .emu_in_0_error              (emu_err_tieoff),
        .emu_in_0_channel            (emu_chan_tieoff),
        .emu_in_0_startofpacket      (emu_sop_tieoff),
        .emu_in_0_endofpacket        (emu_eop_tieoff),
        .emu_in_0_endofrun           (emu_eor_tieoff),

        .emu_in_1_data               (emu_data_tieoff),
        .emu_in_1_valid              (emu_valid_tieoff),
        .emu_in_1_error              (emu_err_tieoff),
        .emu_in_1_channel            (emu_chan_tieoff),
        .emu_in_1_startofpacket      (emu_sop_tieoff),
        .emu_in_1_endofpacket        (emu_eop_tieoff),
        .emu_in_1_endofrun           (emu_eor_tieoff),

        .emu_in_2_data               (emu_data_tieoff),
        .emu_in_2_valid              (emu_valid_tieoff),
        .emu_in_2_error              (emu_err_tieoff),
        .emu_in_2_channel            (emu_chan_tieoff),
        .emu_in_2_startofpacket      (emu_sop_tieoff),
        .emu_in_2_endofpacket        (emu_eop_tieoff),
        .emu_in_2_endofrun           (emu_eor_tieoff),

        .emu_in_3_data               (emu_data_tieoff),
        .emu_in_3_valid              (emu_valid_tieoff),
        .emu_in_3_error              (emu_err_tieoff),
        .emu_in_3_channel            (emu_chan_tieoff),
        .emu_in_3_startofpacket      (emu_sop_tieoff),
        .emu_in_3_endofpacket        (emu_eop_tieoff),
        .emu_in_3_endofrun           (emu_eor_tieoff),

        .emu_in_4_data               (emu_data_tieoff),
        .emu_in_4_valid              (emu_valid_tieoff),
        .emu_in_4_error              (emu_err_tieoff),
        .emu_in_4_channel            (emu_chan_tieoff),
        .emu_in_4_startofpacket      (emu_sop_tieoff),
        .emu_in_4_endofpacket        (emu_eop_tieoff),
        .emu_in_4_endofrun           (emu_eor_tieoff),

        .emu_in_5_data               (emu_data_tieoff),
        .emu_in_5_valid              (emu_valid_tieoff),
        .emu_in_5_error              (emu_err_tieoff),
        .emu_in_5_channel            (emu_chan_tieoff),
        .emu_in_5_startofpacket      (emu_sop_tieoff),
        .emu_in_5_endofpacket        (emu_eop_tieoff),
        .emu_in_5_endofrun           (emu_eor_tieoff),

        .emu_in_6_data               (emu_data_tieoff),
        .emu_in_6_valid              (emu_valid_tieoff),
        .emu_in_6_error              (emu_err_tieoff),
        .emu_in_6_channel            (emu_chan_tieoff),
        .emu_in_6_startofpacket      (emu_sop_tieoff),
        .emu_in_6_endofpacket        (emu_eop_tieoff),
        .emu_in_6_endofrun           (emu_eor_tieoff),

        .emu_in_7_data               (emu_data_tieoff),
        .emu_in_7_valid              (emu_valid_tieoff),
        .emu_in_7_error              (emu_err_tieoff),
        .emu_in_7_channel            (emu_chan_tieoff),
        .emu_in_7_startofpacket      (emu_sop_tieoff),
        .emu_in_7_endofpacket        (emu_eop_tieoff),
        .emu_in_7_endofrun           (emu_eor_tieoff),

        // REAL inputs (all tied off)
        .real_in_0_data              (real_data_tieoff),
        .real_in_0_valid             (real_valid_tieoff),
        .real_in_0_error             (real_err_tieoff),
        .real_in_0_channel           (real_chan_tieoff),
        .real_in_0_startofpacket     (real_sop_tieoff),
        .real_in_0_endofpacket       (real_eop_tieoff),
        .real_in_0_endofrun          (real_eor_tieoff),

        .real_in_1_data              (real_data_tieoff),
        .real_in_1_valid             (real_valid_tieoff),
        .real_in_1_error             (real_err_tieoff),
        .real_in_1_channel           (real_chan_tieoff),
        .real_in_1_startofpacket     (real_sop_tieoff),
        .real_in_1_endofpacket       (real_eop_tieoff),
        .real_in_1_endofrun          (real_eor_tieoff),

        .real_in_2_data              (real_data_tieoff),
        .real_in_2_valid             (real_valid_tieoff),
        .real_in_2_error             (real_err_tieoff),
        .real_in_2_channel           (real_chan_tieoff),
        .real_in_2_startofpacket     (real_sop_tieoff),
        .real_in_2_endofpacket       (real_eop_tieoff),
        .real_in_2_endofrun          (real_eor_tieoff),

        .real_in_3_data              (real_data_tieoff),
        .real_in_3_valid             (real_valid_tieoff),
        .real_in_3_error             (real_err_tieoff),
        .real_in_3_channel           (real_chan_tieoff),
        .real_in_3_startofpacket     (real_sop_tieoff),
        .real_in_3_endofpacket       (real_eop_tieoff),
        .real_in_3_endofrun          (real_eor_tieoff),

        .real_in_4_data              (real_data_tieoff),
        .real_in_4_valid             (real_valid_tieoff),
        .real_in_4_error             (real_err_tieoff),
        .real_in_4_channel           (real_chan_tieoff),
        .real_in_4_startofpacket     (real_sop_tieoff),
        .real_in_4_endofpacket       (real_eop_tieoff),
        .real_in_4_endofrun          (real_eor_tieoff),

        .real_in_5_data              (real_data_tieoff),
        .real_in_5_valid             (real_valid_tieoff),
        .real_in_5_error             (real_err_tieoff),
        .real_in_5_channel           (real_chan_tieoff),
        .real_in_5_startofpacket     (real_sop_tieoff),
        .real_in_5_endofpacket       (real_eop_tieoff),
        .real_in_5_endofrun          (real_eor_tieoff),

        .real_in_6_data              (real_data_tieoff),
        .real_in_6_valid             (real_valid_tieoff),
        .real_in_6_error             (real_err_tieoff),
        .real_in_6_channel           (real_chan_tieoff),
        .real_in_6_startofpacket     (real_sop_tieoff),
        .real_in_6_endofpacket       (real_eop_tieoff),
        .real_in_6_endofrun          (real_eor_tieoff),

        .real_in_7_data              (real_data_tieoff),
        .real_in_7_valid             (real_valid_tieoff),
        .real_in_7_error             (real_err_tieoff),
        .real_in_7_channel           (real_chan_tieoff),
        .real_in_7_startofpacket     (real_sop_tieoff),
        .real_in_7_endofpacket       (real_eop_tieoff),
        .real_in_7_endofrun          (real_eor_tieoff),

        // Selected outputs (not monitored in this repro — leave unconnected)
        .selected_out_0_data         (),
        .selected_out_0_valid        (),
        .selected_out_0_error        (),
        .selected_out_0_channel      (),
        .selected_out_0_startofpacket(),
        .selected_out_0_endofpacket  (),
        .selected_out_0_endofrun     (),

        .selected_out_1_data         (),
        .selected_out_1_valid        (),
        .selected_out_1_error        (),
        .selected_out_1_channel      (),
        .selected_out_1_startofpacket(),
        .selected_out_1_endofpacket  (),
        .selected_out_1_endofrun     (),

        .selected_out_2_data         (),
        .selected_out_2_valid        (),
        .selected_out_2_error        (),
        .selected_out_2_channel      (),
        .selected_out_2_startofpacket(),
        .selected_out_2_endofpacket  (),
        .selected_out_2_endofrun     (),

        .selected_out_3_data         (),
        .selected_out_3_valid        (),
        .selected_out_3_error        (),
        .selected_out_3_channel      (),
        .selected_out_3_startofpacket(),
        .selected_out_3_endofpacket  (),
        .selected_out_3_endofrun     (),

        .selected_out_4_data         (),
        .selected_out_4_valid        (),
        .selected_out_4_error        (),
        .selected_out_4_channel      (),
        .selected_out_4_startofpacket(),
        .selected_out_4_endofpacket  (),
        .selected_out_4_endofrun     (),

        .selected_out_5_data         (),
        .selected_out_5_valid        (),
        .selected_out_5_error        (),
        .selected_out_5_channel      (),
        .selected_out_5_startofpacket(),
        .selected_out_5_endofpacket  (),
        .selected_out_5_endofrun     (),

        .selected_out_6_data         (),
        .selected_out_6_valid        (),
        .selected_out_6_error        (),
        .selected_out_6_channel      (),
        .selected_out_6_startofpacket(),
        .selected_out_6_endofpacket  (),
        .selected_out_6_endofrun     (),

        .selected_out_7_data         (),
        .selected_out_7_valid        (),
        .selected_out_7_error        (),
        .selected_out_7_channel      (),
        .selected_out_7_startofpacket(),
        .selected_out_7_endofpacket  (),
        .selected_out_7_endofrun     ()
    );

    // -----------------------------------------------------------------------
    // Wire lane_run_state from DUT hierarchy (no DPI required)
    // Path: u_dut -> lane_N (arb_hit_type0) -> u_runctl (arb_hit_type0_runctl)
    //       -> run_state [2:0]
    // Note: runctl_state is the internal net in arb_hit_type0 connected to
    // u_runctl.run_state.  Either path resolves in Questa.
    // -----------------------------------------------------------------------
    assign lane_run_state[0] = u_dut.lane_0.u_runctl.run_state;
    assign lane_run_state[1] = u_dut.lane_1.u_runctl.run_state;
    assign lane_run_state[2] = u_dut.lane_2.u_runctl.run_state;
    assign lane_run_state[3] = u_dut.lane_3.u_runctl.run_state;
    assign lane_run_state[4] = u_dut.lane_4.u_runctl.run_state;
    assign lane_run_state[5] = u_dut.lane_5.u_runctl.run_state;
    assign lane_run_state[6] = u_dut.lane_6.u_runctl.run_state;
    assign lane_run_state[7] = u_dut.lane_7.u_runctl.run_state;

    // -----------------------------------------------------------------------
    // UVM startup
    // -----------------------------------------------------------------------
    initial begin
        uvm_config_db#(virtual runctl_b002_if)::set(
            null,
            "uvm_test_top",
            "vif",
            runctl_vif);
        run_test();
    end

endmodule
