// prof_int_001_top.sv
// Standalone integration-TB top for PROF-INT-001: full-load 100 kHz/channel
// latency benchmark against arb_hit_type0_supercore generated RTL.
//
// DUT: arb_hit_type0_supercore (generated by Qsys 18.1, 8-lane).
// Scope: lane 0, EMU-mode, 16 channels (0..15), 100 ms simulated time.
//        (See deviation note in _seq.sv: 100 ms instead of 1 s.)
//
// Measurement:
//   abs_ts_a          = emu_in_0_valid assertion time (ns)
//   abs_ts_pre_rbcam  = abs_ts_a + 8  (1-cycle FIFO push estimate)
//   abs_ts_post_rbcam = abs_ts_a + 8  (no separate tap available at top)
//   abs_ts_feb_egress = selected_out_0_valid observation time (ns)
//
// Note on stages 2/3: In this synthesis DUT, the rbCAM stages are internal
// to arb_hit_type0 (they correspond to the ingress FIFO → arbiter pipeline).
// Only the input and output are accessible without hierarchical probing.
// Pre/post-rbCAM fields are therefore set identically to abs_ts_a so those
// two histogram panels show zero-width distributions; all meaningful latency
// content is in the feb_egress panel.
//
// Author: Yifeng Wang
// Version : 26.2.0
// Date    : 20260505
// Change  : New — PROF INT 001 standalone top.

`timescale 1ns / 1ps

// ---------------------------------------------------------------------------
// Virtual interface: wraps all DUT I/O ports needed by the sequence
// ---------------------------------------------------------------------------
interface prof_int_001_dut_if (
    input logic clk,
    input logic rst
);
    // Run control (broadcast to all lanes via splitter inside DUT)
    logic        run_ctrl_valid;
    logic [8:0]  run_ctrl_data;

    // CSR for lane 0 (used to set EMU mode at startup)
    logic [4:0]  csr_0_address;
    logic        csr_0_write;
    logic        csr_0_read;
    logic [31:0] csr_0_writedata;
    logic [31:0] csr_0_readdata;
    logic        csr_0_waitrequest;

    // EMU input, lane 0
    logic [44:0] emu_in_0_data;
    logic        emu_in_0_valid;
    logic [2:0]  emu_in_0_error;
    logic [3:0]  emu_in_0_channel;
    logic        emu_in_0_startofpacket;
    logic        emu_in_0_endofpacket;
    logic        emu_in_0_endofrun;

    // Selected output, lane 0
    logic [44:0] selected_out_0_data;
    logic        selected_out_0_valid;
    logic [2:0]  selected_out_0_error;
    logic [3:0]  selected_out_0_channel;
    logic        selected_out_0_startofpacket;
    logic        selected_out_0_endofpacket;
    logic        selected_out_0_endofrun;

    task automatic clear_inputs();
        run_ctrl_valid             = 1'b0;
        run_ctrl_data              = 9'h001; // IDLE
        csr_0_address              = 5'h0;
        csr_0_write                = 1'b0;
        csr_0_read                 = 1'b0;
        csr_0_writedata            = 32'h0;
        emu_in_0_data              = 45'h0;
        emu_in_0_valid             = 1'b0;
        emu_in_0_error             = 3'b0;
        emu_in_0_channel           = 4'h0;
        emu_in_0_startofpacket     = 1'b0;
        emu_in_0_endofpacket       = 1'b0;
        emu_in_0_endofrun          = 1'b0;
    endtask
endinterface

// ---------------------------------------------------------------------------
// Top module
// ---------------------------------------------------------------------------
module prof_int_001_top;
    timeunit 1ns;
    timeprecision 1ps;

    import uvm_pkg::*;
    `include "uvm_macros.svh"
    import prof_int_001_full_load_100khz_per_channel_seq_pkg::*;
    import prof_int_001_full_load_100khz_per_channel_test_pkg::*;

    // -----------------------------------------------------------------------
    // Clock and reset
    // -----------------------------------------------------------------------
    logic clk;
    logic rst;

    initial clk = 1'b0;
    always #4 clk = ~clk;   // 125 MHz (8 ns period)

    initial begin
        rst = 1'b1;
        repeat (12) @(posedge clk);
        rst = 1'b0;
    end

    // -----------------------------------------------------------------------
    // Virtual interface
    // -----------------------------------------------------------------------
    prof_int_001_dut_if dut_vif(.clk(clk), .rst(rst));

    initial dut_vif.clear_inputs();

    // -----------------------------------------------------------------------
    // Tie-off wires: all ports not driven by the sequence
    // -----------------------------------------------------------------------
    // CSR lanes 1..7
    wire [4:0]  csr_x_addr  = 5'h0;
    wire        csr_x_wr    = 1'b0;
    wire        csr_x_rd    = 1'b0;
    wire [31:0] csr_x_wdata = 32'h0;

    // EMU lanes 1..7 (all tied off)
    wire [44:0] emu_x_data  = 45'h0;
    wire        emu_x_valid = 1'b0;
    wire [2:0]  emu_x_error = 3'h0;
    wire [3:0]  emu_x_chan  = 4'h0;
    wire        emu_x_sop   = 1'b0;
    wire        emu_x_eop   = 1'b0;
    wire        emu_x_eor   = 1'b0;

    // REAL lanes 0..7 (all tied off)
    wire [44:0] real_x_data  = 45'h0;
    wire        real_x_valid = 1'b0;
    wire [2:0]  real_x_error = 3'h0;
    wire [3:0]  real_x_chan  = 4'h0;
    wire        real_x_sop   = 1'b0;
    wire        real_x_eop   = 1'b0;
    wire        real_x_eor   = 1'b0;

    // -----------------------------------------------------------------------
    // DUT instantiation: arb_hit_type0_supercore
    // -----------------------------------------------------------------------
    arb_hit_type0_supercore u_dut (
        .clk_clk                     (clk),
        .rst_reset                   (rst),
        .run_ctrl_valid              (dut_vif.run_ctrl_valid),
        .run_ctrl_data               (dut_vif.run_ctrl_data),

        // CSR lane 0
        .csr_0_address               (dut_vif.csr_0_address),
        .csr_0_write                 (dut_vif.csr_0_write),
        .csr_0_read                  (dut_vif.csr_0_read),
        .csr_0_writedata             (dut_vif.csr_0_writedata),
        .csr_0_readdata              (dut_vif.csr_0_readdata),
        .csr_0_waitrequest           (dut_vif.csr_0_waitrequest),

        // CSR lanes 1..7 (tied off)
        .csr_1_address (csr_x_addr), .csr_1_write (csr_x_wr),
        .csr_1_read    (csr_x_rd),   .csr_1_writedata (csr_x_wdata),
        .csr_1_readdata (), .csr_1_waitrequest (),

        .csr_2_address (csr_x_addr), .csr_2_write (csr_x_wr),
        .csr_2_read    (csr_x_rd),   .csr_2_writedata (csr_x_wdata),
        .csr_2_readdata (), .csr_2_waitrequest (),

        .csr_3_address (csr_x_addr), .csr_3_write (csr_x_wr),
        .csr_3_read    (csr_x_rd),   .csr_3_writedata (csr_x_wdata),
        .csr_3_readdata (), .csr_3_waitrequest (),

        .csr_4_address (csr_x_addr), .csr_4_write (csr_x_wr),
        .csr_4_read    (csr_x_rd),   .csr_4_writedata (csr_x_wdata),
        .csr_4_readdata (), .csr_4_waitrequest (),

        .csr_5_address (csr_x_addr), .csr_5_write (csr_x_wr),
        .csr_5_read    (csr_x_rd),   .csr_5_writedata (csr_x_wdata),
        .csr_5_readdata (), .csr_5_waitrequest (),

        .csr_6_address (csr_x_addr), .csr_6_write (csr_x_wr),
        .csr_6_read    (csr_x_rd),   .csr_6_writedata (csr_x_wdata),
        .csr_6_readdata (), .csr_6_waitrequest (),

        .csr_7_address (csr_x_addr), .csr_7_write (csr_x_wr),
        .csr_7_read    (csr_x_rd),   .csr_7_writedata (csr_x_wdata),
        .csr_7_readdata (), .csr_7_waitrequest (),

        // EMU lane 0
        .emu_in_0_data           (dut_vif.emu_in_0_data),
        .emu_in_0_valid          (dut_vif.emu_in_0_valid),
        .emu_in_0_error          (dut_vif.emu_in_0_error),
        .emu_in_0_channel        (dut_vif.emu_in_0_channel),
        .emu_in_0_startofpacket  (dut_vif.emu_in_0_startofpacket),
        .emu_in_0_endofpacket    (dut_vif.emu_in_0_endofpacket),
        .emu_in_0_endofrun       (dut_vif.emu_in_0_endofrun),

        // EMU lanes 1..7 (tied off)
        .emu_in_1_data (emu_x_data), .emu_in_1_valid (emu_x_valid),
        .emu_in_1_error (emu_x_error), .emu_in_1_channel (emu_x_chan),
        .emu_in_1_startofpacket (emu_x_sop),
        .emu_in_1_endofpacket   (emu_x_eop),
        .emu_in_1_endofrun      (emu_x_eor),

        .emu_in_2_data (emu_x_data), .emu_in_2_valid (emu_x_valid),
        .emu_in_2_error (emu_x_error), .emu_in_2_channel (emu_x_chan),
        .emu_in_2_startofpacket (emu_x_sop),
        .emu_in_2_endofpacket   (emu_x_eop),
        .emu_in_2_endofrun      (emu_x_eor),

        .emu_in_3_data (emu_x_data), .emu_in_3_valid (emu_x_valid),
        .emu_in_3_error (emu_x_error), .emu_in_3_channel (emu_x_chan),
        .emu_in_3_startofpacket (emu_x_sop),
        .emu_in_3_endofpacket   (emu_x_eop),
        .emu_in_3_endofrun      (emu_x_eor),

        .emu_in_4_data (emu_x_data), .emu_in_4_valid (emu_x_valid),
        .emu_in_4_error (emu_x_error), .emu_in_4_channel (emu_x_chan),
        .emu_in_4_startofpacket (emu_x_sop),
        .emu_in_4_endofpacket   (emu_x_eop),
        .emu_in_4_endofrun      (emu_x_eor),

        .emu_in_5_data (emu_x_data), .emu_in_5_valid (emu_x_valid),
        .emu_in_5_error (emu_x_error), .emu_in_5_channel (emu_x_chan),
        .emu_in_5_startofpacket (emu_x_sop),
        .emu_in_5_endofpacket   (emu_x_eop),
        .emu_in_5_endofrun      (emu_x_eor),

        .emu_in_6_data (emu_x_data), .emu_in_6_valid (emu_x_valid),
        .emu_in_6_error (emu_x_error), .emu_in_6_channel (emu_x_chan),
        .emu_in_6_startofpacket (emu_x_sop),
        .emu_in_6_endofpacket   (emu_x_eop),
        .emu_in_6_endofrun      (emu_x_eor),

        .emu_in_7_data (emu_x_data), .emu_in_7_valid (emu_x_valid),
        .emu_in_7_error (emu_x_error), .emu_in_7_channel (emu_x_chan),
        .emu_in_7_startofpacket (emu_x_sop),
        .emu_in_7_endofpacket   (emu_x_eop),
        .emu_in_7_endofrun      (emu_x_eor),

        // REAL lanes 0..7 (all tied off)
        .real_in_0_data (real_x_data), .real_in_0_valid (real_x_valid),
        .real_in_0_error (real_x_error), .real_in_0_channel (real_x_chan),
        .real_in_0_startofpacket (real_x_sop),
        .real_in_0_endofpacket   (real_x_eop),
        .real_in_0_endofrun      (real_x_eor),

        .real_in_1_data (real_x_data), .real_in_1_valid (real_x_valid),
        .real_in_1_error (real_x_error), .real_in_1_channel (real_x_chan),
        .real_in_1_startofpacket (real_x_sop),
        .real_in_1_endofpacket   (real_x_eop),
        .real_in_1_endofrun      (real_x_eor),

        .real_in_2_data (real_x_data), .real_in_2_valid (real_x_valid),
        .real_in_2_error (real_x_error), .real_in_2_channel (real_x_chan),
        .real_in_2_startofpacket (real_x_sop),
        .real_in_2_endofpacket   (real_x_eop),
        .real_in_2_endofrun      (real_x_eor),

        .real_in_3_data (real_x_data), .real_in_3_valid (real_x_valid),
        .real_in_3_error (real_x_error), .real_in_3_channel (real_x_chan),
        .real_in_3_startofpacket (real_x_sop),
        .real_in_3_endofpacket   (real_x_eop),
        .real_in_3_endofrun      (real_x_eor),

        .real_in_4_data (real_x_data), .real_in_4_valid (real_x_valid),
        .real_in_4_error (real_x_error), .real_in_4_channel (real_x_chan),
        .real_in_4_startofpacket (real_x_sop),
        .real_in_4_endofpacket   (real_x_eop),
        .real_in_4_endofrun      (real_x_eor),

        .real_in_5_data (real_x_data), .real_in_5_valid (real_x_valid),
        .real_in_5_error (real_x_error), .real_in_5_channel (real_x_chan),
        .real_in_5_startofpacket (real_x_sop),
        .real_in_5_endofpacket   (real_x_eop),
        .real_in_5_endofrun      (real_x_eor),

        .real_in_6_data (real_x_data), .real_in_6_valid (real_x_valid),
        .real_in_6_error (real_x_error), .real_in_6_channel (real_x_chan),
        .real_in_6_startofpacket (real_x_sop),
        .real_in_6_endofpacket   (real_x_eop),
        .real_in_6_endofrun      (real_x_eor),

        .real_in_7_data (real_x_data), .real_in_7_valid (real_x_valid),
        .real_in_7_error (real_x_error), .real_in_7_channel (real_x_chan),
        .real_in_7_startofpacket (real_x_sop),
        .real_in_7_endofpacket   (real_x_eop),
        .real_in_7_endofrun      (real_x_eor),

        // Selected outputs lane 0 → wired to vif for observation
        .selected_out_0_data         (dut_vif.selected_out_0_data),
        .selected_out_0_valid        (dut_vif.selected_out_0_valid),
        .selected_out_0_error        (dut_vif.selected_out_0_error),
        .selected_out_0_channel      (dut_vif.selected_out_0_channel),
        .selected_out_0_startofpacket(dut_vif.selected_out_0_startofpacket),
        .selected_out_0_endofpacket  (dut_vif.selected_out_0_endofpacket),
        .selected_out_0_endofrun     (dut_vif.selected_out_0_endofrun),

        // Selected outputs lanes 1..7 (not monitored)
        .selected_out_1_data (), .selected_out_1_valid (),
        .selected_out_1_error (), .selected_out_1_channel (),
        .selected_out_1_startofpacket (), .selected_out_1_endofpacket (),
        .selected_out_1_endofrun (),

        .selected_out_2_data (), .selected_out_2_valid (),
        .selected_out_2_error (), .selected_out_2_channel (),
        .selected_out_2_startofpacket (), .selected_out_2_endofpacket (),
        .selected_out_2_endofrun (),

        .selected_out_3_data (), .selected_out_3_valid (),
        .selected_out_3_error (), .selected_out_3_channel (),
        .selected_out_3_startofpacket (), .selected_out_3_endofpacket (),
        .selected_out_3_endofrun (),

        .selected_out_4_data (), .selected_out_4_valid (),
        .selected_out_4_error (), .selected_out_4_channel (),
        .selected_out_4_startofpacket (), .selected_out_4_endofpacket (),
        .selected_out_4_endofrun (),

        .selected_out_5_data (), .selected_out_5_valid (),
        .selected_out_5_error (), .selected_out_5_channel (),
        .selected_out_5_startofpacket (), .selected_out_5_endofpacket (),
        .selected_out_5_endofrun (),

        .selected_out_6_data (), .selected_out_6_valid (),
        .selected_out_6_error (), .selected_out_6_channel (),
        .selected_out_6_startofpacket (), .selected_out_6_endofpacket (),
        .selected_out_6_endofrun (),

        .selected_out_7_data (), .selected_out_7_valid (),
        .selected_out_7_error (), .selected_out_7_channel (),
        .selected_out_7_startofpacket (), .selected_out_7_endofpacket (),
        .selected_out_7_endofrun ()
    );

    // -----------------------------------------------------------------------
    // UVM startup
    // -----------------------------------------------------------------------
    initial begin
        uvm_config_db#(virtual prof_int_001_dut_if)::set(
            null,
            "uvm_test_top",
            "dut_vif",
            dut_vif);
        run_test();
    end

endmodule
