#!/usr/bin/env python3
"""Generate hierarchical CSR documentation from feb_system_v4.sopcinfo + SVDs.

Doc tree it produces (always overwrites the generated regions, between
`<!-- BEGIN auto -->` and `<!-- END auto -->` markers; non-marked text in
SYSTEM_TOP.md stays hand-maintained):

  doc/SYSTEM_TOP.md          -- top-of-tree, shows ONLY the 3 subsystems
  doc/ip_csr/
    <subsystem>.md           -- Level 1 (control/data/upload), region-A/B/C tables
    <sub_subsystem>.md       -- Level 2 (hit_stack_system, mutrig_datapath_system_v4)
    <leaf_ip>.md             -- Level 3 register-layout view (parsed from SVD)

Hard rules enforced across every level:

1. Each generated file starts with `Parent:` linking back one level (or
   "(root)" for SYSTEM_TOP.md).
2. Each file has a `## Inventory` table with the same 6 columns:
   `instance`, `kind`, `version`, `span`, `inside view`, `notes`.
3. The `inside view` column links one level deeper:
   - subsystem -> ip_csr/<sub>.md
   - sub-subsystem -> ip_csr/<sub>.md
   - leaf IP with SVD that we render -> ip_csr/<ip>.md
   - leaf IP without rendered doc -> link to the upstream SVD path
   - vendor IP / no SVD -> `vendor` or `--`
4. Leaf register-layout files include a `## Registers` table with columns:
   `word`, `offset`, `name`, `access`, `description`.
5. Each file ends with a `## Provenance` block citing the sopcinfo + SVD
   sources and the script that generated it.

Usage:
  ./script/generate_csr_docs.py                 # regenerate everything
  ./script/generate_csr_docs.py --check         # exit non-zero if any
                                                # generated file changed

The script is intended to run from `firmware_builds/systems/260518-feb-ok/`
(the system dir), but resolves paths via __file__.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
SYSTEM_DIR = SCRIPT_DIR.parent
DOC_DIR = SYSTEM_DIR / "doc"
IP_CSR_DIR = DOC_DIR / "ip_csr"
SOPCINFO = SYSTEM_DIR / "generated" / "qsys" / "feb_system_v4.sopcinfo"
REPO_ROOT = SYSTEM_DIR.resolve().parents[2]  # firmware_builds/systems/<dated>/.. = mu3e-ip-cores

AUTO_BEGIN = "<!-- BEGIN auto-generated by script/generate_csr_docs.py -->"
AUTO_END = "<!-- END auto-generated -->"

# Kinds that are SUB-SUBSYSTEMS (themselves contain other slaves) —
# collapse to a single row at Level 1, generate a Level 2 doc.
SUB_SUBSYSTEMS = {"hit_stack_system_v4", "mutrig_datapath_system_v4", "arb_hit_type0_supercore"}

# Vendor pass-through bridges hidden at Level 1 (they only forward; the
# downstream slave is what the user reads). The bridge itself stays in
# the qsys for routing; it just does not deserve a row in the addr map.
HIDE_PASSTHROUGH_BRIDGE_KINDS = {
    "altera_avalon_mm_bridge",
    "altera_avalon_mm_clock_crossing_bridge",
}

# Kinds that we explicitly render a register-layout doc for under ip_csr/
# (one per kind; multiple instances of the same kind share one doc)
RENDER_REGISTERS = {"ring_buffer_cam", "feb_frame_assembly", "arb_hit_type0"}

# Top-level subsystem display names (kept stable for SYSTEM_TOP.md)
SUBSYSTEM_ROLES = {
    "control_path_subsystem": "ctrl-path: sc_hub, slow control, board hardware",
    "data_path_subsystem":    "data-path: MuTRiG receive, arbitration, histogram",
    "upload_subsystem":       "upload: run-control mgmt + upload mux",
}

VENDOR_PREFIXES = ("altera_", "multiplexer")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def is_vendor(kind: str) -> bool:
    return any(kind.startswith(p) for p in VENDOR_PREFIXES)


def find_svd(kind: str) -> Path | None:
    """Search repo for `<kind>.svd`, skipping deprecated/trash_bin under our
    REPO_ROOT (REPO_ROOT itself may live under `.worktrees/`, so do not blanket-
    filter that — only filter `.worktrees/` directories *below* REPO_ROOT)."""
    if not REPO_ROOT.exists():
        return None
    repo_str = str(REPO_ROOT.resolve()) + os.sep
    candidates = []
    for p in REPO_ROOT.rglob(f"{kind}.svd"):
        s = str(p.resolve())
        if not s.startswith(repo_str):
            continue
        rel = s[len(repo_str):]
        if rel.startswith("deprecated/") or "/deprecated/" in rel:
            continue
        if rel.startswith("trash_bin/") or "/trash_bin/" in rel:
            continue
        if rel.startswith(".worktrees/") or "/.worktrees/" in rel:
            continue
        candidates.append(p)
    return candidates[0] if candidates else None


def rel_to_doc(p: Path, doc_file: Path) -> str:
    """Make a path relative to a given doc file's directory."""
    try:
        return os.path.relpath(p, doc_file.parent)
    except ValueError:
        return str(p)


def get_param(elem: ET.Element, name: str) -> str | None:
    for p in elem.findall("parameter"):
        if p.get("name") == name:
            v = p.get("value")
            if v is None:
                v = p.findtext("value")
            return v
    return None


def parse_int(v: str | None) -> int | None:
    if v is None or v == "":
        return None
    try:
        return int(v, 0)
    except (ValueError, TypeError):
        return None


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class SlaveEndpoint:
    instance: str          # full instance name in sopcinfo
    port: str              # slave port name
    kind: str              # module kind (IP type)
    version: str           # module version
    span_bytes: int | None # slave addressSpan in bytes
    base_byte: int | None  # base address from the immediate master (None if not yet mapped)


@dataclass
class SubsystemView:
    name: str              # instance name
    kind: str              # subsystem kind
    version: str           # subsystem version
    role: str              # short prose description
    slaves: list[SlaveEndpoint] = field(default_factory=list)


@dataclass
class SubSubsystemView:
    instance: str          # one of the sub-subsystem instances (e.g. hit_stack_subsystem_0)
    kind: str              # sub-subsystem kind
    version: str
    inner_slaves: list[SlaveEndpoint] = field(default_factory=list)


# ---------------------------------------------------------------------------
# SOPC parsing
# ---------------------------------------------------------------------------

def parse_sopcinfo() -> tuple[dict, dict]:
    """Return (modules_by_name, connections_by_start_master)."""
    root = ET.parse(SOPCINFO).getroot()
    modules = {}
    for mod in root.findall(".//module"):
        name = mod.get("name")
        if not name:
            continue
        # capture interfaces
        slaves = []
        for iface in mod.findall("interface"):
            if "slave" not in iface.get("kind", ""):
                continue
            iname = iface.get("name", "")
            span = parse_int(get_param(iface, "addressSpan"))
            slaves.append({"name": iname, "span": span})
        modules[name] = {
            "kind": mod.get("kind", ""),
            "version": mod.get("version", ""),
            "slaves": slaves,
        }
    connections = {}
    for c in root.findall(".//connection"):
        if "avalon" not in c.get("kind", ""):
            continue
        start = c.get("start", "")
        end = c.get("end", "")
        base = parse_int(get_param(c, "baseAddress"))
        connections.setdefault(start, []).append({"end": end, "base": base})
    return modules, connections


# ---------------------------------------------------------------------------
# Hierarchy discovery
# ---------------------------------------------------------------------------

def collect_subsystems(modules: dict, connections: dict) -> dict[str, SubsystemView]:
    """Find the 3 top subsystems and enumerate their immediate slave endpoints.

    Sub-subsystem instances (kind in SUB_SUBSYSTEMS) are collapsed into a
    single row at this level: only the SUB-SUBSYSTEM INSTANCE itself is
    listed, with the inside-view link pointing one level deeper. Inner
    leaf IPs (mutrig_frame_deassembly, ring_buffer_cam, etc.) are not
    repeated at this level — they live in the Level 2 doc."""
    out: dict[str, SubsystemView] = {}
    for name, role in SUBSYSTEM_ROLES.items():
        m = modules.get(name)
        if not m:
            continue
        out[name] = SubsystemView(
            name=name,
            kind=m["kind"],
            version=m["version"],
            role=role,
            slaves=[],
        )

    # Build set of sub-subsystem INSTANCE name prefixes, e.g.
    # 'data_path_subsystem_hit_stack_subsystem_0', so we can suppress
    # any inner slave whose instance name starts with that prefix + '_'.
    sub_sub_instances = {n for n, m in modules.items() if m["kind"] in SUB_SUBSYSTEMS}

    def is_inside_sub_sub(inst_name: str) -> str | None:
        for ssi in sub_sub_instances:
            if inst_name == ssi:
                return None  # the sub-subsystem itself, listed below
            if inst_name.startswith(ssi + "_"):
                return ssi
        return None

    for inst_name, m in modules.items():
        if inst_name in SUBSYSTEM_ROLES:
            continue
        # match to parent subsystem by name prefix
        for sub in out.values():
            if inst_name.startswith(sub.name + "_"):
                if is_inside_sub_sub(inst_name) is not None:
                    # Belongs to a deeper sub-subsystem — skip at this level
                    break
                if m["kind"] in SUB_SUBSYSTEMS:
                    # Collapse the sub-subsystem to a single row at this level
                    # (do not enumerate the boundary slave ports here)
                    out[sub.name].slaves.append(SlaveEndpoint(
                        instance=inst_name,
                        port="(sub-subsystem)",
                        kind=m["kind"],
                        version=m["version"],
                        span_bytes=None,
                        base_byte=None,
                    ))
                    break
                if m["kind"] in HIDE_PASSTHROUGH_BRIDGE_KINDS:
                    # Vendor mm_bridge / mm_clock_crossing_bridge — pure routing,
                    # not user-addressable from the addr-map perspective.
                    break
                for slv in m["slaves"]:
                    out[sub.name].slaves.append(SlaveEndpoint(
                        instance=inst_name,
                        port=slv["name"],
                        kind=m["kind"],
                        version=m["version"],
                        span_bytes=slv["span"],
                        base_byte=None,
                    ))
                break
    return out


def annotate_addresses(subsystems: dict, connections: dict) -> None:
    """Fill in base_byte for each slave by walking the masters we care about."""
    MASTERS = [
        "control_path_subsystem_sc_hub_cmd_pipe.m0",
        "data_path_subsystem_master_datapath.master",
        "upload_subsystem_upload_system_jtag_master.master",
    ]
    edge_base: dict[str, int] = {}
    for master in MASTERS:
        for conn in connections.get(master, []):
            end = conn["end"]
            base = conn["base"]
            if base is None:
                continue
            edge_base[end] = base
    for sub in subsystems.values():
        for slave in sub.slaves:
            key = f"{slave.instance}.{slave.port}"
            slave.base_byte = edge_base.get(key)


def collect_sub_subsystems(modules: dict) -> list[SubSubsystemView]:
    out = []
    for name, m in modules.items():
        if m["kind"] not in SUB_SUBSYSTEMS:
            continue
        inner = []
        for inst_name, m2 in modules.items():
            if inst_name == name:
                continue
            if inst_name.startswith(name + "_"):
                for slv in m2["slaves"]:
                    inner.append(SlaveEndpoint(
                        instance=inst_name,
                        port=slv["name"],
                        kind=m2["kind"],
                        version=m2["version"],
                        span_bytes=slv["span"],
                        base_byte=None,
                    ))
        out.append(SubSubsystemView(
            instance=name, kind=m["kind"], version=m["version"], inner_slaves=inner,
        ))
    return out


# ---------------------------------------------------------------------------
# SVD parsing for leaf register-layout files
# ---------------------------------------------------------------------------

def parse_svd_registers(svd: Path) -> list[dict]:
    root = ET.parse(svd).getroot()
    rows = []
    for reg in root.iter("register"):
        name = (reg.findtext("name") or "?").strip()
        off  = (reg.findtext("addressOffset") or "?").strip()
        acc  = (reg.findtext("access") or "?").strip()
        desc = (reg.findtext("description") or "").strip()
        off_i = parse_int(off)
        word  = off_i // 4 if off_i is not None else None
        rows.append({
            "word": word, "offset": off, "name": name, "access": acc,
            "description": desc.replace("\n", " "),
        })
    rows.sort(key=lambda r: r["word"] if r["word"] is not None else 1<<30)
    return rows


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def render_inside_view_link(slave: SlaveEndpoint, doc_file: Path) -> str:
    """Return the "inside view" cell content for a slave row."""
    if slave.kind in SUB_SUBSYSTEMS:
        target = IP_CSR_DIR / f"{slave.kind}.md"
        return f"[→ {slave.kind}]({rel_to_doc(target, doc_file)})"
    if slave.kind in RENDER_REGISTERS:
        target = IP_CSR_DIR / f"{slave.kind}.md"
        return f"[→ {slave.kind} regs]({rel_to_doc(target, doc_file)})"
    if is_vendor(slave.kind):
        return "vendor"
    svd = find_svd(slave.kind)
    if svd is not None:
        return f"[svd]({rel_to_doc(svd, doc_file)})"
    return "--"


def fmt_addr(b: int | None) -> str:
    return f"0x{b:08x}" if b is not None else "--"


def fmt_span(s: int | None) -> str:
    if s is None:
        return "--"
    if s >= 1024 and s % 1024 == 0:
        return f"{s} B ({s//1024} KB)"
    return f"{s} B"


def make_inventory_table(rows: list[tuple], doc_file: Path) -> list[str]:
    """rows: list of (instance, kind, version, span, inside_view_link, notes)."""
    lines = [
        "| instance | kind | version | span | inside view | notes |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| `{r[0]}` | `{r[1]}` | `{r[2]}` | {r[3]} | {r[4]} | {r[5]} |")
    return lines


def render_subsystem_doc(sub: SubsystemView, out_path: Path) -> str:
    rows = []
    for slv in sorted(sub.slaves, key=lambda s: (s.base_byte if s.base_byte is not None else 1<<31, s.instance)):
        base = fmt_addr(slv.base_byte)
        span = fmt_span(slv.span_bytes)
        link = render_inside_view_link(slv, out_path)
        notes = base
        # Sub-subsystem rows display just the instance name (no .port).
        if slv.port == "(sub-subsystem)":
            inst_label = slv.instance
        else:
            inst_label = f"{slv.instance}.{slv.port}"
        rows.append((inst_label, slv.kind, slv.version, span, link, notes))
    lines = [
        f"# {sub.name}",
        "",
        f"Parent: [SYSTEM_TOP.md](../SYSTEM_TOP.md)",
        "",
        f"Subsystem kind: `{sub.kind}`  ·  version: `{sub.version}`  ·  role: {sub.role}",
        "",
        AUTO_BEGIN,
        "",
        "## Inventory",
        "",
        *make_inventory_table(rows, out_path),
        "",
        "## Provenance",
        "",
        f"- sopcinfo: `{rel_to_doc(SOPCINFO, out_path)}`",
        f"- generator: `{rel_to_doc(SCRIPT_DIR / 'generate_csr_docs.py', out_path)}`",
        f"- regenerated: {dt.datetime.now().isoformat(timespec='seconds')}",
        "",
        AUTO_END,
        "",
    ]
    return "\n".join(lines)


def render_sub_subsystem_doc(ssub: SubSubsystemView, out_path: Path) -> str:
    # Group inner slaves by kind for "click into rbcam" style links
    rows = []
    for slv in sorted(ssub.inner_slaves, key=lambda s: s.instance):
        span = fmt_span(slv.span_bytes)
        link = render_inside_view_link(slv, out_path)
        rows.append((f"{slv.instance}.{slv.port}", slv.kind, slv.version, span, link, ""))
    # Pick a parent doc to link back: the subsystem that contains this sub-subsystem
    parent_kind_to_sub = {
        "hit_stack_system": "data_path_subsystem",
        "mutrig_datapath_system_v4": "data_path_subsystem",
    }
    parent_sub = parent_kind_to_sub.get(ssub.kind, "data_path_subsystem")
    parent_doc = IP_CSR_DIR / f"{parent_sub}.md"
    lines = [
        f"# {ssub.kind} (sub-subsystem of {parent_sub})",
        "",
        f"Parent: [{parent_sub}]({rel_to_doc(parent_doc, out_path)})",
        "",
        f"Sub-subsystem kind: `{ssub.kind}`  ·  representative instance: `{ssub.instance}`  ·  version: `{ssub.version}`",
        "",
        AUTO_BEGIN,
        "",
        "## Inventory (inner slaves of every instance of this sub-subsystem)",
        "",
        *make_inventory_table(rows, out_path),
        "",
        "## Provenance",
        "",
        f"- sopcinfo: `{rel_to_doc(SOPCINFO, out_path)}`",
        f"- generator: `{rel_to_doc(SCRIPT_DIR / 'generate_csr_docs.py', out_path)}`",
        f"- regenerated: {dt.datetime.now().isoformat(timespec='seconds')}",
        "",
        AUTO_END,
        "",
    ]
    return "\n".join(lines)


def parse_svd_registers_full(svd: Path) -> tuple[dict, list[dict]]:
    """Parse the SVD into a (device, [registers]) tuple where each register
    carries its name, address, access, description, reset value, and a list
    of bit fields (name, bitOffset, bitWidth, access, description)."""
    root = ET.parse(svd).getroot()
    dev = {
        "name":    (root.findtext("name") or "?").strip(),
        "vendor":  (root.findtext("vendor") or "?").strip(),
        "version": (root.findtext("version") or "?").strip(),
        "description": (root.findtext("description") or "").strip(),
    }
    regs = []
    for reg in root.iter("register"):
        off_raw = (reg.findtext("addressOffset") or "?").strip()
        off_i   = parse_int(off_raw)
        fields = []
        for f in reg.findall("fields/field"):
            fields.append({
                "name":   (f.findtext("name") or "?").strip(),
                "off":    parse_int(f.findtext("bitOffset") or "0") or 0,
                "width":  parse_int(f.findtext("bitWidth") or "32") or 32,
                "access": (f.findtext("access") or "").strip(),
                "desc":   (f.findtext("description") or "").strip(),
            })
        fields.sort(key=lambda x: x["off"])
        regs.append({
            "name":   (reg.findtext("name") or "?").strip(),
            "offset": off_raw,
            "word":   off_i // 4 if off_i is not None else None,
            "access": (reg.findtext("access") or "?").strip(),
            "desc":   (reg.findtext("description") or "").strip(),
            "reset":  (reg.findtext("resetValue") or "").strip(),
            "fields": fields,
        })
    regs.sort(key=lambda r: r["word"] if r["word"] is not None else 1<<30)
    return dev, regs


def render_leaf_register_doc(kind: str, svd: Path, out_path: Path,
                              parent_kind_doc: Path | None = None) -> str:
    """Render an ARM-style per-IP register-map markdown: summary table at
    the top, then one bullet block per register with description, reset,
    and a bit-field table (when the SVD declares per-bit fields)."""
    dev, regs = parse_svd_registers_full(svd)
    parent = parent_kind_doc if parent_kind_doc is not None else (IP_CSR_DIR / "data_path_subsystem.md")
    lines = [
        f"# {kind} register layout",
        "",
        f"Parent: [{parent.stem}]({rel_to_doc(parent, out_path)})",
        "",
        f"- SVD: `{rel_to_doc(svd, out_path)}`",
        f"- Device: `{dev['name']}` v`{dev['version']}` (vendor `{dev['vendor']}`)",
        f"- Aperture: {len(regs)} registers ({4 * (max([r['word'] for r in regs if r['word'] is not None], default=-1) + 1)} bytes used)",
        "",
        AUTO_BEGIN,
        "",
        "## Summary",
        "",
        "| word | offset | name | access | description |",
        "|---|---|---|---|---|",
    ]
    for r in regs:
        w = f"0x{r['word']:02x}" if r["word"] is not None else "--"
        short_desc = " ".join(r["desc"].split())[:100].replace("|", "\\|")
        anchor = r["name"].lower()
        lines.append(f"| `{w}` | `{r['offset']}` | [`{r['name']}`](#{anchor}) | {r['access']} | {short_desc} |")
    lines.append("")
    lines.append("## Registers (ARM-style detail)")
    lines.append("")
    for r in regs:
        anchor = r["name"].lower()
        lines.append(f"### `{r['name']}` <a id=\"{anchor}\"></a>")
        lines.append("")
        meta = [f"offset `{r['offset']}`", f"word `0x{r['word']:02x}`" if r["word"] is not None else "word `--`",
                f"access `{r['access']}`"]
        if r["reset"]:
            meta.append(f"reset `{r['reset']}`")
        lines.append(" · ".join(meta))
        lines.append("")
        if r["desc"]:
            lines.append(r["desc"])
            lines.append("")
        if r["fields"]:
            lines.append("| bits | name | access | description |")
            lines.append("|---|---|---|---|")
            for f in r["fields"]:
                hi = f["off"] + f["width"] - 1
                bit_range = f"[{hi}:{f['off']}]" if f["width"] > 1 else f"[{f['off']}]"
                fdesc = " ".join((f["desc"] or "").split()).replace("|", "\\|")
                lines.append(f"| `{bit_range}` | `{f['name']}` | {f['access']} | {fdesc} |")
            lines.append("")
        else:
            lines.append("_no bit fields declared in the SVD._")
            lines.append("")
    lines.extend([
        "## Provenance",
        "",
        f"- svd: `{rel_to_doc(svd, out_path)}`",
        f"- generator: `{rel_to_doc(SCRIPT_DIR / 'generate_csr_docs.py', out_path)}`",
        f"- regenerated: {dt.datetime.now().isoformat(timespec='seconds')}",
        "",
        AUTO_END,
        "",
    ])
    return "\n".join(lines)


def render_system_top(subsystems: dict, out_path: Path) -> str:
    rows = []
    for name, sub in subsystems.items():
        link = f"[→ {name}]({rel_to_doc(IP_CSR_DIR / f'{name}.md', out_path)})"
        rows.append((name, sub.kind, sub.version, "--", link, sub.role))
    auto_section = [
        AUTO_BEGIN,
        "",
        "## Subsystems",
        "",
        *make_inventory_table(rows, out_path),
        "",
        "## Provenance",
        "",
        f"- sopcinfo: `{rel_to_doc(SOPCINFO, out_path)}`",
        f"- generator: `{rel_to_doc(SCRIPT_DIR / 'generate_csr_docs.py', out_path)}`",
        f"- regenerated: {dt.datetime.now().isoformat(timespec='seconds')}",
        "",
        AUTO_END,
    ]
    # If SYSTEM_TOP.md already exists, splice in/replace the auto section,
    # preserving any prose above/below.
    if out_path.exists():
        txt = out_path.read_text()
        # Find existing auto block and replace; else append to end.
        pattern = re.compile(
            re.escape(AUTO_BEGIN) + r".*?" + re.escape(AUTO_END), re.DOTALL)
        if pattern.search(txt):
            return pattern.sub("\n".join(auto_section), txt)
        # Append at end with a separator
        return txt.rstrip() + "\n\n" + "\n".join(auto_section) + "\n"
    # Fresh file
    return "\n".join([
        "# FEB SciFi v3 — system top (Level 0)",
        "",
        "Top-of-tree view of the rewired v4 hierarchy under "
        "`firmware_builds/systems/260518-feb-ok/generated/qsys/feb_system_v4.qsys`.",
        "Click any subsystem in the table below to drill one level down.",
        "",
        *auto_section,
        "",
    ])


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

_TIMESTAMP_RE = re.compile(r"^- regenerated:.*$", re.MULTILINE)


def _strip_timestamp(text: str) -> str:
    """Erase the 'regenerated' line so --check ignores time-only drift."""
    return _TIMESTAMP_RE.sub("- regenerated: <stripped>", text)


def write_if_changed(path: Path, content: str, check_only: bool) -> bool:
    """Return True if path content changed (or would change in --check),
    ignoring only the auto-regenerated timestamp line."""
    if path.exists():
        old = path.read_text()
        if _strip_timestamp(old) == _strip_timestamp(content):
            return False
    if check_only:
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if any file would change")
    args = ap.parse_args(argv)
    if not SOPCINFO.exists():
        print(f"sopcinfo missing: {SOPCINFO}", file=sys.stderr)
        return 2
    IP_CSR_DIR.mkdir(parents=True, exist_ok=True)
    modules, connections = parse_sopcinfo()
    subs = collect_subsystems(modules, connections)
    annotate_addresses(subs, connections)
    ssubs = collect_sub_subsystems(modules)
    changed = False
    # 1) per-subsystem (Level 1) docs
    for name, sub in subs.items():
        path = IP_CSR_DIR / f"{name}.md"
        if write_if_changed(path, render_subsystem_doc(sub, path), args.check):
            print(f"  {'check' if args.check else 'wrote'} {path.relative_to(SYSTEM_DIR)}")
            changed = True
    # 2) sub-subsystem (Level 2) docs, one per kind
    seen_kinds = set()
    for ssub in ssubs:
        if ssub.kind in seen_kinds:
            continue
        seen_kinds.add(ssub.kind)
        path = IP_CSR_DIR / f"{ssub.kind}.md"
        if write_if_changed(path, render_sub_subsystem_doc(ssub, path), args.check):
            print(f"  {'check' if args.check else 'wrote'} {path.relative_to(SYSTEM_DIR)}")
            changed = True
    # 3) leaf register-layout docs
    # Map leaf kind -> parent sub-subsystem (for the Parent: link)
    leaf_parent = {}
    for ssub in ssubs:
        for slv in ssub.inner_slaves:
            if slv.kind in RENDER_REGISTERS:
                leaf_parent.setdefault(slv.kind, IP_CSR_DIR / f"{ssub.kind}.md")
    for kind in sorted(RENDER_REGISTERS):
        svd = find_svd(kind)
        if svd is None:
            print(f"  WARN: no SVD found for {kind}", file=sys.stderr)
            continue
        path = IP_CSR_DIR / f"{kind}.md"
        parent_path = leaf_parent.get(kind)
        if write_if_changed(path, render_leaf_register_doc(kind, svd, path, parent_path), args.check):
            print(f"  {'check' if args.check else 'wrote'} {path.relative_to(SYSTEM_DIR)}")
            changed = True
    # 4) SYSTEM_TOP.md (preserve prose, replace auto block)
    top = DOC_DIR / "SYSTEM_TOP.md"
    if write_if_changed(top, render_system_top(subs, top), args.check):
        print(f"  {'check' if args.check else 'wrote'} {top.relative_to(SYSTEM_DIR)}")
        changed = True
    if args.check:
        if changed:
            print("RESULT FAIL — some files would change (run without --check to regenerate)")
            return 1
        print("RESULT PASS — docs are up to date")
        return 0
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
