config opq_upstream_4lane_altera_mm_interconnect_181_amqcmrq_cfg;
		design opq_upstream_4lane_altera_mm_interconnect_181_amqcmrq;
		instance opq_upstream_4lane_altera_mm_interconnect_181_amqcmrq.csr_jtag_master_master_translator use opq_upstream_4lane_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance opq_upstream_4lane_altera_mm_interconnect_181_amqcmrq.opq_0_csr_translator use opq_upstream_4lane_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
endconfig

