// opq_upstream_4lane_altera_mm_interconnect_181_amqcmrq.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module opq_upstream_4lane_altera_mm_interconnect_181_amqcmrq (
		input  wire        clk_bridge_out_clk_clk,                                              //                                            clk_bridge_out_clk.clk
		input  wire        csr_jtag_master_clk_reset_reset_bridge_in_reset_reset,               //               csr_jtag_master_clk_reset_reset_bridge_in_reset.reset
		input  wire        csr_jtag_master_master_translator_reset_reset_bridge_in_reset_reset, // csr_jtag_master_master_translator_reset_reset_bridge_in_reset.reset
		input  wire        opq_0_rst_interface_reset_bridge_in_reset_reset,                     //                     opq_0_rst_interface_reset_bridge_in_reset.reset
		input  wire [31:0] csr_jtag_master_master_address,                                      //                                        csr_jtag_master_master.address
		output wire        csr_jtag_master_master_waitrequest,                                  //                                                              .waitrequest
		input  wire [3:0]  csr_jtag_master_master_byteenable,                                   //                                                              .byteenable
		input  wire        csr_jtag_master_master_read,                                         //                                                              .read
		output wire [31:0] csr_jtag_master_master_readdata,                                     //                                                              .readdata
		output wire        csr_jtag_master_master_readdatavalid,                                //                                                              .readdatavalid
		input  wire        csr_jtag_master_master_write,                                        //                                                              .write
		input  wire [31:0] csr_jtag_master_master_writedata,                                    //                                                              .writedata
		output wire [8:0]  opq_0_csr_address,                                                   //                                                     opq_0_csr.address
		output wire        opq_0_csr_write,                                                     //                                                              .write
		output wire        opq_0_csr_read,                                                      //                                                              .read
		input  wire [31:0] opq_0_csr_readdata,                                                  //                                                              .readdata
		output wire [31:0] opq_0_csr_writedata,                                                 //                                                              .writedata
		output wire [0:0]  opq_0_csr_burstcount,                                                //                                                              .burstcount
		input  wire        opq_0_csr_readdatavalid,                                             //                                                              .readdatavalid
		input  wire        opq_0_csr_waitrequest                                                //                                                              .waitrequest
	);

	wire         csr_jtag_master_master_translator_avalon_universal_master_0_waitrequest;   // opq_0_csr_translator:uav_waitrequest -> csr_jtag_master_master_translator:uav_waitrequest
	wire  [31:0] csr_jtag_master_master_translator_avalon_universal_master_0_readdata;      // opq_0_csr_translator:uav_readdata -> csr_jtag_master_master_translator:uav_readdata
	wire         csr_jtag_master_master_translator_avalon_universal_master_0_debugaccess;   // csr_jtag_master_master_translator:uav_debugaccess -> opq_0_csr_translator:uav_debugaccess
	wire  [31:0] csr_jtag_master_master_translator_avalon_universal_master_0_address;       // csr_jtag_master_master_translator:uav_address -> opq_0_csr_translator:uav_address
	wire         csr_jtag_master_master_translator_avalon_universal_master_0_read;          // csr_jtag_master_master_translator:uav_read -> opq_0_csr_translator:uav_read
	wire   [3:0] csr_jtag_master_master_translator_avalon_universal_master_0_byteenable;    // csr_jtag_master_master_translator:uav_byteenable -> opq_0_csr_translator:uav_byteenable
	wire         csr_jtag_master_master_translator_avalon_universal_master_0_readdatavalid; // opq_0_csr_translator:uav_readdatavalid -> csr_jtag_master_master_translator:uav_readdatavalid
	wire         csr_jtag_master_master_translator_avalon_universal_master_0_lock;          // csr_jtag_master_master_translator:uav_lock -> opq_0_csr_translator:uav_lock
	wire         csr_jtag_master_master_translator_avalon_universal_master_0_write;         // csr_jtag_master_master_translator:uav_write -> opq_0_csr_translator:uav_write
	wire  [31:0] csr_jtag_master_master_translator_avalon_universal_master_0_writedata;     // csr_jtag_master_master_translator:uav_writedata -> opq_0_csr_translator:uav_writedata
	wire   [2:0] csr_jtag_master_master_translator_avalon_universal_master_0_burstcount;    // csr_jtag_master_master_translator:uav_burstcount -> opq_0_csr_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) csr_jtag_master_master_translator (
		.clk                    (clk_bridge_out_clk_clk),                                                    //                       clk.clk
		.reset                  (csr_jtag_master_master_translator_reset_reset_bridge_in_reset_reset),       //                     reset.reset
		.uav_address            (csr_jtag_master_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (csr_jtag_master_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (csr_jtag_master_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (csr_jtag_master_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (csr_jtag_master_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (csr_jtag_master_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (csr_jtag_master_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (csr_jtag_master_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (csr_jtag_master_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (csr_jtag_master_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (csr_jtag_master_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (csr_jtag_master_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (csr_jtag_master_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (csr_jtag_master_master_byteenable),                                         //                          .byteenable
		.av_read                (csr_jtag_master_master_read),                                               //                          .read
		.av_readdata            (csr_jtag_master_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (csr_jtag_master_master_readdatavalid),                                      //                          .readdatavalid
		.av_write               (csr_jtag_master_master_write),                                              //                          .write
		.av_writedata           (csr_jtag_master_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                      //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                      //               (terminated)
		.av_begintransfer       (1'b0),                                                                      //               (terminated)
		.av_chipselect          (1'b0),                                                                      //               (terminated)
		.av_lock                (1'b0),                                                                      //               (terminated)
		.av_debugaccess         (1'b0),                                                                      //               (terminated)
		.uav_clken              (),                                                                          //               (terminated)
		.av_clken               (1'b1),                                                                      //               (terminated)
		.uav_response           (2'b00),                                                                     //               (terminated)
		.av_response            (),                                                                          //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                      //               (terminated)
		.av_writeresponsevalid  ()                                                                           //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (9),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) opq_0_csr_translator (
		.clk                    (clk_bridge_out_clk_clk),                                                    //                      clk.clk
		.reset                  (csr_jtag_master_master_translator_reset_reset_bridge_in_reset_reset),       //                    reset.reset
		.uav_address            (csr_jtag_master_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (csr_jtag_master_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (csr_jtag_master_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (csr_jtag_master_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (csr_jtag_master_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (csr_jtag_master_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (csr_jtag_master_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (csr_jtag_master_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (csr_jtag_master_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (csr_jtag_master_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (csr_jtag_master_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (opq_0_csr_address),                                                         //      avalon_anti_slave_0.address
		.av_write               (opq_0_csr_write),                                                           //                         .write
		.av_read                (opq_0_csr_read),                                                            //                         .read
		.av_readdata            (opq_0_csr_readdata),                                                        //                         .readdata
		.av_writedata           (opq_0_csr_writedata),                                                       //                         .writedata
		.av_burstcount          (opq_0_csr_burstcount),                                                      //                         .burstcount
		.av_readdatavalid       (opq_0_csr_readdatavalid),                                                   //                         .readdatavalid
		.av_waitrequest         (opq_0_csr_waitrequest),                                                     //                         .waitrequest
		.av_begintransfer       (),                                                                          //              (terminated)
		.av_beginbursttransfer  (),                                                                          //              (terminated)
		.av_byteenable          (),                                                                          //              (terminated)
		.av_writebyteenable     (),                                                                          //              (terminated)
		.av_lock                (),                                                                          //              (terminated)
		.av_chipselect          (),                                                                          //              (terminated)
		.av_clken               (),                                                                          //              (terminated)
		.uav_clken              (1'b0),                                                                      //              (terminated)
		.av_debugaccess         (),                                                                          //              (terminated)
		.av_outputenable        (),                                                                          //              (terminated)
		.uav_response           (),                                                                          //              (terminated)
		.av_response            (2'b00),                                                                     //              (terminated)
		.uav_writeresponsevalid (),                                                                          //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                       //              (terminated)
	);

endmodule
