config opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy_cfg;
		design opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.jtag_phy_embedded_in_jtag_master use opq_upstream_4lane_altera_jtag_dc_streaming_181.altera_avalon_st_jtag_interface;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.timing_adt use opq_upstream_4lane_timing_adapter_181.opq_upstream_4lane_timing_adapter_181_v2af63i;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.fifo use opq_upstream_4lane_altera_avalon_sc_fifo_181.altera_avalon_sc_fifo;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.b2p use opq_upstream_4lane_altera_avalon_st_bytes_to_packets_181.altera_avalon_st_bytes_to_packets;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.p2b use opq_upstream_4lane_altera_avalon_st_packets_to_bytes_181.altera_avalon_st_packets_to_bytes;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.transacto use opq_upstream_4lane_altera_avalon_packets_to_master_181.altera_avalon_packets_to_master;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.b2p_adapter use opq_upstream_4lane_channel_adapter_181.opq_upstream_4lane_channel_adapter_181_arrjpdi;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.p2b_adapter use opq_upstream_4lane_channel_adapter_181.opq_upstream_4lane_channel_adapter_181_xiycpqq;
		instance opq_upstream_4lane_altera_jtag_avalon_master_181_dzttzdy.rst_controller use opq_upstream_4lane_altera_reset_controller_181.altera_reset_controller;
endconfig

