#!/usr/bin/env python3
"""Generate a C++ SWB BAR register table from a10_pcie_registers.vhd."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


CONST_RE = re.compile(
    r"^\s*constant\s+([A-Za-z0-9_]+)\s*:\s*integer\s*:=\s*16#([0-9A-Fa-f]+)#\s*;",
)


def parse_registers(path: Path) -> list[tuple[str, int, str]]:
    regs: list[tuple[str, int, str]] = []
    space = "rw"

    for line in path.read_text(encoding="utf-8").splitlines():
        if "Read register Map" in line:
            space = "ro"

        match = CONST_RE.match(line)
        if not match:
            continue

        name, value = match.groups()
        regs.append((name, int(value, 16), space))

    if not regs:
        raise SystemExit(f"no register constants found in {path}")
    return regs


def c_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()

    src = args.input.resolve()
    data = src.read_bytes()
    sha = hashlib.sha256(data).hexdigest()
    regs = parse_registers(src)

    lines = [
        "/* Auto-generated by gen_swb_pcie_registers.py. Do not edit. */",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace swb_pcie_registers_generated {",
        "",
        "enum class reg_space : uint8_t { ro = 0, rw = 1 };",
        "",
        "struct reg_desc {",
        "\tconst char *name;",
        "\tuint32_t offset;",
        "\treg_space space;",
        "};",
        "",
        f'inline constexpr const char *truth_source = "{c_string(str(src))}";',
        f'inline constexpr const char *truth_sha256 = "{sha}";',
        "",
        "inline constexpr reg_desc registers[] = {",
    ]

    for name, value, space in regs:
        lines.append(
            f'\t{{"{name}", 0x{value:02X}u, reg_space::{space}}},'
        )

    lines.extend([
        "};",
        "",
        "inline constexpr size_t register_count = sizeof(registers) / sizeof(registers[0]);",
        "",
        "} // namespace swb_pcie_registers_generated",
        "",
    ])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
